// GENERATED by scripts/gen-protocol.ts from src/protocol/schema.ts
// Do not edit.

/**
 * Shared-memory field indices, matching the engine's generated `protocol.rs`.
 *
 * Indices identify fields; byte offsets come from the engine's descriptor at run
 * time, because they depend on capacity and a list arena can regrow.
 */

export const PROTOCOL_VERSION = 13;

/**
 * Structural fingerprint of every table, field name and element type, in order.
 *
 * Checked against the engine's copy at startup. The version says "the protocol
 * changed on purpose"; this says "both sides were generated from the same
 * schema" — which is the part a field count cannot tell you, because renaming a
 * field or reordering two same-width fields keeps the count identical while
 * changing what the bytes mean.
 */
export const SCHEMA_HASH = 0x91909483;

/** Element size in bytes per field, indexed as `FIELD_SIZES[table][field]`. */
export const FIELD_SIZES: Record<TableName, number[]> = {
  nodes: [1, 2, 4, 4, 4, 4, 2, 1, 1, 4],
  styles: [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 1, 1, 1, 1, 1, 1, 1, 1, 4, 4, 4, 4, 4, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 4, 4, 4, 1, 4, 4, 4, 4, 4, 2, 2, 1, 1, 1, 4, 4, 4, 4, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 2],
  variants: [4, 4, 4],
  variantSlots: [2],
  media: [4, 1, 4],
  lists: [4, 4, 4, 4, 4, 4, 4],
  tweens: [4, 4, 4, 4, 4, 2, 1, 4, 4, 4, 4],
  keyframes: [2, 4, 1, 4, 4, 4, 4],
  controls: [4, 1, 4, 1],
  layout: [4, 4, 4, 4],
  strings: [4, 4],
};

/** Field names per table, in descriptor order — used to name a mismatch. */
export const FIELD_NAMES: Record<TableName, string[]> = {
  nodes: ["kind", "style", "text", "parent", "firstChild", "nextSibling", "list", "hidden", "flags", "activates"],
  styles: ["bg", "fg", "borderColor", "borderWidth", "radiusTopLeft", "radiusTopRight", "radiusBottomRight", "radiusBottomLeft", "padTop", "padRight", "padBottom", "padLeft", "marginTop", "marginRight", "marginBottom", "marginLeft", "display", "flexDirection", "flexWrap", "justifyContent", "alignItems", "alignSelf", "justifyItems", "justifySelf", "flexGrow", "flexShrink", "flexBasis", "gapRow", "gapColumn", "gridColumns", "gridRows", "gridColumnStart", "gridColumnSpan", "gridRowStart", "gridRowSpan", "width", "height", "minWidth", "minHeight", "maxWidth", "maxHeight", "aspectRatio", "position", "insetTop", "insetRight", "insetBottom", "insetLeft", "fontSize", "fontWeight", "lineClamp", "overflowX", "overflowY", "scrollbarWidth", "scrollbarThumb", "scrollbarTrack", "accentColor", "caretColor", "appearance", "opacity", "translateX", "translateY", "translatePercentX", "translatePercentY", "rotate", "scaleX", "scaleY", "skewX", "skewY", "transformOriginPercentX", "transformOriginPercentY", "transformOriginX", "transformOriginY", "transition", "animation"],
  variants: ["node", "mask", "runStart"],
  variantSlots: ["style"],
  media: ["bit", "kind", "value"],
  lists: ["container", "anchorPrev", "anchorNext", "arenaStart", "stride", "capacity", "active"],
  tweens: ["mask", "duration", "delay", "iterations", "firstSegment", "segmentCount", "easing", "easeA", "easeB", "easeC", "easeD"],
  keyframes: ["style", "offset", "easing", "easeA", "easeB", "easeC", "easeD"],
  controls: ["node", "kind", "group", "flags"],
  layout: ["x", "y", "width", "height"],
  strings: ["offset", "length"],
};

/**
 * Whether a change to a field can move a box, for the tables that classify.
 *
 * The engine is the consumer — it uses this to skip Taffy entirely for a
 * paint-only patch. It is emitted here so the compiler's own `LAYOUT_FIELDS`
 * can be checked against it rather than trusted to agree.
 */
export const LAYOUT_AFFECTING: { [K in TableName]?: boolean[] } = {
  styles: [false, false, false, true, false, false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
};

/**
 * Which bit of a tween's `mask` each animatable style field owns.
 *
 * Only the names that *are* animatable, so a lookup miss is the answer to "can
 * this property be transitioned at all" rather than something to compare against a
 * sentinel. The compiler builds a `transition-property` list into a mask through
 * this map, and refuses a property that is absent from it — which is how
 * `transition: width` becomes a named warning rather than a mask bit nothing
 * honours.
 */
export const ANIM_BIT = {
  bg: 0,
  fg: 1,
  borderColor: 2,
  radiusTopLeft: 3,
  radiusTopRight: 4,
  radiusBottomRight: 5,
  radiusBottomLeft: 6,
  scrollbarThumb: 7,
  scrollbarTrack: 8,
  accentColor: 9,
  caretColor: 10,
  opacity: 11,
  translateX: 12,
  translateY: 13,
  translatePercentX: 14,
  translatePercentY: 15,
  rotate: 16,
  scaleX: 17,
  scaleY: 18,
  skewX: 19,
  skewY: 20,
  transformOriginPercentX: 21,
  transformOriginPercentY: 22,
  transformOriginX: 23,
  transformOriginY: 24,
} as const;

/**
 * A style field that can be transitioned, by its **schema** name.
 *
 * The schema's spelling rather than the IR's — `radiusTopLeft`, not `radTL` —
 * because a mask is what crosses the boundary and the engine indexes it with
 * `styles::ANIM_BIT`. Naming the fields the way the wire names them means the
 * compiler's `transition-property` map is type-checked against the schema itself,
 * with no second list translating between the two spellings.
 */
export type AnimatableField = keyof typeof ANIM_BIT;

/** Every animatable field's mask bit at once — what `transition-property: all` means here. */
export const ANIM_ALL = 0x1ffffff;

export const TABLE_NAMES = ["nodes", "styles", "variants", "variantSlots", "media", "lists", "tweens", "keyframes", "controls", "layout", "strings"] as const;
export type TableName = (typeof TABLE_NAMES)[number];

/** Field index per table, in descriptor order. */
export const F = {
  /** Tree structure and per-node indices. */
  nodes: {
    kind: 0, // NodeKind: box, text, button
    style: 1, // Index into the style table
    text: 2, // String slot, or -1
    parent: 3,
    firstChild: 4,
    nextSibling: 5,
    list: 6, // Index into the list table, or -1
    hidden: 7, // Non-zero excludes the subtree entirely
    flags: 8, // Bit 0 interactive, bit 1 measurable text, bit 2 generated (predicates come from parent)
    activates: 9, // The control node a press here operates, or -1
  },
  /** Resolved style values. Patches write field values in place. */
  styles: {
    bg: 0,
    fg: 1,
    borderColor: 2,
    borderWidth: 3,
    radiusTopLeft: 4,
    radiusTopRight: 5,
    radiusBottomRight: 6,
    radiusBottomLeft: 7,
    padTop: 8,
    padRight: 9,
    padBottom: 10,
    padLeft: 11,
    marginTop: 12,
    marginRight: 13,
    marginBottom: 14,
    marginLeft: 15,
    display: 16, // 0 flex, 1 grid, 2 block, 3 none
    flexDirection: 17,
    flexWrap: 18,
    justifyContent: 19,
    alignItems: 20,
    alignSelf: 21,
    justifyItems: 22, // Grid only
    justifySelf: 23, // Grid only
    flexGrow: 24,
    flexShrink: 25,
    flexBasis: 26,
    gapRow: 27,
    gapColumn: 28,
    gridColumns: 29, // repeat(N, minmax(0,1fr)) — Tailwind's grid-cols-N
    gridRows: 30,
    gridColumnStart: 31,
    gridColumnSpan: 32,
    gridRowStart: 33,
    gridRowSpan: 34,
    width: 35,
    height: 36,
    minWidth: 37,
    minHeight: 38,
    maxWidth: 39,
    maxHeight: 40,
    aspectRatio: 41,
    position: 42, // 0 relative, 1 absolute
    insetTop: 43,
    insetRight: 44,
    insetBottom: 45,
    insetLeft: 46,
    fontSize: 47,
    fontWeight: 48,
    lineClamp: 49, // 0 = unlimited; drives SkParagraph maxLines
    overflowX: 50, // 0 visible, 1 hidden, 2 ellipsis, 3 scroll
    overflowY: 51, // 0 visible, 1 hidden, 2 ellipsis, 3 scroll
    scrollbarWidth: 52, // 0 auto, 1 thin, 2 none
    scrollbarThumb: 53,
    scrollbarTrack: 54,
    accentColor: 55,
    caretColor: 56,
    appearance: 57, // 0 none, 1 auto
    opacity: 58, // 0..1, initial 1
    translateX: 59,
    translateY: 60,
    translatePercentX: 61, // fraction of own border-box width
    translatePercentY: 62, // fraction of own border-box height
    rotate: 63, // degrees, unnormalised
    scaleX: 64, // initial 1
    scaleY: 65, // initial 1
    skewX: 66, // degrees
    skewY: 67, // degrees
    transformOriginPercentX: 68, // initial 0.5
    transformOriginPercentY: 69, // initial 0.5
    transformOriginX: 70, // px, added to the percentage
    transformOriginY: 71, // px, added to the percentage
    transition: 72, // tween row + 1, or 0 for none
    animation: 73, // tween row + 1, or 0 for none
  },
  /** Per-node predicate mask and where that node's style run begins. */
  variants: {
    node: 0, // Sorted ascending, for binary search
    mask: 1, // Predicate bits this node's styling reads
    runStart: 2, // First entry in variantSlots
  },
  /** Dense style-slot runs, indexed by compacted live predicate bits. */
  variantSlots: {
    style: 0,
  },
  /** Global predicates the engine re-evaluates from the surface size each frame. */
  media: {
    bit: 0, // The Predicate bit this condition sets when it holds
    kind: 1, // MediaKind: which axis, and which side of the threshold
    value: 2, // Threshold in CSS px, already resolved from rem/em
  },
  /** List arenas: homogeneous item subtrees addressed by stride. */
  lists: {
    container: 0, // The node the rows are children of
    anchorPrev: 1, // Static sibling before the rows, or -1 for firstChild
    anchorNext: 2, // Static sibling after the rows, or -1 for end of chain
    arenaStart: 3,
    stride: 4,
    capacity: 5,
    active: 6,
  },
  /** Interned transition and animation timing. One row per distinct spec. */
  tweens: {
    mask: 0, // Animatable-field bits this tween may move; see styles::ANIM_BIT
    duration: 1, // Seconds for one iteration; 0 disables the tween
    delay: 2, // Seconds before it starts
    iterations: 3, // f32::INFINITY for `infinite`; always 1 for a transition
    firstSegment: 4, // First row in `keyframes`, or -1 when the endpoints are two style rows
    segmentCount: 5,
    easing: 6, // Easing
    easeA: 7, // bezier x1, or the step count
    easeB: 8, // bezier y1, or the StepPosition
    easeC: 9, // bezier x2
    easeD: 10, // bezier y2
  },
  /** Per-animation keyframe list: offset, resolved style row, and segment easing. */
  keyframes: {
    style: 0, // Interned style row this keyframe resolves to
    offset: 1, // 0..1, ascending within a tween's span
    easing: 2, // Easing, or Easing::INHERIT for the animation's
    easeA: 3,
    easeB: 4,
    easeC: 5,
    easeD: 6,
  },
  /** Form controls: kind, radio group, and authored initial state. */
  controls: {
    node: 0, // Sorted ascending, for binary search
    kind: 1, // ControlKind
    group: 2, // Radio group id — interned per (form, name) — or -1
    flags: 3, // ControlFlags: the authored initial state
  },
  /** Final bounds per node, written by the engine. */
  layout: {
    x: 0,
    y: 1,
    width: 2,
    height: 3,
  },
  /** Slot table into the UTF-8 arena. */
  strings: {
    offset: 0,
    length: 1,
  },
} as const;

/** Field counts, asserted against the engine's descriptor at startup. */
export const FIELD_COUNTS: Record<TableName, number> = {
  nodes: 10,
  styles: 74,
  variants: 3,
  variantSlots: 1,
  media: 3,
  lists: 7,
  tweens: 11,
  keyframes: 7,
  controls: 4,
  layout: 4,
  strings: 2,
};

/** Typed-array constructor per field, used to wrap the engine's memory. */
export const FIELD_VIEWS: Record<TableName, unknown[]> = {
  nodes: [Uint8Array, Uint16Array, Int32Array, Int32Array, Int32Array, Int32Array, Int16Array, Uint8Array, Uint8Array, Int32Array],
  styles: [Uint32Array, Uint32Array, Uint32Array, Float32Array, Float32Array, Float32Array, Float32Array, Float32Array, Float32Array, Float32Array, Float32Array, Float32Array, Float32Array, Float32Array, Float32Array, Float32Array, Uint8Array, Uint8Array, Uint8Array, Uint8Array, Uint8Array, Uint8Array, Uint8Array, Uint8Array, Float32Array, Float32Array, Float32Array, Float32Array, Float32Array, Uint16Array, Uint16Array, Int16Array, Int16Array, Int16Array, Int16Array, Float32Array, Float32Array, Float32Array, Float32Array, Float32Array, Float32Array, Float32Array, Uint8Array, Float32Array, Float32Array, Float32Array, Float32Array, Float32Array, Uint16Array, Uint16Array, Uint8Array, Uint8Array, Uint8Array, Uint32Array, Uint32Array, Uint32Array, Uint32Array, Uint8Array, Float32Array, Float32Array, Float32Array, Float32Array, Float32Array, Float32Array, Float32Array, Float32Array, Float32Array, Float32Array, Float32Array, Float32Array, Float32Array, Float32Array, Uint16Array, Uint16Array],
  variants: [Int32Array, Uint32Array, Int32Array],
  variantSlots: [Uint16Array],
  media: [Uint32Array, Uint8Array, Float32Array],
  lists: [Int32Array, Int32Array, Int32Array, Int32Array, Int32Array, Int32Array, Int32Array],
  tweens: [Uint32Array, Float32Array, Float32Array, Float32Array, Int32Array, Uint16Array, Uint8Array, Float32Array, Float32Array, Float32Array, Float32Array],
  keyframes: [Uint16Array, Float32Array, Uint8Array, Float32Array, Float32Array, Float32Array, Float32Array],
  controls: [Int32Array, Uint8Array, Int32Array, Uint8Array],
  layout: [Float32Array, Float32Array, Float32Array, Float32Array],
  strings: [Uint32Array, Uint32Array],
};

/** Shape of the wrapped tables once the descriptor has been read. */
export type SharedTables = {
  nodes: {
    kind: Uint8Array;
    style: Uint16Array;
    text: Int32Array;
    parent: Int32Array;
    firstChild: Int32Array;
    nextSibling: Int32Array;
    list: Int16Array;
    hidden: Uint8Array;
    flags: Uint8Array;
    activates: Int32Array;
  };
  styles: {
    bg: Uint32Array;
    fg: Uint32Array;
    borderColor: Uint32Array;
    borderWidth: Float32Array;
    radiusTopLeft: Float32Array;
    radiusTopRight: Float32Array;
    radiusBottomRight: Float32Array;
    radiusBottomLeft: Float32Array;
    padTop: Float32Array;
    padRight: Float32Array;
    padBottom: Float32Array;
    padLeft: Float32Array;
    marginTop: Float32Array;
    marginRight: Float32Array;
    marginBottom: Float32Array;
    marginLeft: Float32Array;
    display: Uint8Array;
    flexDirection: Uint8Array;
    flexWrap: Uint8Array;
    justifyContent: Uint8Array;
    alignItems: Uint8Array;
    alignSelf: Uint8Array;
    justifyItems: Uint8Array;
    justifySelf: Uint8Array;
    flexGrow: Float32Array;
    flexShrink: Float32Array;
    flexBasis: Float32Array;
    gapRow: Float32Array;
    gapColumn: Float32Array;
    gridColumns: Uint16Array;
    gridRows: Uint16Array;
    gridColumnStart: Int16Array;
    gridColumnSpan: Int16Array;
    gridRowStart: Int16Array;
    gridRowSpan: Int16Array;
    width: Float32Array;
    height: Float32Array;
    minWidth: Float32Array;
    minHeight: Float32Array;
    maxWidth: Float32Array;
    maxHeight: Float32Array;
    aspectRatio: Float32Array;
    position: Uint8Array;
    insetTop: Float32Array;
    insetRight: Float32Array;
    insetBottom: Float32Array;
    insetLeft: Float32Array;
    fontSize: Float32Array;
    fontWeight: Uint16Array;
    lineClamp: Uint16Array;
    overflowX: Uint8Array;
    overflowY: Uint8Array;
    scrollbarWidth: Uint8Array;
    scrollbarThumb: Uint32Array;
    scrollbarTrack: Uint32Array;
    accentColor: Uint32Array;
    caretColor: Uint32Array;
    appearance: Uint8Array;
    opacity: Float32Array;
    translateX: Float32Array;
    translateY: Float32Array;
    translatePercentX: Float32Array;
    translatePercentY: Float32Array;
    rotate: Float32Array;
    scaleX: Float32Array;
    scaleY: Float32Array;
    skewX: Float32Array;
    skewY: Float32Array;
    transformOriginPercentX: Float32Array;
    transformOriginPercentY: Float32Array;
    transformOriginX: Float32Array;
    transformOriginY: Float32Array;
    transition: Uint16Array;
    animation: Uint16Array;
  };
  variants: {
    node: Int32Array;
    mask: Uint32Array;
    runStart: Int32Array;
  };
  variantSlots: {
    style: Uint16Array;
  };
  media: {
    bit: Uint32Array;
    kind: Uint8Array;
    value: Float32Array;
  };
  lists: {
    container: Int32Array;
    anchorPrev: Int32Array;
    anchorNext: Int32Array;
    arenaStart: Int32Array;
    stride: Int32Array;
    capacity: Int32Array;
    active: Int32Array;
  };
  tweens: {
    mask: Uint32Array;
    duration: Float32Array;
    delay: Float32Array;
    iterations: Float32Array;
    firstSegment: Int32Array;
    segmentCount: Uint16Array;
    easing: Uint8Array;
    easeA: Float32Array;
    easeB: Float32Array;
    easeC: Float32Array;
    easeD: Float32Array;
  };
  keyframes: {
    style: Uint16Array;
    offset: Float32Array;
    easing: Uint8Array;
    easeA: Float32Array;
    easeB: Float32Array;
    easeC: Float32Array;
    easeD: Float32Array;
  };
  controls: {
    node: Int32Array;
    kind: Uint8Array;
    group: Int32Array;
    flags: Uint8Array;
  };
  layout: {
    x: Float32Array;
    y: Float32Array;
    width: Float32Array;
    height: Float32Array;
  };
  strings: {
    offset: Uint32Array;
    length: Uint32Array;
  };
};

export const NodeFlags = {
  INTERACTIVE: 1 << 0,
  MEASURABLE: 1 << 1,
  GENERATED: 1 << 2,
} as const;

export const ControlFlags = {
  CHECKED: 1 << 0,
  DISABLED: 1 << 1,
} as const;

/** What a node is. `nodes.kind`. */
export const NodeKind = {
  BOX: 0,
  TEXT: 1,
  BUTTON: 2,
} as const;
export type NodeKind = (typeof NodeKind)[keyof typeof NodeKind];

/** `styles.display`. `NONE` excludes the subtree from layout. */
export const Display = {
  FLEX: 0,
  GRID: 1,
  BLOCK: 2,
  NONE: 3,
} as const;
export type Display = (typeof Display)[keyof typeof Display];

/** `styles.flexDirection`. */
export const FlexDirection = {
  ROW: 0,
  COLUMN: 1,
  ROW_REVERSE: 2,
  COLUMN_REVERSE: 3,
} as const;
export type FlexDirection = (typeof FlexDirection)[keyof typeof FlexDirection];

/** `styles.flexWrap`. */
export const FlexWrap = {
  NO_WRAP: 0,
  WRAP: 1,
  WRAP_REVERSE: 2,
} as const;
export type FlexWrap = (typeof FlexWrap)[keyof typeof FlexWrap];

/** `styles.justifyContent`. CSS `align-content` values, per Taffy. */
export const Justify = {
  FLEX_START: 0,
  CENTER: 1,
  FLEX_END: 2,
  SPACE_BETWEEN: 3,
  SPACE_AROUND: 4,
  SPACE_EVENLY: 5,
  UNSET: 255,
} as const;
export type Justify = (typeof Justify)[keyof typeof Justify];

/** `styles.alignItems` / `alignSelf` / `justifyItems` / `justifySelf`. */
export const Align = {
  FLEX_START: 0,
  CENTER: 1,
  FLEX_END: 2,
  STRETCH: 3,
  BASELINE: 4,
  UNSET: 255,
} as const;
export type Align = (typeof Align)[keyof typeof Align];

/** `styles.position`. */
export const Position = {
  RELATIVE: 0,
  ABSOLUTE: 1,
} as const;
export type Position = (typeof Position)[keyof typeof Position];

/** `styles.overflowX` / `styles.overflowY`. `CLIP` is distinct from `HIDDEN` for one measured reason: Chromium coerces a `visible` axis to `auto` when the other axis is a scroll container, and `clip` is not one — see BROWSER-FACTS.md. */
export const Overflow = {
  VISIBLE: 0,
  HIDDEN: 1,
  ELLIPSIS: 2,
  SCROLL: 3,
  CLIP: 4,
} as const;
export type Overflow = (typeof Overflow)[keyof typeof Overflow];

/** `styles.scrollbarWidth`. The whole grammar: Chromium 151 rejects `thick` and a `<length>` outright, measured — MDN's scrollbars guide is wrong about both. `NONE` hides the bar without disabling the wheel, which is exactly what the property means. */
export const ScrollbarWidth = {
  AUTO: 0,
  THIN: 1,
  NONE: 2,
} as const;
export type ScrollbarWidth = (typeof ScrollbarWidth)[keyof typeof ScrollbarWidth];

/** `styles.appearance`. An *effect*, not the specified value — `<compat-auto>` keywords all collapse to `AUTO` here, which is what the spec says they do and what makes storing nine more variants pointless. `BASE_SELECT` is the opt-in that makes a `<select>` and its `::picker(select)` fully styleable; it is the one value that changes what gets drawn rather than merely whether. Measured against Chromium 151 — see BROWSER-FACTS.md. */
export const Appearance = {
  NONE: 0,
  AUTO: 1,
  BASE_SELECT: 2,
} as const;
export type Appearance = (typeof Appearance)[keyof typeof Appearance];

/** `media.kind`. Which axis a threshold tests, and which side of it counts as true. `MIN_*` holds at the threshold and above, `MAX_*` at it and below — the same inclusive bounds `min-width`/`max-width` have in CSS, which is why a `min-width: 768px` and a `max-width: 768px` query are both true at exactly 768. */
export const MediaKind = {
  MIN_WIDTH: 0,
  MAX_WIDTH: 1,
  MIN_HEIGHT: 2,
  MAX_HEIGHT: 3,
} as const;
export type MediaKind = (typeof MediaKind)[keyof typeof MediaKind];

/** Bit positions in a variant mask. Bits 0-4 are per-node; higher bits are global, so the engine can flip them without knowing which nodes care. */
export const Predicate = {
  HOVER: 1,
  ACTIVE: 2,
  FOCUS: 4,
  CHECKED: 8,
  DISABLED: 16,
  FIRST_GLOBAL: 256,
} as const;
export type Predicate = (typeof Predicate)[keyof typeof Predicate];

/** `styles.INTERP`. How a field's value is found partway between two style rows. `NONE` is discrete and is what every enum gets. See the `Interp` doc comment in schema.ts for why a colour is its own kind rather than a number. */
export const Interp = {
  NONE: 0,
  NUMBER: 1,
  COLOR: 2,
} as const;
export type Interp = (typeof Interp)[keyof typeof Interp];

/** `tweens.easing` and `keyframes.easing`. Which curve maps elapsed fraction to progress. The keywords are **not** normalised to `cubic-bezier()` by CSS — `ease` reads back as `ease` — but they are here, because a keyword is a bezier with fixed control points and storing five of them separately would be five ways to spell one curve. The two step keywords do normalise in CSS: `step-start` is `steps(1, start)` and `step-end` is `steps(1)`. Measured — see BROWSER-FACTS.md. */
export const Easing = {
  LINEAR: 0,
  CUBIC_BEZIER: 1,
  STEPS: 2,
  INHERIT: 255,
} as const;
export type Easing = (typeof Easing)[keyof typeof Easing];

/** `keyframes.easeB` / `tweens.easeB` when the easing is `STEPS`. Which end of each step the jump happens at. `steps(4, end)` reads 0 at t=0.1 and 0.75 at t=0.9; `steps(4, start)` reads 0.25 and 1.0 — measured, and the pair that tells them apart. */
export const StepPosition = {
  JUMP_END: 0,
  JUMP_START: 1,
  JUMP_BOTH: 2,
  JUMP_NONE: 3,
} as const;
export type StepPosition = (typeof StepPosition)[keyof typeof StepPosition];

/** Engine → Bun. Drained after `tick()`; `0` means the queue is empty. */
export const EventKind = {
  NONE: 0,
  QUIT: 1,
  RESIZE: 2,
  MOUSE_MOVE: 3,
  MOUSE_DOWN: 4,
  MOUSE_UP: 5,
  CLICK: 6,
  KEY_DOWN: 7,
  TEXT_INPUT: 8,
  FOCUS: 9,
  CHANGE: 10,
} as const;
export type EventKind = (typeof EventKind)[keyof typeof EventKind];

/** `controls.kind`. What a press does to this node, which is the only thing the engine needs to know about a control — appearance is the stylesheet's job and is already resolved into the style table. `CHECKBOX` toggles; `RADIO` sets itself and clears its group, and cannot be unchecked by pointer (measured). */
export const ControlKind = {
  NONE: 0,
  CHECKBOX: 1,
  RADIO: 2,
} as const;
export type ControlKind = (typeof ControlKind)[keyof typeof ControlKind];

/** Return code of every FFI entry point. Negative is failure, and the detail is in `dziri_last_error`. */
export const Status = {
  OK: 0,
  PANIC: -1,
  INVALID_HANDLE: -2,
  INVALID_ARGUMENT: -3,
  PROTOCOL_MISMATCH: -4,
  CAPACITY: -5,
  SDL: -6,
  SKIA: -7,
  LAYOUT: -8,
  POISONED: -9,
} as const;
export type Status = (typeof Status)[keyof typeof Status];

/**
 * Style fields as the compiler sees them: [IR name, view constructor, inherited,
 * affectsLayout].
 *
 * `ir.ts` used to declare this by hand beside the schema's own list, and the two
 * restated each other four ways: the name twice in two spellings, the view
 * constructor as a second encoding of `type`, and `affectsLayout` as a second
 * encoding of `affects`. `schema.test.ts` existed to assert they agreed and said
 * so outright — "nothing but this file makes them agree". Two of the four columns
 * were already derivable with zero mismatches when this was generated; the other
 * two are now named on the schema row as `ir` and `inherited`.
 *
 * `lineClamp` is absent because it has no IR row: it is on the wire for
 * SkParagraph's `maxLines` and the compiler does not write it yet.
 *
 * Order is the schema's. It used to be the order this list happened to be written
 * in, which had drifted — `justifyItems` and `justifySelf` were appended here and
 * inserted mid-table there. Nothing indexes these arrays positionally across the
 * boundary (the artifact's style table is keyed by name and `upload.ts` maps by
 * name), so adopting one order moved no value.
 */
export const STYLE_FIELDS = [
  ["bg", "Uint32Array", false, false],
  ["fg", "Uint32Array", true, false],
  ["borderColor", "Uint32Array", false, false],
  ["borderWidth", "Float32Array", false, true],
  ["radTL", "Float32Array", false, false],
  ["radTR", "Float32Array", false, false],
  ["radBR", "Float32Array", false, false],
  ["radBL", "Float32Array", false, false],
  ["padT", "Float32Array", false, true],
  ["padR", "Float32Array", false, true],
  ["padB", "Float32Array", false, true],
  ["padL", "Float32Array", false, true],
  ["marT", "Float32Array", false, true],
  ["marR", "Float32Array", false, true],
  ["marB", "Float32Array", false, true],
  ["marL", "Float32Array", false, true],
  ["display", "Uint8Array", false, true],
  ["direction", "Uint8Array", false, true],
  ["wrap", "Uint8Array", false, true],
  ["justify", "Uint8Array", false, true],
  ["align", "Uint8Array", false, true],
  ["alignSelf", "Uint8Array", false, true],
  ["justifyItems", "Uint8Array", false, true],
  ["justifySelf", "Uint8Array", false, true],
  ["grow", "Float32Array", false, true],
  ["shrink", "Float32Array", false, true],
  ["basis", "Float32Array", false, true],
  ["gapRow", "Float32Array", false, true],
  ["gapCol", "Float32Array", false, true],
  ["gridCols", "Uint16Array", false, true],
  ["gridRows", "Uint16Array", false, true],
  ["gridColStart", "Int16Array", false, true],
  ["gridColSpan", "Int16Array", false, true],
  ["gridRowStart", "Int16Array", false, true],
  ["gridRowSpan", "Int16Array", false, true],
  ["width", "Float32Array", false, true],
  ["height", "Float32Array", false, true],
  ["minW", "Float32Array", false, true],
  ["minH", "Float32Array", false, true],
  ["maxW", "Float32Array", false, true],
  ["maxH", "Float32Array", false, true],
  ["aspectRatio", "Float32Array", false, true],
  ["position", "Uint8Array", false, true],
  ["insetT", "Float32Array", false, true],
  ["insetR", "Float32Array", false, true],
  ["insetB", "Float32Array", false, true],
  ["insetL", "Float32Array", false, true],
  ["fontSize", "Float32Array", true, true],
  ["fontWeight", "Uint16Array", true, true],
  ["overflowX", "Uint8Array", false, true],
  ["overflowY", "Uint8Array", false, true],
  ["scrollbarWidth", "Uint8Array", false, false],
  ["scrollbarThumb", "Uint32Array", true, false],
  ["scrollbarTrack", "Uint32Array", true, false],
  ["accentColor", "Uint32Array", true, false],
  ["caretColor", "Uint32Array", true, false],
  ["appearance", "Uint8Array", false, false],
  ["opacity", "Float32Array", false, false],
  ["translateX", "Float32Array", false, false],
  ["translateY", "Float32Array", false, false],
  ["translatePctX", "Float32Array", false, false],
  ["translatePctY", "Float32Array", false, false],
  ["rotate", "Float32Array", false, false],
  ["scaleX", "Float32Array", false, false],
  ["scaleY", "Float32Array", false, false],
  ["skewX", "Float32Array", false, false],
  ["skewY", "Float32Array", false, false],
  ["originPctX", "Float32Array", false, false],
  ["originPctY", "Float32Array", false, false],
  ["originPxX", "Float32Array", false, false],
  ["originPxY", "Float32Array", false, false],
  ["transition", "Uint16Array", false, false],
  ["animation", "Uint16Array", false, false],
] as const;

/**
 * Each style field the compiler emits, paired with where it lands in the schema.
 *
 * The spellings differ deliberately — the wire name is read by someone debugging a
 * byte offset, the IR name is read a hundred times in the property expander — and
 * the *encodings* were chosen to match, so `direction`, `justify` and `align` need
 * no translation beyond the rename. That was not luck: the schema's enums were
 * written from the IR's.
 */
export const NUMBER_FIELDS: Array<[keyof typeof F.styles, (typeof STYLE_FIELDS)[number][0]]> = [
  ["bg", "bg"],
  ["fg", "fg"],
  ["borderColor", "borderColor"],
  ["borderWidth", "borderWidth"],
  ["radiusTopLeft", "radTL"],
  ["radiusTopRight", "radTR"],
  ["radiusBottomRight", "radBR"],
  ["radiusBottomLeft", "radBL"],
  ["padTop", "padT"],
  ["padRight", "padR"],
  ["padBottom", "padB"],
  ["padLeft", "padL"],
  ["marginTop", "marT"],
  ["marginRight", "marR"],
  ["marginBottom", "marB"],
  ["marginLeft", "marL"],
  ["display", "display"],
  ["flexDirection", "direction"],
  ["flexWrap", "wrap"],
  ["justifyContent", "justify"],
  ["alignItems", "align"],
  ["alignSelf", "alignSelf"],
  ["justifyItems", "justifyItems"],
  ["justifySelf", "justifySelf"],
  ["flexGrow", "grow"],
  ["flexShrink", "shrink"],
  ["flexBasis", "basis"],
  ["gapRow", "gapRow"],
  ["gapColumn", "gapCol"],
  ["gridColumns", "gridCols"],
  ["gridRows", "gridRows"],
  ["gridColumnStart", "gridColStart"],
  ["gridColumnSpan", "gridColSpan"],
  ["gridRowStart", "gridRowStart"],
  ["gridRowSpan", "gridRowSpan"],
  ["width", "width"],
  ["height", "height"],
  ["minWidth", "minW"],
  ["minHeight", "minH"],
  ["maxWidth", "maxW"],
  ["maxHeight", "maxH"],
  ["aspectRatio", "aspectRatio"],
  ["position", "position"],
  ["insetTop", "insetT"],
  ["insetRight", "insetR"],
  ["insetBottom", "insetB"],
  ["insetLeft", "insetL"],
  ["fontSize", "fontSize"],
  ["fontWeight", "fontWeight"],
  ["overflowX", "overflowX"],
  ["overflowY", "overflowY"],
  ["scrollbarWidth", "scrollbarWidth"],
  ["scrollbarThumb", "scrollbarThumb"],
  ["scrollbarTrack", "scrollbarTrack"],
  ["accentColor", "accentColor"],
  ["caretColor", "caretColor"],
  ["appearance", "appearance"],
  ["opacity", "opacity"],
  ["translateX", "translateX"],
  ["translateY", "translateY"],
  ["translatePercentX", "translatePctX"],
  ["translatePercentY", "translatePctY"],
  ["rotate", "rotate"],
  ["scaleX", "scaleX"],
  ["scaleY", "scaleY"],
  ["skewX", "skewX"],
  ["skewY", "skewY"],
  ["transformOriginPercentX", "originPctX"],
  ["transformOriginPercentY", "originPctY"],
  ["transformOriginX", "originPxX"],
  ["transformOriginY", "originPxY"],
  ["transition", "transition"],
  ["animation", "animation"],
];
