// GENERATED by scripts/gen-protocol.ts from src/protocol/schema.ts
// Do not edit.

/**
 * Shared-memory field indices, matching the engine's generated `protocol.rs`.
 *
 * Indices identify fields; byte offsets come from the engine's descriptor at run
 * time, because they depend on capacity and a list arena can regrow.
 */

export const PROTOCOL_VERSION = 4;

/**
 * Structural fingerprint of every table, field name and element type, in order.
 *
 * Checked against the engine's copy at startup. The version says "the protocol
 * changed on purpose"; this says "both sides were generated from the same
 * schema" — which is the part a field count cannot tell you, because renaming a
 * field or reordering two same-width fields keeps the count identical while
 * changing what the bytes mean.
 */
export const SCHEMA_HASH = 0x917d9cf3;

/** Element size in bytes per field, indexed as `FIELD_SIZES[table][field]`. */
export const FIELD_SIZES: Record<TableName, number[]> = {
  nodes: [1, 2, 4, 4, 4, 4, 2, 1, 1],
  styles: [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 1, 1, 1, 1, 1, 1, 1, 1, 4, 4, 4, 4, 4, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 4, 4, 4, 1, 4, 4, 4, 4, 4, 2, 2, 1, 1],
  variants: [4, 4, 4],
  variantSlots: [2],
  lists: [4, 4, 4, 4, 4, 4, 4],
  layout: [4, 4, 4, 4],
  strings: [4, 4],
};

/** Field names per table, in descriptor order — used to name a mismatch. */
export const FIELD_NAMES: Record<TableName, string[]> = {
  nodes: ["kind", "style", "text", "parent", "firstChild", "nextSibling", "list", "hidden", "flags"],
  styles: ["bg", "fg", "borderColor", "borderWidth", "radius", "padTop", "padRight", "padBottom", "padLeft", "marginTop", "marginRight", "marginBottom", "marginLeft", "display", "flexDirection", "flexWrap", "justifyContent", "alignItems", "alignSelf", "justifyItems", "justifySelf", "flexGrow", "flexShrink", "flexBasis", "gapRow", "gapColumn", "gridColumns", "gridRows", "gridColumnStart", "gridColumnSpan", "gridRowStart", "gridRowSpan", "width", "height", "minWidth", "minHeight", "maxWidth", "maxHeight", "aspectRatio", "position", "insetTop", "insetRight", "insetBottom", "insetLeft", "fontSize", "fontWeight", "lineClamp", "overflowX", "overflowY"],
  variants: ["node", "mask", "runStart"],
  variantSlots: ["style"],
  lists: ["container", "anchorPrev", "anchorNext", "arenaStart", "stride", "capacity", "active"],
  layout: ["x", "y", "width", "height"],
  strings: ["offset", "length"],
};

/**
 * Whether a change to a field can move a box, for the tables that classify.
 *
 * The engine is the consumer — it uses this to skip Taffy entirely for a
 * paint-only patch. It is emitted here so the compiler's own `LAYOUT_FIELDS`
 * can be checked against it rather than trusted to agree.
 */
export const LAYOUT_AFFECTING: { [K in TableName]?: boolean[] } = {
  styles: [false, false, false, true, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
};

export const TABLE_NAMES = ["nodes", "styles", "variants", "variantSlots", "lists", "layout", "strings"] as const;
export type TableName = (typeof TABLE_NAMES)[number];

/** Field index per table, in descriptor order. */
export const F = {
  /** Tree structure and per-node indices. */
  nodes: {
    kind: 0, // NodeKind: box, text, button
    style: 1, // Index into the style table
    text: 2, // String slot, or -1
    parent: 3,
    firstChild: 4,
    nextSibling: 5,
    list: 6, // Index into the list table, or -1
    hidden: 7, // Non-zero excludes the subtree entirely
    flags: 8, // Bit 0 interactive, bit 1 measurable text
  },
  /** Resolved style values. Patches write field values in place. */
  styles: {
    bg: 0,
    fg: 1,
    borderColor: 2,
    borderWidth: 3,
    radius: 4,
    padTop: 5,
    padRight: 6,
    padBottom: 7,
    padLeft: 8,
    marginTop: 9,
    marginRight: 10,
    marginBottom: 11,
    marginLeft: 12,
    display: 13, // 0 flex, 1 grid, 2 block, 3 none
    flexDirection: 14,
    flexWrap: 15,
    justifyContent: 16,
    alignItems: 17,
    alignSelf: 18,
    justifyItems: 19, // Grid only
    justifySelf: 20, // Grid only
    flexGrow: 21,
    flexShrink: 22,
    flexBasis: 23,
    gapRow: 24,
    gapColumn: 25,
    gridColumns: 26, // repeat(N, minmax(0,1fr)) — Tailwind's grid-cols-N
    gridRows: 27,
    gridColumnStart: 28,
    gridColumnSpan: 29,
    gridRowStart: 30,
    gridRowSpan: 31,
    width: 32,
    height: 33,
    minWidth: 34,
    minHeight: 35,
    maxWidth: 36,
    maxHeight: 37,
    aspectRatio: 38,
    position: 39, // 0 relative, 1 absolute
    insetTop: 40,
    insetRight: 41,
    insetBottom: 42,
    insetLeft: 43,
    fontSize: 44,
    fontWeight: 45,
    lineClamp: 46, // 0 = unlimited; drives SkParagraph maxLines
    overflowX: 47, // 0 visible, 1 hidden, 2 ellipsis, 3 scroll
    overflowY: 48, // 0 visible, 1 hidden, 2 ellipsis, 3 scroll
  },
  /** Per-node predicate mask and where that node's style run begins. */
  variants: {
    node: 0, // Sorted ascending, for binary search
    mask: 1, // Predicate bits this node's styling reads
    runStart: 2, // First entry in variantSlots
  },
  /** Dense style-slot runs, indexed by compacted live predicate bits. */
  variantSlots: {
    style: 0,
  },
  /** List arenas: homogeneous item subtrees addressed by stride. */
  lists: {
    container: 0, // The node the rows are children of
    anchorPrev: 1, // Static sibling before the rows, or -1 for firstChild
    anchorNext: 2, // Static sibling after the rows, or -1 for end of chain
    arenaStart: 3,
    stride: 4,
    capacity: 5,
    active: 6,
  },
  /** Final bounds per node, written by the engine. */
  layout: {
    x: 0,
    y: 1,
    width: 2,
    height: 3,
  },
  /** Slot table into the UTF-8 arena. */
  strings: {
    offset: 0,
    length: 1,
  },
} as const;

/** Field counts, asserted against the engine's descriptor at startup. */
export const FIELD_COUNTS: Record<TableName, number> = {
  nodes: 9,
  styles: 49,
  variants: 3,
  variantSlots: 1,
  lists: 7,
  layout: 4,
  strings: 2,
};

/** Typed-array constructor per field, used to wrap the engine's memory. */
export const FIELD_VIEWS: Record<TableName, unknown[]> = {
  nodes: [Uint8Array, Uint16Array, Int32Array, Int32Array, Int32Array, Int32Array, Int16Array, Uint8Array, Uint8Array],
  styles: [Uint32Array, Uint32Array, Uint32Array, Float32Array, Float32Array, Float32Array, Float32Array, Float32Array, Float32Array, Float32Array, Float32Array, Float32Array, Float32Array, Uint8Array, Uint8Array, Uint8Array, Uint8Array, Uint8Array, Uint8Array, Uint8Array, Uint8Array, Float32Array, Float32Array, Float32Array, Float32Array, Float32Array, Uint16Array, Uint16Array, Int16Array, Int16Array, Int16Array, Int16Array, Float32Array, Float32Array, Float32Array, Float32Array, Float32Array, Float32Array, Float32Array, Uint8Array, Float32Array, Float32Array, Float32Array, Float32Array, Float32Array, Uint16Array, Uint16Array, Uint8Array, Uint8Array],
  variants: [Int32Array, Uint32Array, Int32Array],
  variantSlots: [Uint16Array],
  lists: [Int32Array, Int32Array, Int32Array, Int32Array, Int32Array, Int32Array, Int32Array],
  layout: [Float32Array, Float32Array, Float32Array, Float32Array],
  strings: [Uint32Array, Uint32Array],
};

/** Shape of the wrapped tables once the descriptor has been read. */
export type SharedTables = {
  nodes: {
    kind: Uint8Array;
    style: Uint16Array;
    text: Int32Array;
    parent: Int32Array;
    firstChild: Int32Array;
    nextSibling: Int32Array;
    list: Int16Array;
    hidden: Uint8Array;
    flags: Uint8Array;
  };
  styles: {
    bg: Uint32Array;
    fg: Uint32Array;
    borderColor: Uint32Array;
    borderWidth: Float32Array;
    radius: Float32Array;
    padTop: Float32Array;
    padRight: Float32Array;
    padBottom: Float32Array;
    padLeft: Float32Array;
    marginTop: Float32Array;
    marginRight: Float32Array;
    marginBottom: Float32Array;
    marginLeft: Float32Array;
    display: Uint8Array;
    flexDirection: Uint8Array;
    flexWrap: Uint8Array;
    justifyContent: Uint8Array;
    alignItems: Uint8Array;
    alignSelf: Uint8Array;
    justifyItems: Uint8Array;
    justifySelf: Uint8Array;
    flexGrow: Float32Array;
    flexShrink: Float32Array;
    flexBasis: Float32Array;
    gapRow: Float32Array;
    gapColumn: Float32Array;
    gridColumns: Uint16Array;
    gridRows: Uint16Array;
    gridColumnStart: Int16Array;
    gridColumnSpan: Int16Array;
    gridRowStart: Int16Array;
    gridRowSpan: Int16Array;
    width: Float32Array;
    height: Float32Array;
    minWidth: Float32Array;
    minHeight: Float32Array;
    maxWidth: Float32Array;
    maxHeight: Float32Array;
    aspectRatio: Float32Array;
    position: Uint8Array;
    insetTop: Float32Array;
    insetRight: Float32Array;
    insetBottom: Float32Array;
    insetLeft: Float32Array;
    fontSize: Float32Array;
    fontWeight: Uint16Array;
    lineClamp: Uint16Array;
    overflowX: Uint8Array;
    overflowY: Uint8Array;
  };
  variants: {
    node: Int32Array;
    mask: Uint32Array;
    runStart: Int32Array;
  };
  variantSlots: {
    style: Uint16Array;
  };
  lists: {
    container: Int32Array;
    anchorPrev: Int32Array;
    anchorNext: Int32Array;
    arenaStart: Int32Array;
    stride: Int32Array;
    capacity: Int32Array;
    active: Int32Array;
  };
  layout: {
    x: Float32Array;
    y: Float32Array;
    width: Float32Array;
    height: Float32Array;
  };
  strings: {
    offset: Uint32Array;
    length: Uint32Array;
  };
};

export const NodeFlags = {
  INTERACTIVE: 1 << 0,
  MEASURABLE: 1 << 1,
} as const;

/** What a node is. `nodes.kind`. */
export const NodeKind = {
  BOX: 0,
  TEXT: 1,
  BUTTON: 2,
} as const;
export type NodeKind = (typeof NodeKind)[keyof typeof NodeKind];

/** `styles.display`. `NONE` excludes the subtree from layout. */
export const Display = {
  FLEX: 0,
  GRID: 1,
  BLOCK: 2,
  NONE: 3,
} as const;
export type Display = (typeof Display)[keyof typeof Display];

/** `styles.flexDirection`. */
export const FlexDirection = {
  ROW: 0,
  COLUMN: 1,
  ROW_REVERSE: 2,
  COLUMN_REVERSE: 3,
} as const;
export type FlexDirection = (typeof FlexDirection)[keyof typeof FlexDirection];

/** `styles.flexWrap`. */
export const FlexWrap = {
  NO_WRAP: 0,
  WRAP: 1,
  WRAP_REVERSE: 2,
} as const;
export type FlexWrap = (typeof FlexWrap)[keyof typeof FlexWrap];

/** `styles.justifyContent`. CSS `align-content` values, per Taffy. */
export const Justify = {
  FLEX_START: 0,
  CENTER: 1,
  FLEX_END: 2,
  SPACE_BETWEEN: 3,
  SPACE_AROUND: 4,
  SPACE_EVENLY: 5,
  UNSET: 255,
} as const;
export type Justify = (typeof Justify)[keyof typeof Justify];

/** `styles.alignItems` / `alignSelf` / `justifyItems` / `justifySelf`. */
export const Align = {
  FLEX_START: 0,
  CENTER: 1,
  FLEX_END: 2,
  STRETCH: 3,
  BASELINE: 4,
  UNSET: 255,
} as const;
export type Align = (typeof Align)[keyof typeof Align];

/** `styles.position`. */
export const Position = {
  RELATIVE: 0,
  ABSOLUTE: 1,
} as const;
export type Position = (typeof Position)[keyof typeof Position];

/** `styles.overflow`. */
export const Overflow = {
  VISIBLE: 0,
  HIDDEN: 1,
  ELLIPSIS: 2,
  SCROLL: 3,
} as const;
export type Overflow = (typeof Overflow)[keyof typeof Overflow];

/** Bit positions in a variant mask. Bits 0-2 are per-node; higher bits are global, so the engine can flip them without knowing which nodes care. */
export const Predicate = {
  HOVER: 1,
  ACTIVE: 2,
  FOCUS: 4,
  FIRST_GLOBAL: 256,
} as const;
export type Predicate = (typeof Predicate)[keyof typeof Predicate];

/** Engine → Bun. Drained after `tick()`; `0` means the queue is empty. */
export const EventKind = {
  NONE: 0,
  QUIT: 1,
  RESIZE: 2,
  MOUSE_MOVE: 3,
  MOUSE_DOWN: 4,
  MOUSE_UP: 5,
  CLICK: 6,
  KEY_DOWN: 7,
  TEXT_INPUT: 8,
  FOCUS: 9,
} as const;
export type EventKind = (typeof EventKind)[keyof typeof EventKind];

/** Return code of every FFI entry point. Negative is failure, and the detail is in `dziri_last_error`. */
export const Status = {
  OK: 0,
  PANIC: -1,
  INVALID_HANDLE: -2,
  INVALID_ARGUMENT: -3,
  PROTOCOL_MISMATCH: -4,
  CAPACITY: -5,
  SDL: -6,
  SKIA: -7,
  LAYOUT: -8,
  POISONED: -9,
} as const;
export type Status = (typeof Status)[keyof typeof Status];
