// GENERATED by src/compile.ts from app/app.tsx + app/app.css
// Do not edit. No CSS, no selectors, no property names — just indices.
//
// 125 nodes, 49 style slots, 48 strings,
// 29 conditional nodes (16 variant slots), 31 interactive,
// 4 text bindings, 4 handlers.

import { addTodo, clearDraft, deleteTodo, draft, isCompact, isLight, remaining, toggleDensity, toggleDone, toggleTheme, total, view } from "./../../../workspace/skia-proto/app/state.ts";

// Types, so this artifact is checked rather than asserted at the far end.
import type { HandlerBinding, ListTable, MediaTable, NodeTable, StyleTable, TextBinding, VariantTable } from "../../../workspace/skia-proto/src/ir.ts";
import type { EditableRef } from "../../../workspace/skia-proto/src/runtime/bindings.ts";
import type { ListBindingRef } from "../../../workspace/skia-proto/src/runtime/list-runtime.ts";
import type { StylePatchRef } from "../../../workspace/skia-proto/src/runtime/patches.ts";

/** Mutable past the static entries: text bindings overwrite their own slots. */
export const strings: string[] = ["dziri","Taffy lays out · Skia paints · SDL3 owns the window","Theme","Density","grid + flex","both, from one style table","","remaining","","total","Dynamic list · keyed · per-row handlers","","Add","Clear","","","x","","","","","","","","","","","","","","","","","Flex · wrap, align-self, aspect-ratio","flex","grid","wrap","grow","align-self","aspect-ratio","absolute","gap","left: 10px · bottom: 10px","string","object","inline beats every selector · 8 is 8px, 600 is not"," of  left · compiled at build time, no CSS in the runtime","no DOM · no browser engine"];

/** Mutable: style patches write field values in place. Node pointers never change. */
export const styles = {
  count: 49,
  bg: new Uint32Array([4279769115,0,0,0,0,0,0,4280756014,4281479738,4280032290,4280032290,0,4280034614,0,0,4280492841,0,4280229668,0,4280492841,4280492841,0,4282090230,4284524026,0,4279900703,4280756014,4281479738,0,0,0,4280756014,4286520605,0,4280756014,4281479738,0,0,4282090230,4287323382,4293675161,4280468830,4280492841,4282090230,0,0,4290321436,4279599165,0]),
  fg: new Uint32Array([4293190887,4293190887,4293190887,4293190887,4294638330,4285624698,4293190887,4292138200,4294243573,4292138200,4294243573,4293190887,4293190887,4294638330,4285624698,4293190887,4293190887,4293190887,4288782762,4294243573,4294243573,4294243573,4294967295,4294967295,4293190887,4293190887,4288782762,4294243573,4288782762,4293190887,4293190887,4288782762,4294888138,4293190887,4288782762,4294243573,4288782762,4293190887,4293190887,4293190887,4293190887,4293190887,4293190887,4294967295,4294967295,4285624698,4294894306,4292672743,4293190887]),
  borderColor: new Uint32Array([0,0,0,0,0,0,0,4282335046,4282335046,4282335046,4282335046,0,4281287784,0,0,4281282359,0,4281282359,0,4282335046,4282090230,0,4282090230,4282090230,0,0,4283585115,4283585115,0,0,0,4282335046,4288224027,0,4282335046,4283585115,0,0,0,0,0,0,4281282359,0,0,0,4282335046,4282335046,0]),
  borderWidth: new Float32Array([0,0,0,0,0,0,0,1,1,1,1,0,1,0,0,1,0,1,0,1,1,0,1,1,0,0,1,1,0,0,0,1,1,0,1,1,0,0,0,0,0,0,1,0,0,0,1,1,0]),
  radius: new Float32Array([0,0,0,0,0,0,0,6,6,6,6,0,8,0,0,8,0,10,0,6,6,0,6,6,0,6,4,4,0,0,0,4,4,0,999,999,0,0,6,6,6,6,8,999,0,0,6,6,0]),
  padT: new Float32Array([18,0,0,0,0,0,0,8,8,8,8,0,10,0,0,10,0,14,0,9,9,0,8,8,0,7,2,2,0,0,0,2,2,0,4,4,0,0,0,0,0,0,0,3,0,0,8,8,0]),
  padR: new Float32Array([18,0,0,0,0,0,0,14,14,14,14,0,12,0,0,12,0,14,0,12,12,0,14,14,0,10,6,6,0,0,0,8,8,0,10,10,0,0,0,0,0,0,0,9,0,0,14,14,0]),
  padB: new Float32Array([18,0,0,0,0,0,0,8,8,8,8,0,10,0,0,10,0,14,0,9,9,0,8,8,0,7,2,2,0,0,0,2,2,0,4,4,0,0,0,0,0,0,0,3,0,0,8,8,0]),
  padL: new Float32Array([18,0,0,0,0,0,0,14,14,14,14,0,12,0,0,12,0,14,0,12,12,0,14,14,0,10,6,6,0,0,0,8,8,0,10,10,0,0,0,0,0,0,0,9,0,0,14,24,0]),
  marT: new Float32Array(49),
  marR: new Float32Array(49),
  marB: new Float32Array(49),
  marL: new Float32Array(49),
  display: new Uint8Array([0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]),
  direction: new Uint8Array([1,1,0,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,0,1,1,1,0,1,1,1,1,1,1,1,1,1,1,0]),
  wrap: new Uint8Array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]),
  justify: new Uint8Array([0,0,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3]),
  align: new Uint8Array([255,255,1,255,255,255,1,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,1,255,255,255,255,255,255,255,1,255,255,255,0,255,255,255,255,255,255,255,255,255,255,1]),
  alignSelf: new Uint8Array([255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,1,2,3,255,255,255,255,255,255,255]),
  grow: new Float32Array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]),
  shrink: new Float32Array(49).fill(1),
  basis: new Float32Array([NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN]),
  gapRow: new Float32Array([0,14,0,0,0,0,8,0,0,0,0,10,2,0,0,2,14,10,0,0,0,0,0,0,4,10,0,0,0,0,0,0,0,6,0,0,0,8,0,0,0,0,0,0,0,0,0,0,8]),
  gapCol: new Float32Array([0,14,0,0,0,0,8,0,0,0,0,10,2,0,0,2,14,10,0,0,0,0,0,0,4,10,0,0,0,0,0,0,0,6,0,0,0,8,0,0,0,0,0,0,0,0,0,0,8]),
  gridCols: new Uint16Array([0,0,0,0,0,0,0,0,0,0,0,4,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]),
  gridRows: new Uint16Array(49),
  gridColStart: new Int16Array(49),
  gridColSpan: new Int16Array([0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]),
  gridRowStart: new Int16Array(49),
  gridRowSpan: new Int16Array(49),
  justifyItems: new Uint8Array(49).fill(255),
  justifySelf: new Uint8Array(49).fill(255),
  width: new Float32Array([NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34,34,34,34,NaN,NaN,NaN,NaN,NaN,NaN,NaN]),
  height: new Float32Array([NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,74,NaN,NaN,NaN,NaN,96,NaN,NaN,NaN,NaN,NaN,NaN]),
  minW: new Float32Array(49).fill(NaN),
  maxW: new Float32Array(49).fill(Infinity),
  minH: new Float32Array(49).fill(NaN),
  maxH: new Float32Array(49).fill(Infinity),
  aspectRatio: new Float32Array([NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN]),
  position: new Uint8Array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0]),
  insetT: new Float32Array([NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,NaN,NaN,NaN,NaN,NaN]),
  insetR: new Float32Array([NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,NaN,NaN,NaN,NaN,NaN]),
  insetB: new Float32Array([NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN]),
  insetL: new Float32Array([NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN]),
  fontSize: new Float32Array([14,14,14,14,22,12,14,13,13,13,13,14,14,20,11,14,14,14,13,14,14,14,13,13,14,14,13,13,13,14,14,13,13,14,12,12,12,14,14,14,14,14,14,11,11,12,13,13,14]),
  fontWeight: new Uint16Array([400,400,400,400,600,400,400,400,400,400,400,400,400,600,400,400,400,400,600,400,400,400,400,400,400,400,400,400,400,400,400,400,400,400,400,400,400,400,400,400,400,400,400,600,600,400,400,600,400]),
  overflowX: new Uint8Array([3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]),
  overflowY: new Uint8Array([3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]),
  scrollbarWidth: new Uint8Array(49),
  scrollbarThumb: new Uint32Array(49).fill(4283585115),
  scrollbarTrack: new Uint32Array(49),
} satisfies StyleTable;

export const nodes = {
  count: 125,
  kind: new Uint8Array([0,0,0,0,0,1,0,1,0,2,2,0,0,0,1,0,1,0,0,1,0,1,0,0,1,0,1,0,0,0,1,0,0,1,2,2,0,0,2,1,0,1,2,0,2,1,0,1,2,0,2,1,0,1,2,0,2,1,0,1,2,0,2,1,0,1,2,0,2,1,0,1,2,0,2,1,0,1,2,0,2,1,0,1,2,0,0,1,0,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,0,0,0,0,0,0,1,0,1,0,2,2,0,1,0,0,1,0,1]),
  style: new Uint16Array([0,1,2,3,4,4,5,5,6,7,7,11,12,13,13,14,14,15,13,13,14,14,15,13,13,14,14,16,17,18,18,6,19,21,22,7,24,25,26,28,29,30,31,25,26,28,29,30,31,25,26,28,29,30,31,25,26,28,29,30,31,25,26,28,29,30,31,25,26,28,29,30,31,25,26,28,29,30,31,25,26,28,29,30,31,17,18,18,33,34,36,34,36,34,36,34,36,34,36,34,36,34,36,34,36,37,38,39,40,41,42,43,44,45,5,6,46,47,5,5,48,5,5,5,5]),
  text: new Int32Array([-1,-1,-1,-1,-1,0,-1,1,-1,2,3,-1,-1,-1,4,-1,5,-1,-1,6,-1,7,-1,-1,8,-1,9,-1,-1,-1,10,-1,-1,11,12,13,-1,-1,-1,17,-1,18,16,-1,-1,19,-1,20,16,-1,-1,21,-1,22,16,-1,-1,23,-1,24,16,-1,-1,25,-1,26,16,-1,-1,27,-1,28,16,-1,-1,29,-1,30,16,-1,-1,31,-1,32,16,-1,-1,33,-1,-1,34,-1,35,-1,36,-1,37,-1,38,-1,39,-1,40,-1,41,-1,-1,-1,-1,-1,-1,-1,40,-1,42,-1,43,44,-1,45,-1,-1,46,-1,47]),
  parent: new Int32Array([-1,0,1,2,3,4,3,6,2,8,8,1,11,12,13,12,15,11,17,18,17,20,11,22,23,22,25,1,27,28,29,28,31,32,31,31,28,36,37,38,37,40,37,36,43,44,43,46,43,36,49,50,49,52,49,36,55,56,55,58,55,36,61,62,61,64,61,36,67,68,67,70,67,36,73,74,73,76,73,36,79,80,79,82,79,27,85,86,85,88,89,88,91,88,93,88,95,88,97,88,99,88,101,88,103,85,105,105,105,105,85,110,111,110,113,1,115,115,115,118,1,120,121,120,123]),
  firstChild: new Int32Array([1,2,3,4,5,-1,7,-1,9,-1,-1,12,13,14,-1,16,-1,18,19,-1,21,-1,23,24,-1,26,-1,28,29,30,-1,32,33,-1,-1,-1,-1,38,39,-1,41,-1,-1,44,45,-1,47,-1,-1,50,51,-1,53,-1,-1,56,57,-1,59,-1,-1,62,63,-1,65,-1,-1,68,69,-1,71,-1,-1,74,75,-1,77,-1,-1,80,81,-1,83,-1,-1,86,87,-1,89,90,-1,92,-1,94,-1,96,-1,98,-1,100,-1,102,-1,104,-1,106,-1,-1,-1,-1,111,112,-1,114,-1,116,-1,-1,119,-1,121,122,-1,124,-1]),
  nextSibling: new Int32Array([-1,-1,11,8,6,-1,-1,-1,-1,10,-1,27,17,15,-1,-1,-1,22,20,-1,-1,-1,-1,25,-1,-1,-1,115,85,31,-1,36,34,-1,35,-1,-1,-1,40,-1,42,-1,-1,-1,46,-1,48,-1,-1,-1,52,-1,54,-1,-1,-1,58,-1,60,-1,-1,-1,64,-1,66,-1,-1,-1,70,-1,72,-1,-1,-1,76,-1,78,-1,-1,-1,82,-1,84,-1,-1,-1,88,-1,105,91,-1,93,-1,95,-1,97,-1,99,-1,101,-1,103,-1,-1,-1,110,107,108,109,-1,-1,113,-1,-1,-1,120,117,118,-1,-1,-1,123,-1,-1,-1]),
  list: new Int16Array(125).fill(-1),
  hidden: new Uint8Array(125),
} satisfies NodeTable;

/**
 * Conditional styling, sparse and sorted by node.
 *
 * mask is the predicate bits a node reads; slots[runStart + i] is its style for
 * the combination whose compacted bits equal i. Runs are shared between nodes
 * that resolve identically.
 */
export const variants = {
  count: 29,
  node: new Int32Array([9,10,32,34,35,38,42,44,48,50,54,56,60,62,66,68,72,74,78,80,84,89,91,93,95,97,99,101,103]),
  mask: new Uint32Array([3,3,4,3,3,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]),
  runStart: new Int32Array([0,0,4,6,0,10,12,10,12,10,12,10,12,10,12,10,12,10,12,10,12,14,14,14,14,14,14,14,14]),
  slots: new Uint16Array([7,8,9,10,19,20,22,23,22,23,26,27,31,32,34,35]),
} satisfies VariantTable;

/** Nodes that can receive input, sorted. Emitted, never inferred. */
export const interactive = new Int32Array([9,10,32,34,35,38,42,44,48,50,54,56,60,62,66,68,72,74,78,80,84,89,91,93,95,97,99,101,103,116,117]);

/** Dynamic text runs. Literal chunks interleaved with the signals they read. */
export const textBindings = [
  { node: 19, slot: 6, parts: [{ signal: remaining }] },
  { node: 24, slot: 8, parts: [{ signal: total }] },
  { node: 33, slot: 11, parts: [{ signal: draft }] },
  { node: 122, slot: 46, parts: [{ signal: remaining }, { literal: " of " }, { signal: total }, { literal: " left · compiled at build time, no CSS in the runtime" }] },
] satisfies TextBinding[];

/** Click handlers, as direct references to the app's exported functions. */
export const handlers = [
  { node: 9, fn: toggleTheme },
  { node: 10, fn: toggleDensity },
  { node: 34, fn: addTodo },
  { node: 35, fn: clearDraft },
] satisfies HandlerBinding[];

/** Nodes that route keystrokes into a string signal while focused. */
export const editables = [
  { node: 32, signal: draft },
] satisfies EditableRef[];

/**
 * Conditional classes, compiled to style-table writes.
 *
 * Each entry writes field values for the slots the class actually changes — no
 * class names, no cascade, and node style pointers untouched. affectsLayout says
 * whether applying it requires a relayout or only a repaint.
 */
export const stylePatches = [
  {
    signal: isLight,
    affectsLayout: false,
    entries: [
      { field: "bg", slots: new Uint16Array([0,7,8,9,10,12,15,17,19,20,22,25,26,27,31,32,34,35,42]), on: new Float64Array([4294638330,4294243573,4294243573,4294243573,4294243573,4293916415,4294967295,4294967295,4294967295,4294967295,4294243573,4294243573,4294243573,4294243573,4294243573,4294243573,4294243573,4294243573,4294243573]), off: new Float64Array([4279769115,4280756014,4281479738,4280032290,4280032290,4280034614,4280492841,4280229668,4280492841,4280492841,4282090230,4279900703,4280756014,4281479738,4280756014,4286520605,4280756014,4281479738,4280492841]) },
      { field: "fg", slots: new Uint16Array([0,1,2,3,4,6,7,8,9,10,11,12,13,15,16,17,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,48]), on: new Float64Array([4279769115,4279769115,4279769115,4279769115,4278782219,4279769115,4282335046,4282335046,4282335046,4282335046,4279769115,4279769115,4278782219,4279769115,4279769115,4279769115,4279769115,4279769115,4279769115,4282335046,4282335046,4279769115,4279769115,4283585115,4283585115,4283585115,4280756010,4280756010,4283585115,4283585115,4279769115,4283585115,4283585115,4283585115,4279769115,4279769115,4279769115,4279769115,4279769115,4279769115,4279769115]), off: new Float64Array([4293190887,4293190887,4293190887,4293190887,4294638330,4293190887,4292138200,4294243573,4292138200,4294243573,4293190887,4293190887,4294638330,4293190887,4293190887,4293190887,4294243573,4294243573,4294243573,4294967295,4294967295,4293190887,4293190887,4288782762,4294243573,4288782762,4293190887,4293190887,4288782762,4294888138,4293190887,4288782762,4294243573,4288782762,4293190887,4293190887,4293190887,4293190887,4293190887,4293190887,4293190887]) },
      { field: "borderColor", slots: new Uint16Array([7,8,9,10,12,15,17,19,20,22,23,26,27,31,32,34,35,42,46,47]), on: new Float64Array([4292138200,4292138200,4292138200,4292138200,4290763774,4293190887,4293190887,4292138200,4292138200,4292138200,4292138200,4292138200,4292138200,4292138200,4292138200,4293190887,4293190887,4293190887,4292138200,4292138200]), off: new Float64Array([4282335046,4282335046,4282335046,4282335046,4281287784,4281282359,4281282359,4282335046,4282090230,4282090230,4282090230,4283585115,4283585115,4282335046,4288224027,4282335046,4283585115,4281282359,4282335046,4282335046]) },
    ],
  },
  {
    signal: isCompact,
    affectsLayout: true,
    entries: [
      { field: "gapRow", slots: new Uint16Array([1,17,24]), on: new Float64Array([8,6,1]), off: new Float64Array([14,10,4]) },
      { field: "gapCol", slots: new Uint16Array([1,17,24]), on: new Float64Array([8,6,1]), off: new Float64Array([14,10,4]) },
      { field: "padT", slots: new Uint16Array([12,15,17,25]), on: new Float64Array([6,6,8,2]), off: new Float64Array([10,10,14,7]) },
      { field: "padR", slots: new Uint16Array([12,15,17,25]), on: new Float64Array([10,10,8,8]), off: new Float64Array([12,12,14,10]) },
      { field: "padB", slots: new Uint16Array([12,15,17,25]), on: new Float64Array([6,6,8,2]), off: new Float64Array([10,10,14,7]) },
      { field: "padL", slots: new Uint16Array([12,15,17,25]), on: new Float64Array([10,10,8,8]), off: new Float64Array([12,12,14,10]) },
    ],
  },
] satisfies StylePatchRef[];

/**
 * Dynamic lists. Each owns a contiguous arena of identical item subtrees; the
 * runtime rewrites the child chain and the bound slots, never the nodes.
 */
export const lists = {
  count: 1,
  container: new Int32Array([36]),
  anchorPrev: new Int32Array([-1]),
  anchorNext: new Int32Array([-1]),
  arenaStart: new Int32Array([37]),
  stride: new Int32Array([6]),
  capacity: new Int32Array([8]),
  active: new Int32Array(1),
  dataOffset: new Int32Array(1),
} satisfies ListTable;

/** Per-list: the array signal, key path, and where each item's bound slots live. */
export const listBindings = [
  {
    list: 0,
    signal: view,
    keyPath: ["id"],
    slotStart: 17,
    slotsPerItem: 2,
    bindings: [
      { offset: 2, slotOffset: 0, parts: [{ path: ["mark"] }] },
      { offset: 4, slotOffset: 1, parts: [{ path: ["title"] }] },
    ],
    itemHandlers: [
      { offset: 1, fn: toggleDone },
      { offset: 5, fn: deleteTodo },
    ],
  },
] satisfies ListBindingRef[];

/**
 * Media conditions, one row per distinct threshold, in predicate-bit order.
 *
 * The engine re-evaluates these against the surface between a resize and the
 * relayout. Bun uploads them once and never looks at them again — routing a
 * resize back through Bun would lag a frame and stall whenever Bun is busy.
 */
export const media = {
  count: 0,
  bit: new Uint32Array([]),
  kind: new Uint8Array([]),
  value: new Float32Array([]),
} satisfies MediaTable;

export const root: number = 0;
