// GENERATED by src/compile.ts from characterize/cases/cascade.html + characterize/cases/cascade.css
// Do not edit. No CSS, no selectors, no property names — just indices.
//
// 9 nodes, 6 style slots, 3 strings,
// 0 conditional nodes (0 variant slots), 0 interactive,
// 0 text bindings, 0 handlers.

// Types, so this artifact is checked rather than asserted at the far end.
import type { HandlerBinding, ListTable, MediaTable, NodeTable, StyleTable, TextBinding, VariantTable } from "dziri/ir.ts";
import type { EditableRef } from "dziri/runtime/bindings.ts";
import type { ListBindingRef } from "dziri/runtime/list-runtime.ts";
import type { StylePatchRef } from "dziri/runtime/patches.ts";

/** Mutable past the static entries: text bindings overwrite their own slots. */
export const strings: string[] = ["tie","inherited","shorthand"];

/** Mutable: style patches write field values in place. Node pointers never change. */
export const styles = {
  count: 6,
  bg: new Uint32Array([4279242772,4280032290,0,0,4280032290,0]),
  fg: new Uint32Array([4293190887,4294243573,4288782762,4294243573,4293190887,4288782762]),
  borderColor: new Uint32Array(6),
  borderWidth: new Float32Array(6),
  radTL: new Float32Array([0,6,0,0,6,0]),
  radTR: new Float32Array([0,6,0,0,6,0]),
  radBR: new Float32Array([0,6,0,0,6,0]),
  radBL: new Float32Array([0,6,0,0,6,0]),
  padT: new Float32Array([12,8,0,0,8,4]),
  padR: new Float32Array([12,12,0,0,12,16]),
  padB: new Float32Array([12,8,0,0,8,4]),
  padL: new Float32Array([12,12,0,0,12,16]),
  marT: new Float32Array(6),
  marR: new Float32Array(6),
  marB: new Float32Array(6),
  marL: new Float32Array(6),
  display: new Uint8Array(6),
  direction: new Uint8Array([1,0,1,1,0,1]),
  wrap: new Uint8Array(6),
  justify: new Uint8Array(6),
  align: new Uint8Array(6).fill(255),
  alignSelf: new Uint8Array(6).fill(255),
  grow: new Float32Array(6),
  shrink: new Float32Array(6).fill(1),
  basis: new Float32Array(6).fill(NaN),
  gapRow: new Float32Array([8,6,0,0,6,0]),
  gapCol: new Float32Array([8,6,0,0,6,0]),
  gridCols: new Uint16Array(6),
  gridRows: new Uint16Array(6),
  gridColStart: new Int16Array(6),
  gridColSpan: new Int16Array(6),
  gridRowStart: new Int16Array(6),
  gridRowSpan: new Int16Array(6),
  justifyItems: new Uint8Array(6).fill(255),
  justifySelf: new Uint8Array(6).fill(255),
  width: new Float32Array(6).fill(NaN),
  height: new Float32Array(6).fill(NaN),
  minW: new Float32Array(6).fill(NaN),
  maxW: new Float32Array(6).fill(Infinity),
  minH: new Float32Array(6).fill(NaN),
  maxH: new Float32Array(6).fill(Infinity),
  aspectRatio: new Float32Array(6).fill(NaN),
  position: new Uint8Array(6),
  insetT: new Float32Array(6).fill(NaN),
  insetR: new Float32Array(6).fill(NaN),
  insetB: new Float32Array(6).fill(NaN),
  insetL: new Float32Array(6).fill(NaN),
  fontSize: new Float32Array(6).fill(14),
  fontWeight: new Uint16Array([400,400,600,400,400,600]),
  overflowX: new Uint8Array(6),
  overflowY: new Uint8Array(6),
  scrollbarWidth: new Uint8Array(6),
  scrollbarThumb: new Uint32Array(6),
  scrollbarTrack: new Uint32Array(6),
} satisfies StyleTable;

export const nodes = {
  count: 9,
  kind: new Uint8Array([0,0,0,1,0,1,0,0,1]),
  style: new Uint16Array([0,1,2,2,3,3,4,5,2]),
  text: new Int32Array([-1,-1,-1,0,-1,1,-1,-1,2]),
  parent: new Int32Array([-1,0,1,2,1,4,0,6,7]),
  firstChild: new Int32Array([1,2,3,-1,5,-1,7,8,-1]),
  nextSibling: new Int32Array([-1,6,4,-1,-1,-1,-1,-1,-1]),
  list: new Int16Array(9).fill(-1),
  hidden: new Uint8Array(9),
} satisfies NodeTable;

/**
 * Conditional styling, sparse and sorted by node.
 *
 * mask is the predicate bits a node reads; slots[runStart + i] is its style for
 * the combination whose compacted bits equal i. Runs are shared between nodes
 * that resolve identically.
 */
export const variants = {
  count: 0,
  node: new Int32Array([]),
  mask: new Uint32Array([]),
  runStart: new Int32Array([]),
  slots: new Uint16Array([]),
} satisfies VariantTable;

/** Nodes that can receive input, sorted. Emitted, never inferred. */
export const interactive = new Int32Array([]);

/** Dynamic text runs. Literal chunks interleaved with the signals they read. */
export const textBindings = [

] satisfies TextBinding[];

/** Click handlers, as direct references to the app's exported functions. */
export const handlers = [

] satisfies HandlerBinding[];

/** Nodes that route keystrokes into a string signal while focused. */
export const editables = [

] satisfies EditableRef[];

/**
 * Conditional classes, compiled to style-table writes.
 *
 * Each entry writes field values for the slots the class actually changes — no
 * class names, no cascade, and node style pointers untouched. affectsLayout says
 * whether applying it requires a relayout or only a repaint.
 */
export const stylePatches = [

] satisfies StylePatchRef[];

/**
 * Dynamic lists. Each owns a contiguous arena of identical item subtrees; the
 * runtime rewrites the child chain and the bound slots, never the nodes.
 */
export const lists = {
  count: 0,
  container: new Int32Array([]),
  anchorPrev: new Int32Array([]),
  anchorNext: new Int32Array([]),
  arenaStart: new Int32Array([]),
  stride: new Int32Array([]),
  capacity: new Int32Array([]),
  active: new Int32Array(0),
  dataOffset: new Int32Array(0),
} satisfies ListTable;

/** Per-list: the array signal, key path, and where each item's bound slots live. */
export const listBindings = [

] satisfies ListBindingRef[];

/**
 * Media conditions, one row per distinct threshold, in predicate-bit order.
 *
 * The engine re-evaluates these against the surface between a resize and the
 * relayout. Bun uploads them once and never looks at them again — routing a
 * resize back through Bun would lag a frame and stall whenever Bun is busy.
 */
export const media = {
  count: 0,
  bit: new Uint32Array([]),
  kind: new Uint8Array([]),
  value: new Float32Array([]),
} satisfies MediaTable;

export const root: number = 0;
