// GENERATED by src/compile.ts from characterize/cases/cascade.html + characterize/cases/cascade.css
// Do not edit. No CSS, no selectors, no property names — just indices.
//
// 9 nodes, 6 style slots, 3 strings,
// 0 conditional nodes (0 variant slots), 0 interactive,
// 0 text bindings, 0 handlers.

// Types, so this artifact is checked rather than asserted at the far end.
import type { ControlTable, DataBinding, DisabledBinding, ErrorBinding, FormBinding, HandlerBinding, ImageTable, KeyframeTable, ListTable, MediaTable, NodeTable, NumericTable, ParamBinding, StyleTable, TextBinding, TweenTable, VariantTable } from "dziry/ir.ts";
import type { EditableRef, ImageBinding } from "dziry/runtime/bindings.ts";
import type { ListBindingRef } from "dziry/runtime/list-runtime.ts";
import type { StylePatchRef } from "dziry/runtime/patches.ts";

/** Mutable past the static entries: text bindings overwrite their own slots. */
export const strings: string[] = ["tie","inherited","shorthand"];

/** Mutable: style patches write field values in place. Node pointers never change. */
export const styles = {
  count: 6,
  bg: new Uint32Array([4279242772,4280032290,0,0,4280032290,0]),
  fg: new Uint32Array([4293190887,4294243573,4288782762,4294243573,4293190887,4288782762]),
  borderTopColor: new Uint32Array(6),
  borderRightColor: new Uint32Array(6),
  borderBottomColor: new Uint32Array(6),
  borderLeftColor: new Uint32Array(6),
  borderTopWidth: new Float32Array(6),
  borderRightWidth: new Float32Array(6),
  borderBottomWidth: new Float32Array(6),
  borderLeftWidth: new Float32Array(6),
  radTL: new Float32Array([0,6,0,0,6,0]),
  radTR: new Float32Array([0,6,0,0,6,0]),
  radBR: new Float32Array([0,6,0,0,6,0]),
  radBL: new Float32Array([0,6,0,0,6,0]),
  ringOuterWidth: new Float32Array(6),
  ringOuterColor: new Uint32Array(6),
  ringInnerWidth: new Float32Array(6),
  ringInnerColor: new Uint32Array(6),
  ringInsetWidth: new Float32Array(6),
  ringInsetColor: new Uint32Array(6),
  selectionBg: new Uint32Array(6).fill(4281569535),
  selectionFg: new Uint32Array(6).fill(4294967295),
  outlineColor: new Uint32Array(6),
  outlineWidth: new Float32Array(6),
  outlineOffset: new Float32Array(6),
  decorationLine: new Uint8Array(6),
  decorationColor: new Uint32Array(6),
  decorationStyle: new Uint8Array(6),
  decorationThickness: new Float32Array(6),
  underlineOffset: new Float32Array(6).fill(NaN),
  padT: new Float32Array([12,8,0,0,8,4]),
  padR: new Float32Array([12,12,0,0,12,16]),
  padB: new Float32Array([12,8,0,0,8,4]),
  padL: new Float32Array([12,12,0,0,12,16]),
  marT: new Float32Array(6),
  marR: new Float32Array(6),
  marB: new Float32Array(6),
  marL: new Float32Array(6),
  display: new Uint8Array(6),
  direction: new Uint8Array([1,0,1,1,0,1]),
  wrap: new Uint8Array(6),
  justify: new Uint8Array(6),
  alignContent: new Uint8Array(6).fill(255),
  align: new Uint8Array(6).fill(255),
  alignSelf: new Uint8Array(6).fill(255),
  justifyItems: new Uint8Array(6).fill(255),
  justifySelf: new Uint8Array(6).fill(255),
  grow: new Float32Array(6),
  shrink: new Float32Array(6).fill(1),
  basis: new Float32Array(6).fill(NaN),
  basisPct: new Float32Array(6),
  order: new Int32Array(6),
  gapRow: new Float32Array([8,6,0,0,6,0]),
  gapCol: new Float32Array([8,6,0,0,6,0]),
  gridCols: new Uint16Array(6),
  gridRows: new Uint16Array(6),
  gridColStart: new Int16Array(6),
  gridColSpan: new Int16Array(6),
  gridRowStart: new Int16Array(6),
  gridRowSpan: new Int16Array(6),
  width: new Float32Array(6).fill(NaN),
  widthPct: new Float32Array(6),
  widthVp: new Float32Array(6),
  height: new Float32Array(6).fill(NaN),
  heightPct: new Float32Array(6),
  heightVp: new Float32Array(6),
  minW: new Float32Array(6).fill(NaN),
  minWPct: new Float32Array(6),
  minWVp: new Float32Array(6),
  minH: new Float32Array(6).fill(NaN),
  minHPct: new Float32Array(6),
  minHVp: new Float32Array(6),
  maxW: new Float32Array(6).fill(Infinity),
  maxWPct: new Float32Array(6),
  maxWVp: new Float32Array(6),
  maxH: new Float32Array(6).fill(Infinity),
  maxHPct: new Float32Array(6),
  maxHVp: new Float32Array(6),
  aspectRatio: new Float32Array(6).fill(NaN),
  position: new Uint8Array(6),
  insetT: new Float32Array(6).fill(NaN),
  insetR: new Float32Array(6).fill(NaN),
  insetB: new Float32Array(6).fill(NaN),
  insetL: new Float32Array(6).fill(NaN),
  insetTPct: new Float32Array(6),
  insetRPct: new Float32Array(6),
  insetBPct: new Float32Array(6),
  insetLPct: new Float32Array(6),
  borderSpacingH: new Float32Array(6).fill(NaN),
  borderSpacingV: new Float32Array(6).fill(NaN),
  scrollMarginTop: new Float32Array(6),
  scrollMarginRight: new Float32Array(6),
  scrollMarginBottom: new Float32Array(6),
  scrollMarginLeft: new Float32Array(6),
  scrollPaddingTop: new Float32Array(6),
  scrollPaddingRight: new Float32Array(6),
  scrollPaddingBottom: new Float32Array(6),
  scrollPaddingLeft: new Float32Array(6),
  fontSize: new Float32Array(6).fill(14),
  fontWeight: new Uint16Array([400,400,600,400,400,600]),
  fontStyle: new Uint8Array(6),
  fontFamily: new Uint8Array(6),
  lineHeight: new Float32Array(6),
  lineHeightPx: new Float32Array(6).fill(NaN),
  textIndent: new Float32Array(6).fill(NaN),
  overflowX: new Uint8Array([3,0,0,0,0,0]),
  overflowY: new Uint8Array([3,0,0,0,0,0]),
  scrollbarWidth: new Uint8Array(6),
  scrollbarThumb: new Uint32Array(6),
  scrollbarTrack: new Uint32Array(6),
  accentColor: new Uint32Array(6),
  caretColor: new Uint32Array(6),
  appearance: new Uint8Array(6),
  cursor: new Uint8Array(6),
  opacity: new Float32Array(6).fill(1),
  translateX: new Float32Array(6),
  translateY: new Float32Array(6),
  translatePctX: new Float32Array(6),
  translatePctY: new Float32Array(6),
  rotate: new Float32Array(6),
  scaleX: new Float32Array(6).fill(1),
  scaleY: new Float32Array(6).fill(1),
  skewX: new Float32Array(6),
  skewY: new Float32Array(6),
  originPctX: new Float32Array(6).fill(0.5),
  originPctY: new Float32Array(6).fill(0.5),
  originPxX: new Float32Array(6),
  originPxY: new Float32Array(6),
  maskComposite: new Uint8Array(6),
  maskImage: new Uint8Array(6),
  filter: new Uint8Array(6),
  backdropFilter: new Uint8Array(6),
  zIndex: new Int32Array(6).fill(-2147483648),
  letterSpacing: new Float32Array(6),
  mixBlendMode: new Uint8Array(6),
  backgroundBlendMode: new Uint8Array(6),
  columnCount: new Uint16Array(6),
  columnWidth: new Float32Array(6).fill(NaN),
  zoom: new Float32Array(6).fill(NaN),
  touchAction: new Uint8Array(6).fill(7),
  whiteSpace: new Uint8Array(6),
  fontStretch: new Float32Array(6).fill(100),
  maskPosition: new Uint8Array(6),
  fill: new Uint32Array(6),
  stroke: new Uint32Array(6),
  strokeWidth: new Float32Array(6).fill(NaN),
  transition: new Uint16Array(6),
  animation: new Uint16Array(6),
} satisfies StyleTable;

export const nodes = {
  count: 9,
  kind: new Uint8Array([0,0,0,1,0,1,0,0,1]),
  style: new Uint16Array([0,1,2,2,3,3,4,5,2]),
  text: new Int32Array([-1,-1,-1,0,-1,1,-1,-1,2]),
  parent: new Int32Array([-1,0,1,2,1,4,0,6,7]),
  firstChild: new Int32Array([1,2,3,-1,5,-1,7,8,-1]),
  nextSibling: new Int32Array([-1,6,4,-1,-1,-1,-1,-1,-1]),
  list: new Int16Array(9).fill(-1),
  hidden: new Uint8Array(9),
  activates: new Int32Array(9).fill(-1),
} satisfies NodeTable;

/**
 * Conditional styling, sparse and sorted by node.
 *
 * mask is the predicate bits a node reads; slots[runStart + i] is its style for
 * the combination whose compacted bits equal i. Runs are shared between nodes
 * that resolve identically.
 */
export const variants = {
  count: 0,
  node: new Int32Array([]),
  mask: new Uint32Array([]),
  runStart: new Int32Array([]),
  slots: new Uint16Array([]),
} satisfies VariantTable;

/** Nodes that can receive input, sorted. Emitted, never inferred. */
export const interactive = new Int32Array([]);

/** `::before` / `::after` boxes, sorted. Their predicates come from the parent. */
export const generated = new Int32Array([]);
export const editableBoxes = new Int32Array([]);
export const placeholders = new Int32Array([]);
/** Overlay roots — painted after the tree, hit-tested before it. `::picker(select)`. */
export const overlays = new Int32Array([]);

/** Nodes Tab can reach, sorted. The set; the order is a live walk of the tree. */
export const tabStops = new Int32Array([]);

/** Nodes claiming `autofocus`, sorted. The engine focuses the first one showing. */
export const autofocus = new Int32Array([]);

/** Text areas, sorted. Enter in one types rather than submitting — measured. */
export const textAreas = new Int32Array([]);

/**
 * Every `<form>`: Enter's outcome, the fields it submits, and its payload's shape.
 *
 * **After the cells above**, which is required rather than tidy — a field holds the cell
 * itself rather than a name to look up, and `const` is not hoisted.
 */
export const forms = [

] satisfies FormBinding[];

/** Dynamic text runs. Literal chunks interleaved with the signals they read. */
export const textBindings = [

] satisfies TextBinding[];

/** Route-parameter text runs — literals interleaved with {args.x} reads. */
export const paramBindings = [

] satisfies ParamBinding[];

/** Loader-data text runs — literals interleaved with {data.x} reads. */
export const dataBindings = [

] satisfies DataBinding[];

/** Loader-error text runs — literals interleaved with {error.x} reads. */
export const errorBindings = [

] satisfies ErrorBinding[];

/** Click and change handlers, as direct references to the app's exported functions. */
export const handlers = [

] satisfies HandlerBinding[];

/**
 * Signals driving a control's DISABLED flag. Rows index `controls`, not `nodes`.
 *
 * Plural rows because a control in a list row has one per replica.
 *
 * **After `localsSource`, and that is required rather than tidy.** A component-local signal
 * is declared by this module rather than imported, so a binding that names one has to come
 * after the declaration — `const` is not hoisted, and emitting this block above the locals
 * threw "Cannot access 'local_5' before initialization" at import time, which is a broken
 * artifact rather than a failing test.
 */
export const disabledBindings = [

] satisfies DisabledBinding[];

/** Nodes that route keystrokes into a string signal while focused. */
export const editables = [

] satisfies EditableRef[];

/**
 * Dynamic image sources. When the signal moves, the worker rewrites
 * strings[slot] and the loader fetches the new path on the next frame.
 */
export const imageBindings = [

] satisfies ImageBinding[];

/**
 * Conditional classes, compiled to style-table writes.
 *
 * Each entry writes field values for the slots the class actually changes — no
 * class names, no cascade, and node style pointers untouched. affectsLayout says
 * whether applying it requires a relayout or only a repaint.
 */
export const stylePatches = [

] satisfies StylePatchRef[];

/**
 * Dynamic lists. Each owns a contiguous arena of identical item subtrees; the
 * runtime rewrites the child chain and the bound slots, never the nodes.
 */
export const lists = {
  count: 0,
  container: new Int32Array([]),
  anchorPrev: new Int32Array([]),
  anchorNext: new Int32Array([]),
  arenaStart: new Int32Array([]),
  stride: new Int32Array([]),
  capacity: new Int32Array([]),
  active: new Int32Array(0),
  dataOffset: new Int32Array(0),
} satisfies ListTable;

/** Per-list: the array signal, key path, and where each item's bound slots live. */
export const listBindings = [

] satisfies ListBindingRef[];

/**
 * Media conditions, one row per distinct threshold, in predicate-bit order.
 *
 * The engine re-evaluates these against the surface between a resize and the
 * relayout. Bun uploads them once and never looks at them again — routing a
 * resize back through Bun would lag a frame and stall whenever Bun is busy.
 */
export const media = {
  count: 0,
  bit: new Uint32Array([]),
  kind: new Uint8Array([]),
  value: new Float32Array([]),
} satisfies MediaTable;

/**
 * Transitions and animations, interned. One row per distinct spec on the page.
 *
 * A style row points at one of these by index **+ 1**, so zero is "no tween here"
 * and a style table that starts out zeroed says the right thing. A transition and a
 * keyframe animation are rows of this one table, because they are the same
 * mechanism: interpolation between two rows of the style table, differing only in
 * where the two rows come from.
 */
export const tweens = {
  count: 0,
  mask: new Uint32Array([]),
  duration: new Float32Array([]),
  delay: new Float32Array([]),
  iterations: new Float32Array([]),
  firstSegment: new Int32Array([]),
  segmentCount: new Uint16Array([]),
  easing: new Uint8Array([]),
  easeA: new Float32Array([]),
  easeB: new Float32Array([]),
  easeC: new Float32Array([]),
  easeD: new Float32Array([]),
} satisfies TweenTable;

/**
 * Keyframes: an offset and the interned style row it resolves to.
 *
 * Addressed as a slice by a tween's firstSegment/segmentCount. The easing on a row
 * is the curve of the segment *starting* at that keyframe — measured, and the reason
 * Tailwind's bounce needs no second concept.
 */
export const keyframes = {
  count: 0,
  style: new Uint16Array([]),
  offset: new Float32Array([]),
  easing: new Uint8Array([]),
  easeA: new Float32Array([]),
  easeB: new Float32Array([]),
  easeC: new Float32Array([]),
  easeD: new Float32Array([]),
} satisfies KeyframeTable;

/**
 * Form controls, sparse and sorted by node.
 *
 * The flags column is the state each control was *authored* in, and is read exactly
 * once — to seed the engine's own state. The engine owns it after that, so this
 * table stays constant while a checkbox is being ticked and a republish caused by
 * some unrelated signal cannot un-tick it.
 */
export const controls = {
  count: 0,
  node: new Int32Array([]),
  kind: new Uint8Array([]),
  group: new Int32Array([]),
  flags: new Uint8Array([]),
  label: new Int32Array([]),
  rows: new Int32Array([]),
  value: new Uint16Array([]),
  accept: [],
  multiple: new Uint8Array([]),
} satisfies ControlTable;

/**
 * min/max/step per range or number input, sorted by node. A side table beside
 * the shared protocol, not columns of it: the engine positions a thumb in
 * fractions and never reads these — the binding does, when a CHANGE comes back
 * as per-mille and somebody has to say what 612 per-mille means.
 */
export const numerics = {
  count: 0,
  node: new Int32Array([]),
  min: new Float32Array([]),
  max: new Float32Array([]),
  step: new Float32Array([]),
} satisfies NumericTable;

/**
 * Image references, sparse and sorted by node. Only the *reference* crosses:
 * the host resolves each src — a file read or a fetch — and hands the bytes to
 * the engine over FFI. See images.rs.
 */
export const images = {
  count: 0,
  node: new Int32Array([]),
  src: new Int32Array([]),
} satisfies ImageTable;

export const root: number = 0;

/**
 * The app modules this artifact references, as namespaces. Hot reload walks
 * them to carry module-level signal state across a worker swap; nothing else
 * reads them. Empty when the window referenced no app module.
 */
export const __state = [];
