// GENERATED by src/compile.ts from characterize/cases/pseudo-elements.html + characterize/cases/pseudo-elements.css
// Do not edit. No CSS, no selectors, no property names — just indices.
//
// 10 nodes, 9 style slots, 4 strings,
// 3 conditional nodes (6 variant slots), 2 interactive,
// 0 text bindings, 0 handlers.

// Types, so this artifact is checked rather than asserted at the far end.
import type { ControlTable, HandlerBinding, KeyframeTable, ListTable, MediaTable, NodeTable, StyleTable, TextBinding, TweenTable, VariantTable } from "dziri/ir.ts";
import type { EditableRef } from "dziri/runtime/bindings.ts";
import type { ListBindingRef } from "dziri/runtime/list-runtime.ts";
import type { StylePatchRef } from "dziri/runtime/patches.ts";

/** Mutable past the static entries: text bindings overwrite their own slots. */
export const strings: string[] = ["✓","“","”","mid"];

/** Mutable: style patches write field values in place. Node pointers never change. */
export const styles = {
  count: 9,
  bg: new Uint32Array([4278782219,4294967295,4294967295,0,0,4278355143,0,0,0]),
  fg: new Uint32Array([4293190887,4293190887,4293190887,0,4288782762,4293190887,4294967295,4293190887,4285624698]),
  borderColor: new Uint32Array([0,4285624698,4278355143,0,0,4278355143,0,0,0]),
  borderWidth: new Float32Array(9),
  radTL: new Float32Array([0,3,3,0,0,3,0,0,0]),
  radTR: new Float32Array([0,3,3,0,0,3,0,0,0]),
  radBR: new Float32Array([0,3,3,0,0,3,0,0,0]),
  radBL: new Float32Array([0,3,3,0,0,3,0,0,0]),
  ringOuterWidth: new Float32Array(9),
  ringOuterColor: new Uint32Array(9),
  ringInnerWidth: new Float32Array(9),
  ringInnerColor: new Uint32Array(9),
  ringInsetWidth: new Float32Array(9),
  ringInsetColor: new Uint32Array(9),
  selectionBg: new Uint32Array(9).fill(4281569535),
  selectionFg: new Uint32Array(9).fill(4294967295),
  padT: new Float32Array([12,0,0,0,0,0,0,0,0]),
  padR: new Float32Array([12,0,0,0,0,0,0,0,0]),
  padB: new Float32Array([12,0,0,0,0,0,0,0,0]),
  padL: new Float32Array([12,0,0,0,0,0,0,0,0]),
  marT: new Float32Array(9),
  marR: new Float32Array(9),
  marB: new Float32Array(9),
  marL: new Float32Array(9),
  display: new Uint8Array(9),
  direction: new Uint8Array(9).fill(1),
  wrap: new Uint8Array(9),
  justify: new Uint8Array(9),
  align: new Uint8Array(9).fill(255),
  alignSelf: new Uint8Array(9).fill(255),
  justifyItems: new Uint8Array(9).fill(255),
  justifySelf: new Uint8Array(9).fill(255),
  grow: new Float32Array(9),
  shrink: new Float32Array(9).fill(1),
  basis: new Float32Array(9).fill(NaN),
  gapRow: new Float32Array([8,0,0,0,0,0,0,0,0]),
  gapCol: new Float32Array([8,0,0,0,0,0,0,0,0]),
  gridCols: new Uint16Array(9),
  gridRows: new Uint16Array(9),
  gridColStart: new Int16Array(9),
  gridColSpan: new Int16Array(9),
  gridRowStart: new Int16Array(9),
  gridRowSpan: new Int16Array(9),
  width: new Float32Array([NaN,16,16,NaN,NaN,16,NaN,NaN,NaN]),
  height: new Float32Array([NaN,16,16,NaN,NaN,16,NaN,NaN,NaN]),
  minW: new Float32Array(9).fill(NaN),
  minH: new Float32Array(9).fill(NaN),
  maxW: new Float32Array(9).fill(Infinity),
  maxH: new Float32Array(9).fill(Infinity),
  aspectRatio: new Float32Array(9).fill(NaN),
  position: new Uint8Array(9),
  insetT: new Float32Array(9).fill(NaN),
  insetR: new Float32Array(9).fill(NaN),
  insetB: new Float32Array(9).fill(NaN),
  insetL: new Float32Array(9).fill(NaN),
  fontSize: new Float32Array([14,14,14,12,12,14,12,14,14]),
  fontWeight: new Uint16Array(9).fill(400),
  overflowX: new Uint8Array(9),
  overflowY: new Uint8Array(9),
  scrollbarWidth: new Uint8Array(9),
  scrollbarThumb: new Uint32Array(9),
  scrollbarTrack: new Uint32Array(9),
  accentColor: new Uint32Array([0,4278355143,4278355143,4278355143,4278355143,4278355143,4278355143,0,0]),
  caretColor: new Uint32Array(9),
  appearance: new Uint8Array(9),
  opacity: new Float32Array(9).fill(1),
  translateX: new Float32Array(9),
  translateY: new Float32Array(9),
  translatePctX: new Float32Array(9),
  translatePctY: new Float32Array(9),
  rotate: new Float32Array(9),
  scaleX: new Float32Array(9).fill(1),
  scaleY: new Float32Array(9).fill(1),
  skewX: new Float32Array(9),
  skewY: new Float32Array(9),
  originPctX: new Float32Array(9).fill(0.5),
  originPctY: new Float32Array(9).fill(0.5),
  originPxX: new Float32Array(9),
  originPxY: new Float32Array(9),
  transition: new Uint16Array(9),
  animation: new Uint16Array(9),
} satisfies StyleTable;

export const nodes = {
  count: 10,
  kind: new Uint8Array([0,0,1,0,1,0,1,1,1,0]),
  style: new Uint16Array([0,1,3,5,6,7,8,8,7,7]),
  text: new Int32Array([-1,-1,0,-1,0,-1,1,2,3,-1]),
  parent: new Int32Array([-1,0,1,0,3,0,5,5,5,0]),
  firstChild: new Int32Array([1,2,-1,4,-1,6,-1,-1,-1,-1]),
  nextSibling: new Int32Array([-1,3,-1,5,-1,9,8,-1,7,-1]),
  list: new Int16Array(10).fill(-1),
  hidden: new Uint8Array(10),
  activates: new Int32Array(10).fill(-1),
} satisfies NodeTable;

/**
 * Conditional styling, sparse and sorted by node.
 *
 * mask is the predicate bits a node reads; slots[runStart + i] is its style for
 * the combination whose compacted bits equal i. Runs are shared between nodes
 * that resolve identically.
 */
export const variants = {
  count: 3,
  node: new Int32Array([1,2,4]),
  mask: new Uint32Array(3).fill(1),
  runStart: new Int32Array([0,2,4]),
  slots: new Uint16Array([1,2,3,4,6,4]),
} satisfies VariantTable;

/** Nodes that can receive input, sorted. Emitted, never inferred. */
export const interactive = new Int32Array([1,3]);

/** `::before` / `::after` boxes, sorted. Their predicates come from the parent. */
export const generated = new Int32Array([2,4,6,7]);
export const editableBoxes = new Int32Array([]);
export const placeholders = new Int32Array([]);
/** Overlay roots — painted after the tree, hit-tested before it. `::picker(select)`. */
export const overlays = new Int32Array([]);

/** Dynamic text runs. Literal chunks interleaved with the signals they read. */
export const textBindings = [

] satisfies TextBinding[];

/** Click handlers, as direct references to the app's exported functions. */
export const handlers = [

] satisfies HandlerBinding[];

/** Nodes that route keystrokes into a string signal while focused. */
export const editables = [

] satisfies EditableRef[];

/**
 * Conditional classes, compiled to style-table writes.
 *
 * Each entry writes field values for the slots the class actually changes — no
 * class names, no cascade, and node style pointers untouched. affectsLayout says
 * whether applying it requires a relayout or only a repaint.
 */
export const stylePatches = [

] satisfies StylePatchRef[];

/**
 * Dynamic lists. Each owns a contiguous arena of identical item subtrees; the
 * runtime rewrites the child chain and the bound slots, never the nodes.
 */
export const lists = {
  count: 0,
  container: new Int32Array([]),
  anchorPrev: new Int32Array([]),
  anchorNext: new Int32Array([]),
  arenaStart: new Int32Array([]),
  stride: new Int32Array([]),
  capacity: new Int32Array([]),
  active: new Int32Array(0),
  dataOffset: new Int32Array(0),
} satisfies ListTable;

/** Per-list: the array signal, key path, and where each item's bound slots live. */
export const listBindings = [

] satisfies ListBindingRef[];

/**
 * Media conditions, one row per distinct threshold, in predicate-bit order.
 *
 * The engine re-evaluates these against the surface between a resize and the
 * relayout. Bun uploads them once and never looks at them again — routing a
 * resize back through Bun would lag a frame and stall whenever Bun is busy.
 */
export const media = {
  count: 0,
  bit: new Uint32Array([]),
  kind: new Uint8Array([]),
  value: new Float32Array([]),
} satisfies MediaTable;

/**
 * Transitions and animations, interned. One row per distinct spec on the page.
 *
 * A style row points at one of these by index **+ 1**, so zero is "no tween here"
 * and a style table that starts out zeroed says the right thing. A transition and a
 * keyframe animation are rows of this one table, because they are the same
 * mechanism: interpolation between two rows of the style table, differing only in
 * where the two rows come from.
 */
export const tweens = {
  count: 0,
  mask: new Uint32Array([]),
  duration: new Float32Array([]),
  delay: new Float32Array([]),
  iterations: new Float32Array([]),
  firstSegment: new Int32Array([]),
  segmentCount: new Uint16Array([]),
  easing: new Uint8Array([]),
  easeA: new Float32Array([]),
  easeB: new Float32Array([]),
  easeC: new Float32Array([]),
  easeD: new Float32Array([]),
} satisfies TweenTable;

/**
 * Keyframes: an offset and the interned style row it resolves to.
 *
 * Addressed as a slice by a tween's firstSegment/segmentCount. The easing on a row
 * is the curve of the segment *starting* at that keyframe — measured, and the reason
 * Tailwind's bounce needs no second concept.
 */
export const keyframes = {
  count: 0,
  style: new Uint16Array([]),
  offset: new Float32Array([]),
  easing: new Uint8Array([]),
  easeA: new Float32Array([]),
  easeB: new Float32Array([]),
  easeC: new Float32Array([]),
  easeD: new Float32Array([]),
} satisfies KeyframeTable;

/**
 * Form controls, sparse and sorted by node.
 *
 * The flags column is the state each control was *authored* in, and is read exactly
 * once — to seed the engine's own state. The engine owns it after that, so this
 * table stays constant while a checkbox is being ticked and a republish caused by
 * some unrelated signal cannot un-tick it.
 */
export const controls = {
  count: 0,
  node: new Int32Array([]),
  kind: new Uint8Array([]),
  group: new Int32Array([]),
  flags: new Uint8Array([]),
  label: new Int32Array([]),
} satisfies ControlTable;

export const root: number = 0;
