// GENERATED by src/compile.ts from windows/main/index.tsx + windows/main/index.css
// Do not edit. No CSS, no selectors, no property names — just indices.
//
// 165 nodes, 62 style slots, 59 strings,
// 33 conditional nodes (18 variant slots), 35 interactive,
// 4 text bindings, 4 handlers.

import { addTodo, clearDraft, deleteTodo, draft, isCompact, isLight, remaining, toggleDensity, toggleDone, toggleTheme, total, view } from "./../../../workspace/skia-proto/windows/main/state.ts";

// Types, so this artifact is checked rather than asserted at the far end.
import type { HandlerBinding, ListTable, MediaTable, NodeTable, StyleTable, TextBinding, VariantTable, RouteNodes, WindowConfig } from "../../../workspace/skia-proto/src/ir.ts";
import type { EditableRef } from "../../../workspace/skia-proto/src/runtime/bindings.ts";
import type { ListBindingRef } from "../../../workspace/skia-proto/src/runtime/list-runtime.ts";
import type { StylePatchRef } from "../../../workspace/skia-proto/src/runtime/patches.ts";

/** Mutable past the static entries: text bindings overwrite their own slots. */
export const strings: string[] = ["dziri","Home","Routing","Products","About","Taffy lays out · Skia paints · SDL3 owns the window","Theme","Density","grid + flex","both, from one style table","","remaining","","total","Dynamic list · keyed · per-row handlers","","Add","Clear","","","x","","","","","","","","","","","","","","","","","Flex · wrap, align-self, aspect-ratio","flex","grid","wrap","grow","align-self","aspect-ratio","absolute","gap","left: 10px · bottom: 10px","string","object","inline beats every selector · 8 is 8px, 600 is not"," of  left · compiled at build time, no CSS in the runtime","no DOM · no browser engine","A window is windows/main/index.tsx; its routes are the files under pages/. The route path is the file path, and a $segment is a parameter.","New","First","A static route, sorted before the parameter route beside it.","A parameter route. Its pattern is products/$id, bound per navigation.","Every route in this window is compiled into one table set. The five that are not showing are resident and hidden, which costs memory and nothing per frame: hidden already excludes a subtree from layout, paint and hit-testing.","Switching route writes one byte per route root — bounded by route count, not by node count. Nothing is allocated, nothing grows, nothing is rebuilt."];

/** Mutable: style patches write field values in place. Node pointers never change. */
export const styles = {
  count: 62,
  bg: new Uint32Array([4279769115,0,4280295460,0,0,4280756010,4281611322,0,0,0,0,0,0,0,0,4280756014,4281479738,4280032290,4280032290,0,4280034614,0,0,4280492841,0,4280229668,0,4280492841,4280492841,0,4282090230,4284524026,0,4279900703,4280756014,4281479738,0,0,4280756014,4286520605,0,4280756014,4281479738,0,0,4282090230,4287323382,4293675161,4280468830,4280492841,4282090230,0,0,4290321436,4279599165,0,4280295460,0,0,0,4280756010,4279769115]),
  fg: new Uint32Array([4293190887,4293190887,4293190887,4294638330,4293190887,4288782762,4293190887,4288782762,4293190887,4293190887,4293190887,4293190887,4294638330,4285624698,4293190887,4292138200,4294243573,4292138200,4294243573,4293190887,4293190887,4294638330,4285624698,4293190887,4293190887,4293190887,4288782762,4294243573,4294243573,4294243573,4294967295,4294967295,4293190887,4293190887,4288782762,4294243573,4293190887,4293190887,4288782762,4294888138,4293190887,4288782762,4294243573,4288782762,4293190887,4293190887,4293190887,4293190887,4293190887,4293190887,4294967295,4294967295,4285624698,4294894306,4292672743,4293190887,4293190887,4294638330,4288782762,4293190887,4288782762,4293190887]),
  borderColor: new Uint32Array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4282335046,4282335046,4282335046,4282335046,0,4281287784,0,0,4281282359,0,4281282359,0,4282335046,4282090230,0,4282090230,4282090230,0,0,4283585115,4283585115,0,0,4282335046,4288224027,0,4282335046,4283585115,0,0,0,0,0,0,4281282359,0,0,0,4282335046,4282335046,0,0,0,0,0,0,0]),
  borderWidth: new Float32Array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,1,0,0,1,0,1,0,1,1,0,1,1,0,0,1,1,0,0,1,1,0,1,1,0,0,0,0,0,0,1,0,0,0,1,1,0,0,0,0,0,0,0]),
  radius: new Float32Array([0,0,10,0,0,6,6,0,0,0,0,0,0,0,0,6,6,6,6,0,8,0,0,8,0,10,0,6,6,0,6,6,0,6,4,4,0,0,4,4,0,999,999,0,0,6,6,6,6,8,999,0,0,6,6,0,10,0,0,0,5,8]),
  padT: new Float32Array([18,0,10,0,0,5,5,0,0,0,0,0,0,0,0,8,8,8,8,0,10,0,0,10,0,14,0,9,9,0,8,8,0,7,2,2,0,0,2,2,0,4,4,0,0,0,0,0,0,0,3,0,0,8,8,0,18,0,0,0,5,12]),
  padR: new Float32Array([18,0,14,0,0,11,11,0,0,0,0,0,0,0,0,14,14,14,14,0,12,0,0,12,0,14,0,12,12,0,14,14,0,10,6,6,0,0,8,8,0,10,10,0,0,0,0,0,0,0,9,0,0,14,14,0,18,0,0,0,10,12]),
  padB: new Float32Array([18,0,10,0,0,5,5,0,0,0,0,0,0,0,0,8,8,8,8,0,10,0,0,10,0,14,0,9,9,0,8,8,0,7,2,2,0,0,2,2,0,4,4,0,0,0,0,0,0,0,3,0,0,8,8,0,18,0,0,0,5,12]),
  padL: new Float32Array([18,0,14,0,0,11,11,0,0,0,0,0,0,0,0,14,14,14,14,0,12,0,0,12,0,14,0,12,12,0,14,14,0,10,6,6,0,0,8,8,0,10,10,0,0,0,0,0,0,0,9,0,0,14,24,0,18,0,0,0,10,12]),
  marT: new Float32Array(62),
  marR: new Float32Array(62),
  marB: new Float32Array(62),
  marL: new Float32Array(62),
  display: new Uint8Array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]),
  direction: new Uint8Array([1,1,0,1,0,1,1,1,1,1,0,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0,1,1,1,0,1,1,1,1,1,1,1,1,1,1,0,1,1,1,0,1,1]),
  wrap: new Uint8Array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]),
  justify: new Uint8Array([0,0,3,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0]),
  align: new Uint8Array([255,255,1,255,255,255,255,255,255,255,1,255,255,255,1,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,1,255,255,255,255,255,255,1,255,255,255,0,255,255,255,255,255,255,255,255,255,255,1,255,255,255,255,255,255]),
  alignSelf: new Uint8Array([255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,1,2,3,255,255,255,255,255,255,255,255,255,255,255,255,255]),
  grow: new Float32Array([0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]),
  shrink: new Float32Array(62).fill(1),
  basis: new Float32Array([NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN]),
  gapRow: new Float32Array([0,14,0,0,6,0,0,0,0,14,0,0,0,0,8,0,0,0,0,10,2,0,0,2,14,10,0,0,0,0,0,0,4,10,0,0,0,0,0,0,6,0,0,0,8,0,0,0,0,0,0,0,0,0,0,8,12,0,0,8,0,0]),
  gapCol: new Float32Array([0,14,0,0,6,0,0,0,0,14,0,0,0,0,8,0,0,0,0,10,2,0,0,2,14,10,0,0,0,0,0,0,4,10,0,0,0,0,0,0,6,0,0,0,8,0,0,0,0,0,0,0,0,0,0,8,12,0,0,8,0,0]),
  gridCols: new Uint16Array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]),
  gridRows: new Uint16Array(62),
  gridColStart: new Int16Array(62),
  gridColSpan: new Int16Array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]),
  gridRowStart: new Int16Array(62),
  gridRowSpan: new Int16Array(62),
  justifyItems: new Uint8Array(62).fill(255),
  justifySelf: new Uint8Array(62).fill(255),
  width: new Float32Array([NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34,34,34,34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN]),
  height: new Float32Array([NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,74,NaN,NaN,NaN,NaN,96,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN]),
  minW: new Float32Array(62).fill(NaN),
  maxW: new Float32Array(62).fill(Infinity),
  minH: new Float32Array(62).fill(NaN),
  maxH: new Float32Array(62).fill(Infinity),
  aspectRatio: new Float32Array([NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN]),
  position: new Uint8Array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0]),
  insetT: new Float32Array([NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN]),
  insetR: new Float32Array([NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN]),
  insetB: new Float32Array([NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN]),
  insetL: new Float32Array([NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN]),
  fontSize: new Float32Array([14,14,14,15,14,13,13,13,14,14,14,14,22,12,14,13,13,13,13,14,14,20,11,14,14,14,13,14,14,14,13,13,14,14,13,13,14,14,13,13,14,12,12,12,14,14,14,14,14,14,11,11,12,13,13,14,14,18,14,14,13,14]),
  fontWeight: new Uint16Array([400,400,400,600,400,400,400,400,400,400,400,400,600,400,400,400,400,400,400,400,400,600,400,400,400,400,600,400,400,400,400,400,400,400,400,400,400,400,400,400,400,400,400,400,400,400,400,400,400,400,600,600,400,400,600,400,400,600,400,400,400,400]),
  overflowX: new Uint8Array([3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]),
  overflowY: new Uint8Array([3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]),
  scrollbarWidth: new Uint8Array(62),
  scrollbarThumb: new Uint32Array(62).fill(4283585115),
  scrollbarTrack: new Uint32Array(62),
} satisfies StyleTable;

export const nodes = {
  count: 165,
  kind: new Uint8Array([0,0,0,0,1,0,0,1,0,1,0,1,0,1,0,0,0,0,0,1,0,1,0,2,2,0,0,0,1,0,1,0,0,1,0,1,0,0,1,0,1,0,0,0,1,0,0,1,2,2,0,0,2,1,0,1,2,0,2,1,0,1,2,0,2,1,0,1,2,0,2,1,0,1,2,0,2,1,0,1,2,0,2,1,0,1,2,0,2,1,0,1,2,0,2,1,0,1,2,0,0,1,0,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,0,0,0,0,0,0,1,0,1,0,2,2,0,1,0,0,1,0,1,0,0,1,0,1,0,0,1,0,0,1,0,1,0,0,1,0,0,1,0,0,1,0,1,0,1]),
  style: new Uint16Array([0,1,2,3,3,4,5,7,5,7,5,7,5,7,8,9,10,11,12,12,13,13,14,15,15,19,20,21,21,22,22,23,21,21,22,22,23,21,21,22,22,24,25,26,26,14,27,29,30,15,32,33,34,7,36,37,38,33,34,7,36,37,38,33,34,7,36,37,38,33,34,7,36,37,38,33,34,7,36,37,38,33,34,7,36,37,38,33,34,7,36,37,38,33,34,7,36,37,38,25,26,26,40,41,43,41,43,41,43,41,43,41,43,41,43,41,43,41,43,44,45,46,47,48,49,50,51,52,13,14,53,54,13,13,55,13,13,13,13,56,57,57,58,58,56,57,57,59,60,7,60,7,61,58,58,61,58,58,56,57,57,58,58,58,58]),
  text: new Int32Array([-1,-1,-1,-1,0,-1,-1,1,-1,2,-1,3,-1,4,-1,-1,-1,-1,-1,0,-1,5,-1,6,7,-1,-1,-1,8,-1,9,-1,-1,10,-1,11,-1,-1,12,-1,13,-1,-1,-1,14,-1,-1,15,16,17,-1,-1,-1,21,-1,22,20,-1,-1,23,-1,24,20,-1,-1,25,-1,26,20,-1,-1,27,-1,28,20,-1,-1,29,-1,30,20,-1,-1,31,-1,32,20,-1,-1,33,-1,34,20,-1,-1,35,-1,36,20,-1,-1,37,-1,-1,38,-1,39,-1,40,-1,41,-1,42,-1,43,-1,44,-1,45,-1,-1,-1,-1,-1,-1,-1,44,-1,46,-1,47,48,-1,49,-1,-1,50,-1,51,-1,-1,4,-1,52,-1,-1,3,-1,-1,53,-1,54,-1,-1,55,-1,-1,56,-1,-1,2,-1,57,-1,58]),
  parent: new Int32Array([-1,0,1,2,3,2,5,6,5,8,5,10,5,12,1,14,15,16,17,18,17,20,16,22,22,15,25,26,27,26,29,25,31,32,31,34,25,36,37,36,39,15,41,42,43,42,45,46,45,45,42,50,51,52,51,54,51,50,57,58,57,60,57,50,63,64,63,66,63,50,69,70,69,72,69,50,75,76,75,78,75,50,81,82,81,84,81,50,87,88,87,90,87,50,93,94,93,96,93,41,99,100,99,102,103,102,105,102,107,102,109,102,111,102,113,102,115,102,117,99,119,119,119,119,99,124,125,124,127,15,129,129,129,132,15,134,135,134,137,14,139,140,139,142,14,144,145,144,147,148,147,150,144,152,153,144,155,156,14,158,159,158,161,158,163]),
  firstChild: new Int32Array([1,2,3,4,-1,6,7,-1,9,-1,11,-1,13,-1,15,16,17,18,19,-1,21,-1,23,-1,-1,26,27,28,-1,30,-1,32,33,-1,35,-1,37,38,-1,40,-1,42,43,44,-1,46,47,-1,-1,-1,-1,52,53,-1,55,-1,-1,58,59,-1,61,-1,-1,64,65,-1,67,-1,-1,70,71,-1,73,-1,-1,76,77,-1,79,-1,-1,82,83,-1,85,-1,-1,88,89,-1,91,-1,-1,94,95,-1,97,-1,-1,100,101,-1,103,104,-1,106,-1,108,-1,110,-1,112,-1,114,-1,116,-1,118,-1,120,-1,-1,-1,-1,125,126,-1,128,-1,130,-1,-1,133,-1,135,136,-1,138,-1,140,141,-1,143,-1,145,146,-1,148,149,-1,151,-1,153,154,-1,156,157,-1,159,160,-1,162,-1,164,-1]),
  nextSibling: new Int32Array([-1,-1,14,5,-1,-1,8,-1,10,-1,12,-1,-1,-1,-1,139,25,22,20,-1,-1,-1,-1,24,-1,41,31,29,-1,-1,-1,36,34,-1,-1,-1,-1,39,-1,-1,-1,129,99,45,-1,50,48,-1,49,-1,-1,-1,54,-1,56,-1,-1,-1,60,-1,62,-1,-1,-1,66,-1,68,-1,-1,-1,72,-1,74,-1,-1,-1,78,-1,80,-1,-1,-1,84,-1,86,-1,-1,-1,90,-1,92,-1,-1,-1,96,-1,98,-1,-1,-1,102,-1,119,105,-1,107,-1,109,-1,111,-1,113,-1,115,-1,117,-1,-1,-1,124,121,122,123,-1,-1,127,-1,-1,-1,134,131,132,-1,-1,-1,137,-1,-1,-1,144,142,-1,-1,-1,158,147,-1,152,150,-1,-1,-1,155,-1,-1,-1,-1,-1,-1,161,-1,163,-1,-1,-1]),
  list: new Int16Array(165).fill(-1),
  hidden: new Uint8Array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,1,0,0,0,0,0,0]),
} satisfies NodeTable;

/**
 * Conditional styling, sparse and sorted by node.
 *
 * mask is the predicate bits a node reads; slots[runStart + i] is its style for
 * the combination whose compacted bits equal i. Runs are shared between nodes
 * that resolve identically.
 */
export const variants = {
  count: 33,
  node: new Int32Array([6,8,10,12,23,24,46,48,49,52,56,58,62,64,68,70,74,76,80,82,86,88,92,94,98,103,105,107,109,111,113,115,117]),
  mask: new Uint32Array([1,1,1,1,3,3,4,3,3,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]),
  runStart: new Int32Array([0,0,0,0,2,2,6,8,2,12,14,12,14,12,14,12,14,12,14,12,14,12,14,12,14,16,16,16,16,16,16,16,16]),
  slots: new Uint16Array([5,6,15,16,17,18,27,28,30,31,30,31,34,35,38,39,41,42]),
} satisfies VariantTable;

/** Nodes that can receive input, sorted. Emitted, never inferred. */
export const interactive = new Int32Array([6,8,10,12,23,24,46,48,49,52,56,58,62,64,68,70,74,76,80,82,86,88,92,94,98,103,105,107,109,111,113,115,117,130,131]);

/** Dynamic text runs. Literal chunks interleaved with the signals they read. */
export const textBindings = [
  { node: 33, slot: 10, parts: [{ signal: remaining }] },
  { node: 38, slot: 12, parts: [{ signal: total }] },
  { node: 47, slot: 15, parts: [{ signal: draft }] },
  { node: 136, slot: 50, parts: [{ signal: remaining }, { literal: " of " }, { signal: total }, { literal: " left · compiled at build time, no CSS in the runtime" }] },
] satisfies TextBinding[];

/** Click handlers, as direct references to the app's exported functions. */
export const handlers = [
  { node: 23, fn: toggleTheme },
  { node: 24, fn: toggleDensity },
  { node: 48, fn: addTodo },
  { node: 49, fn: clearDraft },
] satisfies HandlerBinding[];

/** Nodes that route keystrokes into a string signal while focused. */
export const editables = [
  { node: 46, signal: draft },
] satisfies EditableRef[];

/**
 * Conditional classes, compiled to style-table writes.
 *
 * Each entry writes field values for the slots the class actually changes — no
 * class names, no cascade, and node style pointers untouched. affectsLayout says
 * whether applying it requires a relayout or only a repaint.
 */
export const stylePatches = [
  {
    signal: isLight,
    affectsLayout: false,
    entries: [
      { field: "bg", slots: new Uint16Array([0,2,5,6,15,16,17,18,20,23,25,27,28,30,33,34,35,38,39,41,42,49,56,60,61]), on: new Float64Array([4294638330,4294243573,4293190887,4292138200,4294243573,4294243573,4294243573,4294243573,4293916415,4294967295,4294967295,4294967295,4294967295,4294243573,4294243573,4294243573,4294243573,4294243573,4294243573,4294243573,4294243573,4294243573,4294967295,4293190887,4294243573]), off: new Float64Array([4279769115,4280295460,4280756010,4281611322,4280756014,4281479738,4280032290,4280032290,4280034614,4280492841,4280229668,4280492841,4280492841,4282090230,4279900703,4280756014,4281479738,4280756014,4286520605,4280756014,4281479738,4280492841,4280295460,4280756010,4279769115]) },
      { field: "fg", slots: new Uint16Array([0,1,2,3,4,5,6,7,8,9,10,11,12,14,15,16,17,18,19,20,21,23,24,25,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,55,56,57,58,59,60,61]), on: new Float64Array([4279769115,4279769115,4279769115,4279769115,4279769115,4283585115,4279769115,4283585115,4279769115,4279769115,4279769115,4279769115,4278782219,4279769115,4282335046,4282335046,4282335046,4282335046,4279769115,4279769115,4278782219,4279769115,4279769115,4279769115,4279769115,4279769115,4279769115,4282335046,4282335046,4279769115,4279769115,4283585115,4283585115,4280756010,4280756010,4283585115,4283585115,4279769115,4283585115,4283585115,4283585115,4279769115,4279769115,4279769115,4279769115,4279769115,4279769115,4279769115,4279769115,4279769115,4283585115,4279769115,4283585115,4279769115]), off: new Float64Array([4293190887,4293190887,4293190887,4294638330,4293190887,4288782762,4293190887,4288782762,4293190887,4293190887,4293190887,4293190887,4294638330,4293190887,4292138200,4294243573,4292138200,4294243573,4293190887,4293190887,4294638330,4293190887,4293190887,4293190887,4294243573,4294243573,4294243573,4294967295,4294967295,4293190887,4293190887,4288782762,4294243573,4293190887,4293190887,4288782762,4294888138,4293190887,4288782762,4294243573,4288782762,4293190887,4293190887,4293190887,4293190887,4293190887,4293190887,4293190887,4293190887,4294638330,4288782762,4293190887,4288782762,4293190887]) },
      { field: "borderColor", slots: new Uint16Array([15,16,17,18,20,23,25,27,28,30,31,34,35,38,39,41,42,49,53,54]), on: new Float64Array([4292138200,4292138200,4292138200,4292138200,4290763774,4293190887,4293190887,4292138200,4292138200,4292138200,4292138200,4292138200,4292138200,4292138200,4292138200,4293190887,4293190887,4293190887,4292138200,4292138200]), off: new Float64Array([4282335046,4282335046,4282335046,4282335046,4281287784,4281282359,4281282359,4282335046,4282090230,4282090230,4282090230,4283585115,4283585115,4282335046,4288224027,4282335046,4283585115,4281282359,4282335046,4282335046]) },
    ],
  },
  {
    signal: isCompact,
    affectsLayout: true,
    entries: [
      { field: "gapRow", slots: new Uint16Array([9,25,32]), on: new Float64Array([8,6,1]), off: new Float64Array([14,10,4]) },
      { field: "gapCol", slots: new Uint16Array([9,25,32]), on: new Float64Array([8,6,1]), off: new Float64Array([14,10,4]) },
      { field: "padT", slots: new Uint16Array([20,23,25,33]), on: new Float64Array([6,6,8,2]), off: new Float64Array([10,10,14,7]) },
      { field: "padR", slots: new Uint16Array([20,23,25,33]), on: new Float64Array([10,10,8,8]), off: new Float64Array([12,12,14,10]) },
      { field: "padB", slots: new Uint16Array([20,23,25,33]), on: new Float64Array([6,6,8,2]), off: new Float64Array([10,10,14,7]) },
      { field: "padL", slots: new Uint16Array([20,23,25,33]), on: new Float64Array([10,10,8,8]), off: new Float64Array([12,12,14,10]) },
    ],
  },
] satisfies StylePatchRef[];

/**
 * Dynamic lists. Each owns a contiguous arena of identical item subtrees; the
 * runtime rewrites the child chain and the bound slots, never the nodes.
 */
export const lists = {
  count: 1,
  container: new Int32Array([50]),
  anchorPrev: new Int32Array([-1]),
  anchorNext: new Int32Array([-1]),
  arenaStart: new Int32Array([51]),
  stride: new Int32Array([6]),
  capacity: new Int32Array([8]),
  active: new Int32Array(1),
  dataOffset: new Int32Array(1),
} satisfies ListTable;

/** Per-list: the array signal, key path, and where each item's bound slots live. */
export const listBindings = [
  {
    list: 0,
    signal: view,
    keyPath: ["id"],
    slotStart: 21,
    slotsPerItem: 2,
    bindings: [
      { offset: 2, slotOffset: 0, parts: [{ path: ["mark"] }] },
      { offset: 4, slotOffset: 1, parts: [{ path: ["title"] }] },
    ],
    itemHandlers: [
      { offset: 1, fn: toggleDone },
      { offset: 5, fn: deleteTodo },
    ],
  },
] satisfies ListBindingRef[];

/**
 * Media conditions, one row per distinct threshold, in predicate-bit order.
 *
 * The engine re-evaluates these against the surface between a resize and the
 * relayout. Bun uploads them once and never looks at them again — routing a
 * resize back through Bun would lag a frame and stall whenever Bun is busy.
 */
export const media = {
  count: 0,
  bit: new Uint32Array([]),
  kind: new Uint8Array([]),
  value: new Float32Array([]),
} satisfies MediaTable;

export const root: number = 0;

/** The window this artifact is, as `<Window>` declared it. */
export const windowConfig = {
  title: "dziri — compiled UI",
  width: 1040,
  height: 620,
  minWidth: 480,
  minHeight: 360,
} satisfies WindowConfig;

/**
 * Each route's own top-level nodes, in the window's match order.
 *
 * Navigation writes `hidden` over the routes leaving the chain and clears it over
 * the ones joining — bounded by route count, not by node count.
 */
export const routeNodes = [
  { path: "/", roots: [15], parent: -1 },
  { path: "about", roots: [139], parent: -1 },
  { path: "products", roots: [144], parent: -1 },
  { path: "routing", roots: [158], parent: -1 },
  { path: "products/new", roots: [152], parent: 2 },
  { path: "products/$id", roots: [155], parent: 2 },
] satisfies RouteNodes[];

/** Index in `routeNodes` of the route the emitted `hidden` column shows. */
export const initialRoute: number = 0;

/** Folder name of the window, for diagnostics and multi-window dispatch later. */
export const windowId: string = "main";
