/**
 * `dziri build` — the app as one executable.
 *
 * Three things have to end up inside it, and each one needed a measurement rather
 * than an assumption:
 *
 * 1. **The app.** `bun build --compile` over `windows/entry.gen.ts`, which is the
 *    same file `dziri dev` runs — so a bug that only appears in the packaged app
 *    is a packaging bug, not a different code path.
 *
 * 2. **The engine.** Embedded as a file asset and unpacked on first run. It cannot
 *    stay in the virtual filesystem: `dlopen` does not accept a `B:/~BUN/root/`
 *    path. See `engine/embed.ts`.
 *
 * 3. **A wrapper entry**, generated into a scratch directory, whose whole job is to
 *    hold the `with { type: "file" }` import — the specifier has to be a literal,
 *    and the engine's path is platform- and machine-dependent, so it cannot be
 *    written in a checked-in source file.
 *
 * # What this does not do yet
 *
 * Cross-compilation, code signing and notarization. `bun build --compile --target`
 * can cross-build the *JavaScript* half, but the engine embedded here is the one
 * built for this machine, so a cross-built binary would carry the wrong library.
 * Shipping for another platform means building the engine there. ROADMAP's D2 has
 * this as CI work with a pinned toolchain, and it is the honest place for it.
 */
import { existsSync, mkdirSync, statSync } from "node:fs";
import { basename, join, resolve } from "node:path";
import { compileProject, describe, ENTRY_FILE, WORKER_FILE } from "../compiler/build.ts";
import { libraryName } from "../engine/host.ts";
import { PACKAGE } from "../compiler/compile.ts";
import { reactivePlugin, reactiveEnabled } from "../compiler/reactive-plugin.ts";

export type BuildOptions = {
  projectDir: string;
  /** Output directory, relative to the project. Defaults to `dist`. */
  outDir?: string;
  /** Executable name without the extension. Defaults to the project directory's name. */
  name?: string;
  /** Keep the scratch entry, for looking at what was generated. */
  keepScratch?: boolean;
  /** Windows: leave the executable a console app, so it can print. */
  console?: boolean;
  /** Ship readable JavaScript inside the executable. Costs ~48 KiB of 117 MB. */
  noMinify?: boolean;
};

export type BuildResult = {
  outFile: string;
  bytes: number;
  engineBytes: number;
  engineHash: string;
  elapsed: number;
};

/**
 * Finds the engine this build should carry.
 *
 * The same two candidates the loader searches at run time, in the same order, so
 * `dziri dev` and `dziri build` cannot end up running different engines.
 */
function findEngine(): string {
  const name = libraryName();
  const here = new URL("../..", import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, "$1");

  const candidates = [
    join(here, "native-src", "dziri-engine", "target", "release", name),
    join(here, "native", `${process.platform}-${process.arch}`, name),
  ];

  for (const path of candidates) if (existsSync(path)) return path;
  throw new Error(
    `no engine binary to embed. Build it first (\`bun run engine\`).\n  looked in:\n` +
      candidates.map((c) => `    ${c}`).join("\n"),
  );
}

/**
 * The engine's identity, as the cache key the unpacked copy is filed under.
 *
 * Taken here because the build is the one place that can afford it — hashing 18 MB
 * costs about 20 ms once, against paying it on every launch of every copy of the
 * app. Truncated to 16 hex digits: this names a directory, and the full 64 buys
 * nothing against an accident.
 */
async function hashEngine(path: string): Promise<string> {
  const bytes = await Bun.file(path).arrayBuffer();
  const digest = new Bun.CryptoHasher("sha256").update(bytes).digest("hex");
  return digest.slice(0, 16);
}

/**
 * The generated wrapper — everything that must happen before the app's first line.
 *
 * `await` before the dynamic import, not a top-level side effect: unpacking is I/O
 * and the app's own module graph must not start loading until the loader knows
 * where the engine is. A static import would have been hoisted above this.
 */
function wrapperSource(
  enginePath: string,
  hash: string,
  workerBundle: string,
  entry: string,
): string {
  return `// GENERATED by \`dziri build\`. Not checked in; rewritten every build.
//
// Holds the two imports that have to name machine-specific paths as literals,
// which is the whole reason this file is generated rather than checked in.

import embeddedEngine from ${JSON.stringify(enginePath)} with { type: "file" };
import embeddedWorker from ${JSON.stringify(workerBundle)} with { type: "file" };
import { useEmbeddedEngine } from "${PACKAGE}/engine/embed.ts";
import { useWorkerBundle } from "${PACKAGE}/host/main.ts";

// Both before the app's first line. The engine has to be a real file for
// \`dlopen\`; the app thread has to be the pre-bundled JavaScript rather than the
// \`.ts\` the generated entry would compute, because the standalone runtime does
// not transpile what it loads out of its own virtual filesystem.
await useEmbeddedEngine(embeddedEngine, ${JSON.stringify(hash)});
useWorkerBundle(embeddedWorker);

await import(${JSON.stringify(entry)});
`;
}

/**
 * Turns the executable into a Windows GUI app, so launching it opens no console.
 *
 * A desktop app that pops a black terminal behind its window is not a desktop
 * app, and this is the last thing standing between `dziri build` and something
 * shippable.
 *
 * **Bun's own `--windows-hide-console` does not do it.** Measured: a binary built
 * with that flag still reports subsystem 3 in its PE header, which is the field
 * the loader reads to decide whether to give the process a console. Whatever the
 * flag does, it happens after the console already exists.
 *
 * So the field is written directly. It is one 16-bit value in the optional
 * header, at a fixed offset from the PE signature whose own location is at 0x3c —
 * the same edit every "make this a GUI app" tool performs, and it changes nothing
 * else about the file.
 *
 * The cost, stated because it is real: a GUI-subsystem process has no standard
 * output. `console.log` from the packaged app goes nowhere. That is correct for
 * the shipped thing and wrong for a diagnostic run, which is what `--console` is
 * for.
 */
async function hideConsole(exe: string): Promise<void> {
  const bytes = new Uint8Array(await Bun.file(exe).arrayBuffer());
  const view = new DataView(bytes.buffer);

  /** `e_lfanew` — where the PE header starts. */
  const pe = view.getUint32(0x3c, true);

  // "PE\0\0". If this is not here the file is not what we think it is, and
  // writing two bytes into it on a guess is how you produce a corrupt binary.
  if (view.getUint32(pe, true) !== 0x0000_4550) return;

  /** `IMAGE_OPTIONAL_HEADER.Subsystem`, 0x5c past the signature in both PE32 and PE32+. */
  const at = pe + 0x5c;
  const CONSOLE = 3;
  const GUI = 2;

  if (view.getUint16(at, true) !== CONSOLE) return;
  view.setUint16(at, GUI, true);
  await Bun.write(exe, bytes);
}

export async function buildApp(options: BuildOptions): Promise<BuildResult> {
  const started = performance.now();
  const projectDir = resolve(options.projectDir);

  for (const one of await compileProject({ projectDir })) {
    console.log(describe(one, projectDir));
  }

  const enginePath = findEngine();
  const engineBytes = statSync(enginePath).size;
  const engineHash = await hashEngine(enginePath);

  const outDir = join(projectDir, options.outDir ?? "dist");
  const name = options.name ?? basename(projectDir);
  const outFile = join(outDir, process.platform === "win32" ? `${name}.exe` : name);

  /* Beside the output rather than in the system temp dir, because the wrapper's
     `import "./…/entry.gen.ts"` is resolved relative to it — and a relative
     specifier that crosses drives is not expressible on Windows. */
  const scratch = join(outDir, ".dziri-build");
  mkdirSync(scratch, { recursive: true });

  /**
   * The app thread, bundled to JavaScript first and separately.
   *
   * Two builds rather than one because the two threads are two module graphs
   * that never meet: the engine thread imports no application code, and the app
   * thread imports no engine handle. Bundling them together would put the whole
   * application in the executable twice — and the app thread has to be plain
   * JavaScript regardless, since the standalone runtime loads an embedded module
   * without transpiling it.
   */
  /* `outdir` + `naming`, not `outfile`: the latter is a CLI flag and `Bun.build`
     rejects it, which surfaced as a bare "Bundle failed" with nothing else said. */
  const workerBundle = join(scratch, "worker.js");
  const workerBuild = await Bun.build({
    entrypoints: [join(projectDir, WORKER_FILE)],
    plugins: reactiveEnabled() ? [reactivePlugin] : [],
    target: "bun",
    minify: !options.noMinify,
    outdir: scratch,
    naming: "worker.js",
    // Bun 1.4: esbuild-compatible bundle metadata. Written beside the bundle so
    // "the binary grew — which module did it" has an answer instead of a guess.
    metafile: true,
  });

  if (!workerBuild.success) {
    throw new Error(
      `bundling the app thread failed.\n\n` +
        workerBuild.logs.map((l) => `  ${String(l)}`).join("\n"),
    );
  }

  const workerMeta = (workerBuild as { metafile?: unknown }).metafile;
  if (workerMeta !== undefined) {
    await Bun.write(join(scratch, "worker-meta.json"), JSON.stringify(workerMeta, null, 2));
  }

  const wrapper = join(scratch, "entry.ts");
  await Bun.write(
    wrapper,
    wrapperSource(enginePath, engineHash, workerBundle, join(projectDir, ENTRY_FILE)),
  );

  /**
   * `Bun.build`, not the `bun build --compile` CLI, and the difference is the
   * plugin list.
   *
   * The reactive rewrite is a bundler concern here: `windows/**` modules go into
   * the executable and their bare signal reads have to be rewritten on the way in.
   * A `plugin()` registration reaches the module loader only, so the CLI produced a
   * binary containing a raw `todos.filter(…)` — a method on a signal object, which
   * does not exist — and it threw on the first frame while `dziri dev` was fine.
   *
   * `compile` is undocumented in `@types/bun` 1.3.14 but implemented; the cast is
   * for the types, not for the behaviour.
   */
  const result = await Bun.build({
    entrypoints: [wrapper],
    plugins: reactiveEnabled() ? [reactivePlugin] : [],
    minify: !options.noMinify,
    metafile: true,
    /* Bytecode needs the format said out loud: ESM bytecode is new in Bun 1.4,
       and without `format` the bundler falls back to CJS and rejects the
       wrapper's top-level `await`. The binary starts without a parse step for
       the entry graph — on the demo that is noise (~10ms of a ~240ms boot,
       which is mostly SDL and Skia), but it scales with the app's JS while the
       size cost stays ~0.2% — and the first frame is byte-identical. */
    format: "esm",
    bytecode: true,
    compile: { outfile: outFile },
  } as Parameters<typeof Bun.build>[0]);

  if (!result.success) {
    throw new Error(
      `bundling failed.\n\n${result.logs.map((l) => `  ${String(l)}`).join("\n")}`,
    );
  }

  const appMeta = (result as { metafile?: unknown }).metafile;
  if (appMeta !== undefined) {
    await Bun.write(join(scratch, "app-meta.json"), JSON.stringify(appMeta, null, 2));
  }

  if (process.platform === "win32" && !options.console) await hideConsole(outFile);

  if (!options.keepScratch) {
    await Bun.file(wrapper)
      .delete()
      .catch(() => {});
  }

  return {
    outFile,
    bytes: statSync(outFile).size,
    engineBytes,
    engineHash,
    elapsed: performance.now() - started,
  };
}
