// GENERATED by scripts/gen-protocol.ts from src/protocol/schema.ts
// Do not edit.

//! Shared-memory layout. Struct-of-arrays: every field is its own contiguous
//! span, so a style patch touches one array and paint reads stay monomorphic.

/// Bumped on any schema change. The engine refuses to start on a mismatch rather
/// than rendering garbage.
pub const PROTOCOL_VERSION: u32 = 1;

/// Structural fingerprint of every table, field name and element type, in order.
///
/// The version says "the protocol changed on purpose"; this says "the two sides
/// were generated from the same schema". A field rename, a reorder of two
/// same-width fields, or an `i32` retyped to `f32` all leave the field count
/// untouched — so a handshake that counts fields cannot see them, and the result
/// is one side reading the other's bytes as a different type at a valid offset.
pub const SCHEMA_HASH: u32 = 0x24ce8fc9;

pub const TABLE_COUNT: usize = 6;

/// Field count of the widest table. The (table, field) lookup index uses this as
/// its stride, so it cannot be out-grown by adding fields to a table.
pub const MAX_FIELD_COUNT: usize = 48;
pub const TABLE_NAMES: [&str; TABLE_COUNT] = ["nodes", "styles", "states", "lists", "layout", "strings"];

#[repr(u32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum Table {
    Nodes = 0,
    Styles = 1,
    States = 2,
    Lists = 3,
    Layout = 4,
    Strings = 5,
}

impl Table {
    pub fn field_count(self) -> usize {
        FIELD_COUNTS[self as usize]
    }
}

pub const FIELD_COUNTS: [usize; TABLE_COUNT] = [nodes::FIELD_COUNT, styles::FIELD_COUNT, states::FIELD_COUNT, lists::FIELD_COUNT, layout::FIELD_COUNT, strings::FIELD_COUNT];

/// How each table is sized, so the engine can turn a capacity request into byte
/// spans without a hand-written mapping that could drift from the schema.
pub const SIZED_BY: [&str; TABLE_COUNT] = ["nodes", "styles", "own", "own", "nodes", "strings"];

/// Element size per field, indexed by table. Empty for an unknown table.
pub fn elem_sizes(table: usize) -> &'static [usize] {
    match table {
        0 => &nodes::ELEM_SIZES,
        1 => &styles::ELEM_SIZES,
        2 => &states::ELEM_SIZES,
        3 => &lists::ELEM_SIZES,
        4 => &layout::ELEM_SIZES,
        5 => &strings::ELEM_SIZES,
        _ => &[],
    }
}

/// Field names per table, for descriptor assertions and diagnostics.
pub fn field_names(table: usize) -> &'static [&'static str] {
    match table {
        0 => &nodes::FIELD_NAMES,
        1 => &styles::FIELD_NAMES,
        2 => &states::FIELD_NAMES,
        3 => &lists::FIELD_NAMES,
        4 => &layout::FIELD_NAMES,
        5 => &strings::FIELD_NAMES,
        _ => &[],
    }
}

/// Tree structure and per-node indices.
pub mod nodes {
    /// Field indices, in descriptor order.
    pub const KIND: usize = 0;
    pub const STYLE: usize = 1;
    pub const TEXT: usize = 2;
    pub const PARENT: usize = 3;
    pub const FIRST_CHILD: usize = 4;
    pub const NEXT_SIBLING: usize = 5;
    pub const LIST: usize = 6;
    pub const HIDDEN: usize = 7;
    pub const FLAGS: usize = 8;

    pub const FIELD_COUNT: usize = 9;
    pub const ELEM_SIZES: [usize; FIELD_COUNT] = [1, 2, 4, 4, 4, 4, 2, 1, 1];
    pub const FIELD_NAMES: [&str; FIELD_COUNT] = ["kind", "style", "text", "parent", "firstChild", "nextSibling", "list", "hidden", "flags"];
}

/// Resolved style values. Patches write field values in place.
pub mod styles {
    /// Field indices, in descriptor order.
    pub const BG: usize = 0;
    pub const FG: usize = 1;
    pub const BORDER_COLOR: usize = 2;
    pub const BORDER_WIDTH: usize = 3;
    pub const RADIUS: usize = 4;
    pub const PAD_TOP: usize = 5;
    pub const PAD_RIGHT: usize = 6;
    pub const PAD_BOTTOM: usize = 7;
    pub const PAD_LEFT: usize = 8;
    pub const MARGIN_TOP: usize = 9;
    pub const MARGIN_RIGHT: usize = 10;
    pub const MARGIN_BOTTOM: usize = 11;
    pub const MARGIN_LEFT: usize = 12;
    pub const DISPLAY: usize = 13;
    pub const FLEX_DIRECTION: usize = 14;
    pub const FLEX_WRAP: usize = 15;
    pub const JUSTIFY_CONTENT: usize = 16;
    pub const ALIGN_ITEMS: usize = 17;
    pub const ALIGN_SELF: usize = 18;
    pub const JUSTIFY_ITEMS: usize = 19;
    pub const JUSTIFY_SELF: usize = 20;
    pub const FLEX_GROW: usize = 21;
    pub const FLEX_SHRINK: usize = 22;
    pub const FLEX_BASIS: usize = 23;
    pub const GAP_ROW: usize = 24;
    pub const GAP_COLUMN: usize = 25;
    pub const GRID_COLUMNS: usize = 26;
    pub const GRID_ROWS: usize = 27;
    pub const GRID_COLUMN_START: usize = 28;
    pub const GRID_COLUMN_SPAN: usize = 29;
    pub const GRID_ROW_START: usize = 30;
    pub const GRID_ROW_SPAN: usize = 31;
    pub const WIDTH: usize = 32;
    pub const HEIGHT: usize = 33;
    pub const MIN_WIDTH: usize = 34;
    pub const MIN_HEIGHT: usize = 35;
    pub const MAX_WIDTH: usize = 36;
    pub const MAX_HEIGHT: usize = 37;
    pub const ASPECT_RATIO: usize = 38;
    pub const POSITION: usize = 39;
    pub const INSET_TOP: usize = 40;
    pub const INSET_RIGHT: usize = 41;
    pub const INSET_BOTTOM: usize = 42;
    pub const INSET_LEFT: usize = 43;
    pub const FONT_SIZE: usize = 44;
    pub const FONT_WEIGHT: usize = 45;
    pub const LINE_CLAMP: usize = 46;
    pub const OVERFLOW: usize = 47;

    pub const FIELD_COUNT: usize = 48;
    pub const ELEM_SIZES: [usize; FIELD_COUNT] = [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 1, 1, 1, 1, 1, 1, 1, 1, 4, 4, 4, 4, 4, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 4, 4, 4, 1, 4, 4, 4, 4, 4, 2, 2, 1];
    pub const FIELD_NAMES: [&str; FIELD_COUNT] = ["bg", "fg", "borderColor", "borderWidth", "radius", "padTop", "padRight", "padBottom", "padLeft", "marginTop", "marginRight", "marginBottom", "marginLeft", "display", "flexDirection", "flexWrap", "justifyContent", "alignItems", "alignSelf", "justifyItems", "justifySelf", "flexGrow", "flexShrink", "flexBasis", "gapRow", "gapColumn", "gridColumns", "gridRows", "gridColumnStart", "gridColumnSpan", "gridRowStart", "gridRowSpan", "width", "height", "minWidth", "minHeight", "maxWidth", "maxHeight", "aspectRatio", "position", "insetTop", "insetRight", "insetBottom", "insetLeft", "fontSize", "fontWeight", "lineClamp", "overflow"];
}

/// Sparse interaction-state styles, sorted by node for binary search.
pub mod states {
    /// Field indices, in descriptor order.
    pub const NODE: usize = 0;
    pub const HOVER: usize = 1;
    pub const ACTIVE: usize = 2;
    pub const FOCUS: usize = 3;

    pub const FIELD_COUNT: usize = 4;
    pub const ELEM_SIZES: [usize; FIELD_COUNT] = [4, 4, 4, 4];
    pub const FIELD_NAMES: [&str; FIELD_COUNT] = ["node", "hover", "active", "focus"];
}

/// List arenas: homogeneous item subtrees addressed by stride.
pub mod lists {
    /// Field indices, in descriptor order.
    pub const NODE: usize = 0;
    pub const ARENA_START: usize = 1;
    pub const STRIDE: usize = 2;
    pub const CAPACITY: usize = 3;
    pub const ACTIVE: usize = 4;

    pub const FIELD_COUNT: usize = 5;
    pub const ELEM_SIZES: [usize; FIELD_COUNT] = [4, 4, 4, 4, 4];
    pub const FIELD_NAMES: [&str; FIELD_COUNT] = ["node", "arenaStart", "stride", "capacity", "active"];
}

/// Final bounds per node, written by the engine.
pub mod layout {
    /// Field indices, in descriptor order.
    pub const X: usize = 0;
    pub const Y: usize = 1;
    pub const WIDTH: usize = 2;
    pub const HEIGHT: usize = 3;

    pub const FIELD_COUNT: usize = 4;
    pub const ELEM_SIZES: [usize; FIELD_COUNT] = [4, 4, 4, 4];
    pub const FIELD_NAMES: [&str; FIELD_COUNT] = ["x", "y", "width", "height"];
}

/// Slot table into the UTF-8 arena.
pub mod strings {
    /// Field indices, in descriptor order.
    pub const OFFSET: usize = 0;
    pub const LENGTH: usize = 1;

    pub const FIELD_COUNT: usize = 2;
    pub const ELEM_SIZES: [usize; FIELD_COUNT] = [4, 4];
    pub const FIELD_NAMES: [&str; FIELD_COUNT] = ["offset", "length"];
}

/// Node flag bits.
pub mod flags {
    pub const INTERACTIVE: u8 = 1 << 0;
    pub const MEASURABLE: u8 = 1 << 1;
}

/// What a node is. `nodes.kind`.
pub mod node_kind {
    pub const BOX: u8 = 0;
    pub const TEXT: u8 = 1;
    pub const BUTTON: u8 = 2;
    pub const LIST: u8 = 3;
}

/// `styles.display`. `NONE` excludes the subtree from layout.
pub mod display {
    pub const FLEX: u8 = 0;
    pub const GRID: u8 = 1;
    pub const BLOCK: u8 = 2;
    pub const NONE: u8 = 3;
}

/// `styles.flexDirection`.
pub mod flex_direction {
    pub const ROW: u8 = 0;
    pub const COLUMN: u8 = 1;
    pub const ROW_REVERSE: u8 = 2;
    pub const COLUMN_REVERSE: u8 = 3;
}

/// `styles.flexWrap`.
pub mod flex_wrap {
    pub const NO_WRAP: u8 = 0;
    pub const WRAP: u8 = 1;
    pub const WRAP_REVERSE: u8 = 2;
}

/// `styles.justifyContent`. CSS `align-content` values, per Taffy.
pub mod justify {
    pub const FLEX_START: u8 = 0;
    pub const CENTER: u8 = 1;
    pub const FLEX_END: u8 = 2;
    pub const SPACE_BETWEEN: u8 = 3;
    pub const SPACE_AROUND: u8 = 4;
    pub const SPACE_EVENLY: u8 = 5;
    pub const UNSET: u8 = 255;
}

/// `styles.alignItems` / `alignSelf` / `justifyItems` / `justifySelf`.
pub mod align {
    pub const FLEX_START: u8 = 0;
    pub const CENTER: u8 = 1;
    pub const FLEX_END: u8 = 2;
    pub const STRETCH: u8 = 3;
    pub const BASELINE: u8 = 4;
    pub const UNSET: u8 = 255;
}

/// `styles.position`.
pub mod position {
    pub const RELATIVE: u8 = 0;
    pub const ABSOLUTE: u8 = 1;
}

/// `styles.overflow`.
pub mod overflow {
    pub const VISIBLE: u8 = 0;
    pub const HIDDEN: u8 = 1;
    pub const ELLIPSIS: u8 = 2;
    pub const SCROLL: u8 = 3;
}

/// Engine → Bun. Drained after `tick()`; `0` means the queue is empty.
pub mod event_kind {
    pub const NONE: u32 = 0;
    pub const QUIT: u32 = 1;
    pub const RESIZE: u32 = 2;
    pub const MOUSE_MOVE: u32 = 3;
    pub const MOUSE_DOWN: u32 = 4;
    pub const MOUSE_UP: u32 = 5;
    pub const CLICK: u32 = 6;
    pub const KEY_DOWN: u32 = 7;
    pub const TEXT_INPUT: u32 = 8;
    pub const FOCUS: u32 = 9;
}

/// Return code of every FFI entry point. Negative is failure, and the detail is in `dziri_last_error`.
pub mod status {
    pub const OK: i32 = 0;
    pub const PANIC: i32 = -1;
    pub const INVALID_HANDLE: i32 = -2;
    pub const INVALID_ARGUMENT: i32 = -3;
    pub const PROTOCOL_MISMATCH: i32 = -4;
    pub const CAPACITY: i32 = -5;
    pub const SDL: i32 = -6;
    pub const SKIA: i32 = -7;
    pub const LAYOUT: i32 = -8;
    pub const POISONED: i32 = -9;
}
