// GENERATED by scripts/gen-protocol.ts from src/protocol/schema.ts
// Do not edit.

//! Shared-memory layout. Struct-of-arrays: every field is its own contiguous
//! span, so a style patch touches one array and paint reads stay monomorphic.

/// Bumped on any schema change. The engine refuses to start on a mismatch rather
/// than rendering garbage.
pub const PROTOCOL_VERSION: u32 = 16;

/// Structural fingerprint of every table, field name and element type, in order.
///
/// The version says "the protocol changed on purpose"; this says "the two sides
/// were generated from the same schema". A field rename, a reorder of two
/// same-width fields, or an `i32` retyped to `f32` all leave the field count
/// untouched — so a handshake that counts fields cannot see them, and the result
/// is one side reading the other's bytes as a different type at a valid offset.
pub const SCHEMA_HASH: u32 = 0xbbe19d0e;

pub const TABLE_COUNT: usize = 11;

/// Field count of the widest table. The (table, field) lookup index uses this as
/// its stride, so it cannot be out-grown by adding fields to a table.
pub const MAX_FIELD_COUNT: usize = 80;
pub const TABLE_NAMES: [&str; TABLE_COUNT] = [
    "nodes",
    "styles",
    "variants",
    "variantSlots",
    "media",
    "lists",
    "tweens",
    "keyframes",
    "controls",
    "layout",
    "strings",
];

#[repr(u32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum Table {
    Nodes = 0,
    Styles = 1,
    Variants = 2,
    VariantSlots = 3,
    Media = 4,
    Lists = 5,
    Tweens = 6,
    Keyframes = 7,
    Controls = 8,
    Layout = 9,
    Strings = 10,
}

impl Table {
    pub fn field_count(self) -> usize {
        FIELD_COUNTS[self as usize]
    }
}

pub const FIELD_COUNTS: [usize; TABLE_COUNT] = [
    nodes::FIELD_COUNT,
    styles::FIELD_COUNT,
    variants::FIELD_COUNT,
    variant_slots::FIELD_COUNT,
    media::FIELD_COUNT,
    lists::FIELD_COUNT,
    tweens::FIELD_COUNT,
    keyframes::FIELD_COUNT,
    controls::FIELD_COUNT,
    layout::FIELD_COUNT,
    strings::FIELD_COUNT,
];

/// How each table is sized, so the engine can turn a capacity request into byte
/// spans without a hand-written mapping that could drift from the schema.
pub const SIZED_BY: [&str; TABLE_COUNT] = [
    "nodes", "styles", "own", "own", "own", "own", "own", "own", "own", "nodes", "strings",
];

/// Element size per field, indexed by table. Empty for an unknown table.
pub fn elem_sizes(table: usize) -> &'static [usize] {
    match table {
        0 => &nodes::ELEM_SIZES,
        1 => &styles::ELEM_SIZES,
        2 => &variants::ELEM_SIZES,
        3 => &variant_slots::ELEM_SIZES,
        4 => &media::ELEM_SIZES,
        5 => &lists::ELEM_SIZES,
        6 => &tweens::ELEM_SIZES,
        7 => &keyframes::ELEM_SIZES,
        8 => &controls::ELEM_SIZES,
        9 => &layout::ELEM_SIZES,
        10 => &strings::ELEM_SIZES,
        _ => &[],
    }
}

/// Field names per table, for descriptor assertions and diagnostics.
pub fn field_names(table: usize) -> &'static [&'static str] {
    match table {
        0 => &nodes::FIELD_NAMES,
        1 => &styles::FIELD_NAMES,
        2 => &variants::FIELD_NAMES,
        3 => &variant_slots::FIELD_NAMES,
        4 => &media::FIELD_NAMES,
        5 => &lists::FIELD_NAMES,
        6 => &tweens::FIELD_NAMES,
        7 => &keyframes::FIELD_NAMES,
        8 => &controls::FIELD_NAMES,
        9 => &layout::FIELD_NAMES,
        10 => &strings::FIELD_NAMES,
        _ => &[],
    }
}

/// Tree structure and per-node indices.
pub mod nodes {
    /// Field indices, in descriptor order.
    pub const KIND: usize = 0;
    pub const STYLE: usize = 1;
    pub const TEXT: usize = 2;
    pub const PARENT: usize = 3;
    pub const FIRST_CHILD: usize = 4;
    pub const NEXT_SIBLING: usize = 5;
    pub const LIST: usize = 6;
    pub const HIDDEN: usize = 7;
    pub const FLAGS: usize = 8;
    pub const ACTIVATES: usize = 9;

    pub const FIELD_COUNT: usize = 10;
    pub const ELEM_SIZES: [usize; FIELD_COUNT] = [1, 2, 4, 4, 4, 4, 2, 1, 1, 4];
    pub const FIELD_NAMES: [&str; FIELD_COUNT] = [
        "kind",
        "style",
        "text",
        "parent",
        "firstChild",
        "nextSibling",
        "list",
        "hidden",
        "flags",
        "activates",
    ];
}

/// Resolved style values. Patches write field values in place.
pub mod styles {
    /// Field indices, in descriptor order.
    pub const BG: usize = 0;
    pub const FG: usize = 1;
    pub const BORDER_COLOR: usize = 2;
    pub const BORDER_WIDTH: usize = 3;
    pub const RADIUS_TOP_LEFT: usize = 4;
    pub const RADIUS_TOP_RIGHT: usize = 5;
    pub const RADIUS_BOTTOM_RIGHT: usize = 6;
    pub const RADIUS_BOTTOM_LEFT: usize = 7;
    pub const RING_OUTER_WIDTH: usize = 8;
    pub const RING_OUTER_COLOR: usize = 9;
    pub const RING_INNER_WIDTH: usize = 10;
    pub const RING_INNER_COLOR: usize = 11;
    pub const RING_INSET_WIDTH: usize = 12;
    pub const RING_INSET_COLOR: usize = 13;
    pub const PAD_TOP: usize = 14;
    pub const PAD_RIGHT: usize = 15;
    pub const PAD_BOTTOM: usize = 16;
    pub const PAD_LEFT: usize = 17;
    pub const MARGIN_TOP: usize = 18;
    pub const MARGIN_RIGHT: usize = 19;
    pub const MARGIN_BOTTOM: usize = 20;
    pub const MARGIN_LEFT: usize = 21;
    pub const DISPLAY: usize = 22;
    pub const FLEX_DIRECTION: usize = 23;
    pub const FLEX_WRAP: usize = 24;
    pub const JUSTIFY_CONTENT: usize = 25;
    pub const ALIGN_ITEMS: usize = 26;
    pub const ALIGN_SELF: usize = 27;
    pub const JUSTIFY_ITEMS: usize = 28;
    pub const JUSTIFY_SELF: usize = 29;
    pub const FLEX_GROW: usize = 30;
    pub const FLEX_SHRINK: usize = 31;
    pub const FLEX_BASIS: usize = 32;
    pub const GAP_ROW: usize = 33;
    pub const GAP_COLUMN: usize = 34;
    pub const GRID_COLUMNS: usize = 35;
    pub const GRID_ROWS: usize = 36;
    pub const GRID_COLUMN_START: usize = 37;
    pub const GRID_COLUMN_SPAN: usize = 38;
    pub const GRID_ROW_START: usize = 39;
    pub const GRID_ROW_SPAN: usize = 40;
    pub const WIDTH: usize = 41;
    pub const HEIGHT: usize = 42;
    pub const MIN_WIDTH: usize = 43;
    pub const MIN_HEIGHT: usize = 44;
    pub const MAX_WIDTH: usize = 45;
    pub const MAX_HEIGHT: usize = 46;
    pub const ASPECT_RATIO: usize = 47;
    pub const POSITION: usize = 48;
    pub const INSET_TOP: usize = 49;
    pub const INSET_RIGHT: usize = 50;
    pub const INSET_BOTTOM: usize = 51;
    pub const INSET_LEFT: usize = 52;
    pub const FONT_SIZE: usize = 53;
    pub const FONT_WEIGHT: usize = 54;
    pub const LINE_CLAMP: usize = 55;
    pub const OVERFLOW_X: usize = 56;
    pub const OVERFLOW_Y: usize = 57;
    pub const SCROLLBAR_WIDTH: usize = 58;
    pub const SCROLLBAR_THUMB: usize = 59;
    pub const SCROLLBAR_TRACK: usize = 60;
    pub const ACCENT_COLOR: usize = 61;
    pub const CARET_COLOR: usize = 62;
    pub const APPEARANCE: usize = 63;
    pub const OPACITY: usize = 64;
    pub const TRANSLATE_X: usize = 65;
    pub const TRANSLATE_Y: usize = 66;
    pub const TRANSLATE_PERCENT_X: usize = 67;
    pub const TRANSLATE_PERCENT_Y: usize = 68;
    pub const ROTATE: usize = 69;
    pub const SCALE_X: usize = 70;
    pub const SCALE_Y: usize = 71;
    pub const SKEW_X: usize = 72;
    pub const SKEW_Y: usize = 73;
    pub const TRANSFORM_ORIGIN_PERCENT_X: usize = 74;
    pub const TRANSFORM_ORIGIN_PERCENT_Y: usize = 75;
    pub const TRANSFORM_ORIGIN_X: usize = 76;
    pub const TRANSFORM_ORIGIN_Y: usize = 77;
    pub const TRANSITION: usize = 78;
    pub const ANIMATION: usize = 79;

    pub const FIELD_COUNT: usize = 80;
    pub const ELEM_SIZES: [usize; FIELD_COUNT] = [
        4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 1, 1, 1, 1, 1, 1, 1, 1,
        4, 4, 4, 4, 4, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 4, 4, 4, 1, 4, 4, 4, 4, 4, 2, 2, 1, 1, 1, 4,
        4, 4, 4, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 2,
    ];
    pub const FIELD_NAMES: [&str; FIELD_COUNT] = [
        "bg",
        "fg",
        "borderColor",
        "borderWidth",
        "radiusTopLeft",
        "radiusTopRight",
        "radiusBottomRight",
        "radiusBottomLeft",
        "ringOuterWidth",
        "ringOuterColor",
        "ringInnerWidth",
        "ringInnerColor",
        "ringInsetWidth",
        "ringInsetColor",
        "padTop",
        "padRight",
        "padBottom",
        "padLeft",
        "marginTop",
        "marginRight",
        "marginBottom",
        "marginLeft",
        "display",
        "flexDirection",
        "flexWrap",
        "justifyContent",
        "alignItems",
        "alignSelf",
        "justifyItems",
        "justifySelf",
        "flexGrow",
        "flexShrink",
        "flexBasis",
        "gapRow",
        "gapColumn",
        "gridColumns",
        "gridRows",
        "gridColumnStart",
        "gridColumnSpan",
        "gridRowStart",
        "gridRowSpan",
        "width",
        "height",
        "minWidth",
        "minHeight",
        "maxWidth",
        "maxHeight",
        "aspectRatio",
        "position",
        "insetTop",
        "insetRight",
        "insetBottom",
        "insetLeft",
        "fontSize",
        "fontWeight",
        "lineClamp",
        "overflowX",
        "overflowY",
        "scrollbarWidth",
        "scrollbarThumb",
        "scrollbarTrack",
        "accentColor",
        "caretColor",
        "appearance",
        "opacity",
        "translateX",
        "translateY",
        "translatePercentX",
        "translatePercentY",
        "rotate",
        "scaleX",
        "scaleY",
        "skewX",
        "skewY",
        "transformOriginPercentX",
        "transformOriginPercentY",
        "transformOriginX",
        "transformOriginY",
        "transition",
        "animation",
    ];

    /// Whether a change to this field can move a box.
    ///
    /// `false` means paint reads it and layout does not, so a commit that
    /// touches only such fields needs no Taffy work at all — the repaint that
    /// every non-empty commit schedules is the entire response. A colour-only
    /// theme patch is the case this exists for.
    pub const LAYOUT_AFFECTING: [bool; FIELD_COUNT] = [
        false, false, false, true, false, false, false, false, false, false, false, false, false,
        false, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        false, false, false, false, false, false, false, false, false, false, false, false, false,
        false, false, false, false, false, false, false, false, false,
    ];

    /// How each field is interpolated partway through a tween.
    ///
    /// `interp::NONE` means discrete — every enum, and the two tween references
    /// themselves. See the `Interp` doc comment in schema.ts for why a colour is
    /// not a number here.
    pub const INTERP: [u8; FIELD_COUNT] = [
        2, 2, 2, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2,
        2, 2, 2, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
    ];

    /// Which bit of a tween's `mask` each field owns, or 255 for "not animatable".
    ///
    /// Dense over the animatable fields rather than sparse over all of them, so a
    /// mask stays one `u32` while the table grows. The numbering is derived from
    /// field order, which is why `interp` is in `SCHEMA_HASH`: renumbering it on
    /// one side only would animate a neighbouring property.
    pub const ANIM_BIT: [u8; FIELD_COUNT] = [
        0, 1, 2, 255, 3, 4, 5, 6, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
        255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
        255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
        255, 255, 7, 8, 9, 10, 255, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 255,
        255,
    ];

    /// The field index each mask bit refers to, low bit first — `ANIM_BIT` inverted.
    ///
    /// The engine walks a mask's set bits and needs the field for each; searching
    /// `ANIM_BIT` for a value would be a linear scan per bit per animating node.
    pub const ANIM_FIELDS: [usize; 25] = [
        0, 1, 2, 4, 5, 6, 7, 59, 60, 61, 62, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
    ];
}

/// Per-node predicate mask and where that node's style run begins.
pub mod variants {
    /// Field indices, in descriptor order.
    pub const NODE: usize = 0;
    pub const MASK: usize = 1;
    pub const RUN_START: usize = 2;

    pub const FIELD_COUNT: usize = 3;
    pub const ELEM_SIZES: [usize; FIELD_COUNT] = [4, 4, 4];
    pub const FIELD_NAMES: [&str; FIELD_COUNT] = ["node", "mask", "runStart"];
}

/// Dense style-slot runs, indexed by compacted live predicate bits.
pub mod variant_slots {
    /// Field indices, in descriptor order.
    pub const STYLE: usize = 0;

    pub const FIELD_COUNT: usize = 1;
    pub const ELEM_SIZES: [usize; FIELD_COUNT] = [2];
    pub const FIELD_NAMES: [&str; FIELD_COUNT] = ["style"];
}

/// Global predicates the engine re-evaluates from the surface size each frame.
pub mod media {
    /// Field indices, in descriptor order.
    pub const BIT: usize = 0;
    pub const KIND: usize = 1;
    pub const VALUE: usize = 2;

    pub const FIELD_COUNT: usize = 3;
    pub const ELEM_SIZES: [usize; FIELD_COUNT] = [4, 1, 4];
    pub const FIELD_NAMES: [&str; FIELD_COUNT] = ["bit", "kind", "value"];
}

/// List arenas: homogeneous item subtrees addressed by stride.
pub mod lists {
    /// Field indices, in descriptor order.
    pub const CONTAINER: usize = 0;
    pub const ANCHOR_PREV: usize = 1;
    pub const ANCHOR_NEXT: usize = 2;
    pub const ARENA_START: usize = 3;
    pub const STRIDE: usize = 4;
    pub const CAPACITY: usize = 5;
    pub const ACTIVE: usize = 6;

    pub const FIELD_COUNT: usize = 7;
    pub const ELEM_SIZES: [usize; FIELD_COUNT] = [4, 4, 4, 4, 4, 4, 4];
    pub const FIELD_NAMES: [&str; FIELD_COUNT] = [
        "container",
        "anchorPrev",
        "anchorNext",
        "arenaStart",
        "stride",
        "capacity",
        "active",
    ];
}

/// Interned transition and animation timing. One row per distinct spec.
pub mod tweens {
    /// Field indices, in descriptor order.
    pub const MASK: usize = 0;
    pub const DURATION: usize = 1;
    pub const DELAY: usize = 2;
    pub const ITERATIONS: usize = 3;
    pub const FIRST_SEGMENT: usize = 4;
    pub const SEGMENT_COUNT: usize = 5;
    pub const EASING: usize = 6;
    pub const EASE_A: usize = 7;
    pub const EASE_B: usize = 8;
    pub const EASE_C: usize = 9;
    pub const EASE_D: usize = 10;

    pub const FIELD_COUNT: usize = 11;
    pub const ELEM_SIZES: [usize; FIELD_COUNT] = [4, 4, 4, 4, 4, 2, 1, 4, 4, 4, 4];
    pub const FIELD_NAMES: [&str; FIELD_COUNT] = [
        "mask",
        "duration",
        "delay",
        "iterations",
        "firstSegment",
        "segmentCount",
        "easing",
        "easeA",
        "easeB",
        "easeC",
        "easeD",
    ];
}

/// Per-animation keyframe list: offset, resolved style row, and segment easing.
pub mod keyframes {
    /// Field indices, in descriptor order.
    pub const STYLE: usize = 0;
    pub const OFFSET: usize = 1;
    pub const EASING: usize = 2;
    pub const EASE_A: usize = 3;
    pub const EASE_B: usize = 4;
    pub const EASE_C: usize = 5;
    pub const EASE_D: usize = 6;

    pub const FIELD_COUNT: usize = 7;
    pub const ELEM_SIZES: [usize; FIELD_COUNT] = [2, 4, 1, 4, 4, 4, 4];
    pub const FIELD_NAMES: [&str; FIELD_COUNT] = [
        "style", "offset", "easing", "easeA", "easeB", "easeC", "easeD",
    ];
}

/// Form controls: kind, radio group, and authored initial state.
pub mod controls {
    /// Field indices, in descriptor order.
    pub const NODE: usize = 0;
    pub const KIND: usize = 1;
    pub const GROUP: usize = 2;
    pub const FLAGS: usize = 3;

    pub const FIELD_COUNT: usize = 4;
    pub const ELEM_SIZES: [usize; FIELD_COUNT] = [4, 1, 4, 1];
    pub const FIELD_NAMES: [&str; FIELD_COUNT] = ["node", "kind", "group", "flags"];
}

/// Final bounds per node, written by the engine.
pub mod layout {
    /// Field indices, in descriptor order.
    pub const X: usize = 0;
    pub const Y: usize = 1;
    pub const WIDTH: usize = 2;
    pub const HEIGHT: usize = 3;

    pub const FIELD_COUNT: usize = 4;
    pub const ELEM_SIZES: [usize; FIELD_COUNT] = [4, 4, 4, 4];
    pub const FIELD_NAMES: [&str; FIELD_COUNT] = ["x", "y", "width", "height"];
}

/// Slot table into the UTF-8 arena.
pub mod strings {
    /// Field indices, in descriptor order.
    pub const OFFSET: usize = 0;
    pub const LENGTH: usize = 1;

    pub const FIELD_COUNT: usize = 2;
    pub const ELEM_SIZES: [usize; FIELD_COUNT] = [4, 4];
    pub const FIELD_NAMES: [&str; FIELD_COUNT] = ["offset", "length"];
}

pub mod flags {
    pub const INTERACTIVE: u8 = 1 << 0;
    pub const MEASURABLE: u8 = 1 << 1;
    pub const GENERATED: u8 = 1 << 2;
    pub const EDITABLE: u8 = 1 << 3;
    pub const PLACEHOLDER: u8 = 1 << 4;
}

pub mod control_flags {
    pub const CHECKED: u8 = 1 << 0;
    pub const DISABLED: u8 = 1 << 1;
}

/// What a node is. `nodes.kind`.
pub mod node_kind {
    pub const BOX: u8 = 0;
    pub const TEXT: u8 = 1;
    pub const BUTTON: u8 = 2;
}

/// `styles.display`. `NONE` excludes the subtree from layout.
pub mod display {
    pub const FLEX: u8 = 0;
    pub const GRID: u8 = 1;
    pub const BLOCK: u8 = 2;
    pub const NONE: u8 = 3;
}

/// `styles.flexDirection`.
pub mod flex_direction {
    pub const ROW: u8 = 0;
    pub const COLUMN: u8 = 1;
    pub const ROW_REVERSE: u8 = 2;
    pub const COLUMN_REVERSE: u8 = 3;
}

/// `styles.flexWrap`.
pub mod flex_wrap {
    pub const NO_WRAP: u8 = 0;
    pub const WRAP: u8 = 1;
    pub const WRAP_REVERSE: u8 = 2;
}

/// `styles.justifyContent`. CSS `align-content` values, per Taffy.
pub mod justify {
    pub const FLEX_START: u8 = 0;
    pub const CENTER: u8 = 1;
    pub const FLEX_END: u8 = 2;
    pub const SPACE_BETWEEN: u8 = 3;
    pub const SPACE_AROUND: u8 = 4;
    pub const SPACE_EVENLY: u8 = 5;
    pub const UNSET: u8 = 255;
}

/// `styles.alignItems` / `alignSelf` / `justifyItems` / `justifySelf`.
pub mod align {
    pub const FLEX_START: u8 = 0;
    pub const CENTER: u8 = 1;
    pub const FLEX_END: u8 = 2;
    pub const STRETCH: u8 = 3;
    pub const BASELINE: u8 = 4;
    pub const UNSET: u8 = 255;
}

/// `styles.position`.
pub mod position {
    pub const RELATIVE: u8 = 0;
    pub const ABSOLUTE: u8 = 1;
}

/// `styles.overflowX` / `styles.overflowY`. `CLIP` is distinct from `HIDDEN` for one measured reason: Chromium coerces a `visible` axis to `auto` when the other axis is a scroll container, and `clip` is not one — see BROWSER-FACTS.md.
pub mod overflow {
    pub const VISIBLE: u8 = 0;
    pub const HIDDEN: u8 = 1;
    pub const ELLIPSIS: u8 = 2;
    pub const SCROLL: u8 = 3;
    pub const CLIP: u8 = 4;
}

/// `styles.scrollbarWidth`. The whole grammar: Chromium 151 rejects `thick` and a `<length>` outright, measured — MDN's scrollbars guide is wrong about both. `NONE` hides the bar without disabling the wheel, which is exactly what the property means.
pub mod scrollbar_width {
    pub const AUTO: u8 = 0;
    pub const THIN: u8 = 1;
    pub const NONE: u8 = 2;
}

/// `styles.appearance`. An *effect*, not the specified value — `<compat-auto>` keywords all collapse to `AUTO` here, which is what the spec says they do and what makes storing nine more variants pointless. `BASE_SELECT` is the opt-in that makes a `<select>` and its `::picker(select)` fully styleable; it is the one value that changes what gets drawn rather than merely whether. Measured against Chromium 151 — see BROWSER-FACTS.md.
pub mod appearance {
    pub const NONE: u8 = 0;
    pub const AUTO: u8 = 1;
    pub const BASE_SELECT: u8 = 2;
}

/// `media.kind`. Which axis a threshold tests, and which side of it counts as true. `MIN_*` holds at the threshold and above, `MAX_*` at it and below — the same inclusive bounds `min-width`/`max-width` have in CSS, which is why a `min-width: 768px` and a `max-width: 768px` query are both true at exactly 768.
pub mod media_kind {
    pub const MIN_WIDTH: u8 = 0;
    pub const MAX_WIDTH: u8 = 1;
    pub const MIN_HEIGHT: u8 = 2;
    pub const MAX_HEIGHT: u8 = 3;
}

/// Bit positions in a variant mask. Bits 0-4 are per-node; higher bits are global, so the engine can flip them without knowing which nodes care.
pub mod predicate {
    pub const HOVER: u32 = 1;
    pub const ACTIVE: u32 = 2;
    pub const FOCUS: u32 = 4;
    pub const CHECKED: u32 = 8;
    pub const DISABLED: u32 = 16;
    pub const FIRST_GLOBAL: u32 = 256;
}

/// `styles.INTERP`. How a field's value is found partway between two style rows. `NONE` is discrete and is what every enum gets. See the `Interp` doc comment in schema.ts for why a colour is its own kind rather than a number.
pub mod interp {
    pub const NONE: u8 = 0;
    pub const NUMBER: u8 = 1;
    pub const COLOR: u8 = 2;
}

/// `tweens.easing` and `keyframes.easing`. Which curve maps elapsed fraction to progress. The keywords are **not** normalised to `cubic-bezier()` by CSS — `ease` reads back as `ease` — but they are here, because a keyword is a bezier with fixed control points and storing five of them separately would be five ways to spell one curve. The two step keywords do normalise in CSS: `step-start` is `steps(1, start)` and `step-end` is `steps(1)`. Measured — see BROWSER-FACTS.md.
pub mod easing {
    pub const LINEAR: u8 = 0;
    pub const CUBIC_BEZIER: u8 = 1;
    pub const STEPS: u8 = 2;
    pub const INHERIT: u8 = 255;
}

/// `keyframes.easeB` / `tweens.easeB` when the easing is `STEPS`. Which end of each step the jump happens at. `steps(4, end)` reads 0 at t=0.1 and 0.75 at t=0.9; `steps(4, start)` reads 0.25 and 1.0 — measured, and the pair that tells them apart.
pub mod step_position {
    pub const JUMP_END: u8 = 0;
    pub const JUMP_START: u8 = 1;
    pub const JUMP_BOTH: u8 = 2;
    pub const JUMP_NONE: u8 = 3;
}

/// Engine → Bun. Drained after `tick()`; `0` means the queue is empty.
pub mod event_kind {
    pub const NONE: u32 = 0;
    pub const QUIT: u32 = 1;
    pub const RESIZE: u32 = 2;
    pub const MOUSE_MOVE: u32 = 3;
    pub const MOUSE_DOWN: u32 = 4;
    pub const MOUSE_UP: u32 = 5;
    pub const CLICK: u32 = 6;
    pub const KEY_DOWN: u32 = 7;
    pub const TEXT_INPUT: u32 = 8;
    pub const FOCUS: u32 = 9;
    pub const CHANGE: u32 = 10;
}

/// `controls.kind`. What a press does to this node, which is the only thing the engine needs to know about a control — appearance is the stylesheet's job and is already resolved into the style table. `CHECKBOX` toggles; `RADIO` sets itself and clears its group, and cannot be unchecked by pointer (measured).
pub mod control_kind {
    pub const NONE: u8 = 0;
    pub const CHECKBOX: u8 = 1;
    pub const RADIO: u8 = 2;
}

/// Return code of every FFI entry point. Negative is failure, and the detail is in `dziri_last_error`.
pub mod status {
    pub const OK: i32 = 0;
    pub const PANIC: i32 = -1;
    pub const INVALID_HANDLE: i32 = -2;
    pub const INVALID_ARGUMENT: i32 = -3;
    pub const PROTOCOL_MISMATCH: i32 = -4;
    pub const CAPACITY: i32 = -5;
    pub const SDL: i32 = -6;
    pub const SKIA: i32 = -7;
    pub const LAYOUT: i32 = -8;
    pub const POISONED: i32 = -9;
}
