// GENERATED by scripts/coverage-snapshot.ts. Do not edit.
//
// What the coverage tools said when this was last run. Regenerate with
// `bun run coverage:snapshot`; `--check` fails when it is stale.
//
// These are displayed on the demo's overview page. They are generated rather than
// typed because the two that used to be typed were both wrong: the page claimed
// 36% of Tailwind and 93 CSS properties while the tools said 41.2% and 98.

export const COVERAGE = {
  /** `bun run tailwind-coverage` — classes from the installed tailwindcss that compile. */
  tailwind: { pct: "97.7%", have: 22744, total: 23286 },

  /**
   * `bun run css-coverage` — against the curated corpus in guards/css-coverage/in-scope.txt,
   * *not* against all of CSS. The denominator is the point: "everything standard
   * minus the non-goals" is ~376 properties including ones a UI framework will
   * never want, and a percentage against that would mislead.
   */
  css: { pct: "84.1%", have: 106, total: 126, supported: 231 },

  /**
   * `bun run html-coverage` — elements whose default rendering already matches
   * Chrome, out of those compared.
   *
   * The tool deliberately prints no percentage of its own, because it is a
   * difference table rather than a pass/fail run. This ratio has a stated
   * denominator — in-scope elements actually compared. The one element still
   * differing is li, blocked on the list-marker feature (a paint feature,
   * not a stylesheet rule), per HTML-ELEMENT-COVERAGE-RESEARCH.md.
   */
  html: { pct: "98.0%", have: 49, total: 50 },
} as const;
