// GENERATED by scripts/coverage-snapshot.ts. Do not edit.
//
// What the coverage tools said when this was last run. Regenerate with
// `bun run coverage:snapshot`; `--check` fails when it is stale.
//
// These are displayed on the demo's overview page. They are generated rather than
// typed because the two that used to be typed were both wrong: the page claimed
// 36% of Tailwind and 93 CSS properties while the tools said 41.2% and 98.

export const COVERAGE = {
  /** `bun run tailwind-coverage` — classes from the installed tailwindcss that compile. */
  tailwind: { pct: "44.1%", have: 10277, total: 23286 },

  /**
   * `bun run css-coverage` — against the curated corpus in css-coverage/in-scope.txt,
   * *not* against all of CSS. The denominator is the point: "everything standard
   * minus the non-goals" is ~376 properties including ones a UI framework will
   * never want, and a percentage against that would mislead.
   */
  css: { pct: "64.3%", have: 81, total: 126, supported: 131 },

  /**
   * `bun run html-coverage` — elements whose default rendering already matches
   * Chrome, out of those compared.
   *
   * The tool deliberately prints no percentage of its own, because it is a
   * difference table rather than a pass/fail run. This ratio has a stated
   * denominator — in-scope elements actually compared — and it is low for one
   * reason: the UA stylesheet is young. That is the largest single coverage lever
   * left, per HTML-ELEMENT-COVERAGE-RESEARCH.md.
   */
  html: { pct: "41.0%", have: 25, total: 61 },
} as const;
