// GENERATED by src/compile.ts from windows/main/index.tsx + windows/main/index.css
// Do not edit. No CSS, no selectors, no property names — just indices.
//
// 37 nodes, 14 style slots, 11 strings,
// 3 conditional nodes (2 variant slots), 3 interactive,
// 0 text bindings, 0 handlers.

// Types, so this artifact is checked rather than asserted at the far end.
import type { HandlerBinding, ListTable, MediaTable, NodeTable, StyleTable, TextBinding, VariantTable, RouteNodes, WindowConfig } from "../../src/ir.ts";
import type { EditableRef } from "../../src/runtime/bindings.ts";
import type { ListBindingRef } from "../../src/runtime/list-runtime.ts";
import type { StylePatchRef } from "../../src/runtime/patches.ts";

/** Mutable past the static entries: text bindings overwrite their own slots. */
export const strings: string[] = ["dziri","Home","Products","About","Routing","Every route in this window is compiled into one table set. The four that are not showing are resident and hidden, which costs memory and nothing per frame.","A window is windows/main/index.tsx; its routes are the files under pages/. The route path is the file path, and a $segment is a parameter.","New","First","A static route, sorted before the parameter route beside it.","A parameter route. Its pattern is products/$id, bound per navigation."];

/** Mutable: style patches write field values in place. Node pointers never change. */
export const styles = {
  count: 14,
  bg: new Uint32Array([4279506458,0,4279967268,0,0,4280428078,4281152060,0,0,4279967268,0,0,4280428078,4279704095]),
  fg: new Uint32Array([4293323247,4293323247,4293323247,4294112762,4293323247,4289640132,4293323247,4289640132,4293323247,4293323247,4294112762,4289640132,4289640132,4293323247]),
  borderColor: new Uint32Array([0,0,0,0,0,0,0,0,0,4280954680,0,0,0,4280691507]),
  borderWidth: new Float32Array([0,0,0,0,0,0,0,0,0,1,0,0,0,1]),
  radius: new Float32Array([0,0,0,0,0,6,6,0,0,10,0,0,5,8]),
  padT: new Float32Array([0,0,14,0,0,6,6,0,24,20,0,0,5,14]),
  padR: new Float32Array([0,0,20,0,0,12,12,0,24,20,0,0,10,14]),
  padB: new Float32Array([0,0,14,0,0,6,6,0,24,20,0,0,5,14]),
  padL: new Float32Array([0,0,20,0,0,12,12,0,24,20,0,0,10,14]),
  marT: new Float32Array(14),
  marR: new Float32Array(14),
  marB: new Float32Array(14),
  marL: new Float32Array(14),
  display: new Uint8Array(14),
  direction: new Uint8Array([1,1,0,1,0,1,1,1,1,1,1,1,1,1]),
  wrap: new Uint8Array(14),
  justify: new Uint8Array([0,0,3,0,0,0,0,0,0,0,0,0,0,0]),
  align: new Uint8Array([255,255,1,255,255,255,255,255,255,255,255,255,255,255]),
  alignSelf: new Uint8Array(14).fill(255),
  grow: new Float32Array([0,1,0,0,0,0,0,0,1,0,0,0,0,0]),
  shrink: new Float32Array(14).fill(1),
  basis: new Float32Array(14).fill(NaN),
  gapRow: new Float32Array([0,0,0,0,8,0,0,0,0,12,0,0,0,0]),
  gapCol: new Float32Array([0,0,0,0,8,0,0,0,0,12,0,0,0,0]),
  gridCols: new Uint16Array(14),
  gridRows: new Uint16Array(14),
  gridColStart: new Int16Array(14),
  gridColSpan: new Int16Array(14),
  gridRowStart: new Int16Array(14),
  gridRowSpan: new Int16Array(14),
  justifyItems: new Uint8Array(14).fill(255),
  justifySelf: new Uint8Array(14).fill(255),
  width: new Float32Array(14).fill(NaN),
  height: new Float32Array(14).fill(NaN),
  minW: new Float32Array(14).fill(NaN),
  maxW: new Float32Array(14).fill(Infinity),
  minH: new Float32Array(14).fill(NaN),
  maxH: new Float32Array(14).fill(Infinity),
  aspectRatio: new Float32Array(14).fill(NaN),
  position: new Uint8Array(14),
  insetT: new Float32Array(14).fill(NaN),
  insetR: new Float32Array(14).fill(NaN),
  insetB: new Float32Array(14).fill(NaN),
  insetL: new Float32Array(14).fill(NaN),
  fontSize: new Float32Array([15,15,15,16,15,13,13,13,15,15,20,14,13,15]),
  fontWeight: new Uint16Array([400,400,400,600,400,400,400,400,400,400,600,400,400,400]),
  overflowX: new Uint8Array(14),
  overflowY: new Uint8Array(14),
  scrollbarWidth: new Uint8Array(14),
  scrollbarThumb: new Uint32Array(14),
  scrollbarTrack: new Uint32Array(14),
} satisfies StyleTable;

export const nodes = {
  count: 37,
  kind: new Uint8Array([0,0,0,0,1,0,0,1,0,1,0,1,0,0,0,1,0,1,0,0,1,0,1,0,0,1,0,0,1,0,1,0,0,1,0,0,1]),
  style: new Uint16Array([0,1,2,3,3,4,5,7,5,7,5,7,8,9,10,10,11,11,9,10,10,11,11,9,10,10,4,12,7,12,7,13,11,11,13,11,11]),
  text: new Int32Array([-1,-1,-1,-1,0,-1,-1,1,-1,2,-1,3,-1,-1,-1,4,-1,5,-1,-1,3,-1,6,-1,-1,2,-1,-1,7,-1,8,-1,-1,9,-1,-1,10]),
  parent: new Int32Array([-1,0,1,2,3,2,5,6,5,8,5,10,1,12,13,14,13,16,12,18,19,18,21,12,23,24,23,26,27,26,29,23,31,32,23,34,35]),
  firstChild: new Int32Array([1,2,3,4,-1,6,7,-1,9,-1,11,-1,13,14,15,-1,17,-1,19,20,-1,22,-1,24,25,-1,27,28,-1,30,-1,32,33,-1,35,36,-1]),
  nextSibling: new Int32Array([-1,-1,12,5,-1,-1,8,-1,10,-1,-1,-1,-1,18,16,-1,-1,-1,23,21,-1,-1,-1,-1,26,-1,31,29,-1,-1,-1,34,-1,-1,-1,-1,-1]),
  list: new Int16Array(37).fill(-1),
  hidden: new Uint8Array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0]),
} satisfies NodeTable;

/**
 * Conditional styling, sparse and sorted by node.
 *
 * mask is the predicate bits a node reads; slots[runStart + i] is its style for
 * the combination whose compacted bits equal i. Runs are shared between nodes
 * that resolve identically.
 */
export const variants = {
  count: 3,
  node: new Int32Array([6,8,10]),
  mask: new Uint32Array(3).fill(1),
  runStart: new Int32Array(3),
  slots: new Uint16Array([5,6]),
} satisfies VariantTable;

/** Nodes that can receive input, sorted. Emitted, never inferred. */
export const interactive = new Int32Array([6,8,10]);

/** Dynamic text runs. Literal chunks interleaved with the signals they read. */
export const textBindings = [

] satisfies TextBinding[];

/** Click handlers, as direct references to the app's exported functions. */
export const handlers = [

] satisfies HandlerBinding[];

/** Nodes that route keystrokes into a string signal while focused. */
export const editables = [

] satisfies EditableRef[];

/**
 * Conditional classes, compiled to style-table writes.
 *
 * Each entry writes field values for the slots the class actually changes — no
 * class names, no cascade, and node style pointers untouched. affectsLayout says
 * whether applying it requires a relayout or only a repaint.
 */
export const stylePatches = [

] satisfies StylePatchRef[];

/**
 * Dynamic lists. Each owns a contiguous arena of identical item subtrees; the
 * runtime rewrites the child chain and the bound slots, never the nodes.
 */
export const lists = {
  count: 0,
  container: new Int32Array([]),
  anchorPrev: new Int32Array([]),
  anchorNext: new Int32Array([]),
  arenaStart: new Int32Array([]),
  stride: new Int32Array([]),
  capacity: new Int32Array([]),
  active: new Int32Array(0),
  dataOffset: new Int32Array(0),
} satisfies ListTable;

/** Per-list: the array signal, key path, and where each item's bound slots live. */
export const listBindings = [

] satisfies ListBindingRef[];

/**
 * Media conditions, one row per distinct threshold, in predicate-bit order.
 *
 * The engine re-evaluates these against the surface between a resize and the
 * relayout. Bun uploads them once and never looks at them again — routing a
 * resize back through Bun would lag a frame and stall whenever Bun is busy.
 */
export const media = {
  count: 0,
  bit: new Uint32Array([]),
  kind: new Uint8Array([]),
  value: new Float32Array([]),
} satisfies MediaTable;

export const root: number = 0;

/** The window this artifact is, as `<Window>` declared it. */
export const windowConfig = {
  title: "dziri — routing",
  width: 900,
  height: 560,
  minWidth: 420,
  minHeight: 320,
} satisfies WindowConfig;

/**
 * Each route's own top-level nodes, in the window's match order.
 *
 * Navigation writes `hidden` over the routes leaving the chain and clears it over
 * the ones joining — bounded by route count, not by node count.
 */
export const routeNodes = [
  { path: "/", roots: [13], parent: -1 },
  { path: "about", roots: [18], parent: -1 },
  { path: "products", roots: [23], parent: -1 },
  { path: "products/new", roots: [31], parent: 2 },
  { path: "products/$id", roots: [34], parent: 2 },
] satisfies RouteNodes[];

/** Index in `routeNodes` of the route the emitted `hidden` column shows. */
export const initialRoute: number = 0;

/** Folder name of the window, for diagnostics and multi-window dispatch later. */
export const windowId: string = "main";
