/**
 * Records what the coverage tools currently say, for the demo to display.
 *
 *   bun run coverage:snapshot           # run the tools, rewrite the snapshot
 *   bun run coverage:snapshot --check   # fail if the snapshot is out of date
 *
 * The demo's overview page used to state "36% of Tailwind classes compile" and
 * "93 CSS properties supported" as literals in JSX. Both were wrong by the time
 * anyone read them — the real figures were 41.2% and 98 — and nothing could have
 * noticed, because a number typed into a page is not checked by anything. This
 * repository has `doc-lint` for citations and `protocol-guard` for the schema for
 * exactly that reason; a published percentage deserves the same treatment.
 *
 * So the numbers come from the tools that compute them, through a generated file
 * that is committed. Committed rather than computed at build time because two of
 * the three tools need headless Chrome, and `bun run dev` must not.
 *
 * `--check` is what keeps it honest: it re-runs the tools and fails if the
 * snapshot disagrees, so a change that moves coverage either updates this file or
 * fails the check. That is a ratchet in the same shape as `runtime-surface`.
 */
import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";

const ROOT = join(import.meta.dir, "..");
const OUT = join(ROOT, "windows", "main", "coverage.gen.ts");
const CHECK = process.argv.includes("--check");

async function run(script: string): Promise<string> {
  const proc = Bun.spawn(["bun", "run", `scripts/${script}.ts`], {
    cwd: ROOT,
    stdout: "pipe",
    stderr: "pipe",
  });
  const [out] = await Promise.all([new Response(proc.stdout).text(), proc.exited]);
  return out;
}

/** The first capture of `re`, or a thrown error naming what was being looked for. */
function grab(text: string, re: RegExp, what: string): string {
  const m = text.match(re);
  if (!m) throw new Error(`could not read ${what} from the tool's output`);
  return m[1]!;
}

const tw = await run("tailwind-coverage");
const css = await run("css-coverage");
const html = await run("html-coverage");

// `classes 9605/23286 work today (41.2%)`
const twWorking = grab(tw, /classes\s+(\d+)\/\d+ work today/, "Tailwind classes working");
const twTotal = grab(tw, /classes\s+\d+\/(\d+) work today/, "Tailwind class total");
const twPct = grab(tw, /classes\s+\d+\/\d+ work today \(([\d.]+)%\)/, "Tailwind percentage");

// `56.3% of the defined corpus  (71/126)`
const cssPct = grab(css, /([\d.]+)% of the defined corpus/, "CSS corpus percentage");
const cssHave = grab(css, /of the defined corpus\s+\((\d+)\/\d+\)/, "CSS properties in corpus");
const cssTotal = grab(css, /of the defined corpus\s+\(\d+\/(\d+)\)/, "CSS corpus size");
const cssSupported = grab(css, /supported\s+(\d+)/, "CSS properties supported");

// `36 differ · 20 known only · 25 already match · …`
const htmlDiffer = grab(html, /(\d+) differ/, "HTML elements differing");
const htmlMatch = grab(html, /(\d+) already match/, "HTML elements matching");
const htmlCompared = String(Number(htmlDiffer) + Number(htmlMatch));
const htmlPct = ((Number(htmlMatch) / Number(htmlCompared)) * 100).toFixed(1);

const source = `// GENERATED by scripts/coverage-snapshot.ts. Do not edit.
//
// What the coverage tools said when this was last run. Regenerate with
// \`bun run coverage:snapshot\`; \`--check\` fails when it is stale.
//
// These are displayed on the demo's overview page. They are generated rather than
// typed because the two that used to be typed were both wrong: the page claimed
// 36% of Tailwind and 93 CSS properties while the tools said 41.2% and 98.

export const COVERAGE = {
  /** \`bun run tailwind-coverage\` — classes from the installed tailwindcss that compile. */
  tailwind: { pct: "${twPct}%", have: ${twWorking}, total: ${twTotal} },

  /**
   * \`bun run css-coverage\` — against the curated corpus in guards/css-coverage/in-scope.txt,
   * *not* against all of CSS. The denominator is the point: "everything standard
   * minus the non-goals" is ~376 properties including ones a UI framework will
   * never want, and a percentage against that would mislead.
   */
  css: { pct: "${cssPct}%", have: ${cssHave}, total: ${cssTotal}, supported: ${cssSupported} },

  /**
   * \`bun run html-coverage\` — elements whose default rendering already matches
   * Chrome, out of those compared.
   *
   * The tool deliberately prints no percentage of its own, because it is a
   * difference table rather than a pass/fail run. This ratio has a stated
   * denominator — in-scope elements actually compared. The one element still
   * differing is li, blocked on the list-marker feature (a paint feature,
   * not a stylesheet rule), per HTML-ELEMENT-COVERAGE-RESEARCH.md.
   */
  html: { pct: "${htmlPct}%", have: ${htmlMatch}, total: ${htmlCompared} },
} as const;
`;

const previous = await readFile(OUT, "utf8").catch(() => "");

if (CHECK) {
  if (previous.trim() === source.trim()) {
    console.log("coverage-snapshot  up to date");
    console.log(
      `  tailwind ${twPct}% (${twWorking}/${twTotal}) · css ${cssPct}% (${cssHave}/${cssTotal}) · html ${htmlPct}% (${htmlMatch}/${htmlCompared})`,
    );
    process.exit(0);
  }
  console.log("coverage-snapshot  STALE — the demo is showing numbers the tools disagree with");
  console.log(`  run: bun run coverage:snapshot`);
  process.exit(1);
}

await writeFile(OUT, source);
console.log(`coverage-snapshot  -> ${OUT.slice(ROOT.length + 1)}`);
console.log(`  tailwind  ${twPct}%  (${twWorking}/${twTotal} classes)`);
console.log(`  css       ${cssPct}%  (${cssHave}/${cssTotal} corpus · ${cssSupported} properties parsed)`);
console.log(`  html      ${htmlPct}%  (${htmlMatch}/${htmlCompared} elements match Chrome)`);
