/**
 * Holds the docs to the code.
 *
 *   bun run docs-check              # everything
 *   bun run docs-check --quiet      # failures only
 *   bun run docs-check --examples   # just typecheck the code blocks
 *   bun run docs-check --keep       # leave the extracted examples on disk
 *
 * `doc-lint` already proves that `file.ts:LINE` citations resolve. That is the
 * mechanical half. This is the other half, and it checks the three things that
 * actually rot when the framework moves underneath a page:
 *
 *   1. **Examples compile.** Every ```ts / ```tsx block in the docs is extracted and
 *      typechecked against the real `dziri` types. Rename an export and the docs fail
 *      with it, in the same run, instead of six weeks later in someone's terminal.
 *
 *   2. **The public surface is covered.** Everything re-exported from `src/index.ts`
 *      is the authoring API. A surface no page mentions is an undocumented feature; a
 *      page documenting a name that is no longer exported is a lie.
 *
 *   3. **Frontmatter is present.** The sidebars are autogenerated, so a page with no
 *      `sidebar_position` sorts arbitrarily and a page with no `title` gets one
 *      guessed from its filename. Both fail quietly, which is the worst way to fail.
 *
 * What it deliberately does not check is whether the prose is *true*. Nothing can.
 * See `.claude/skills/docs/SKILL.md` for the part that still needs a person.
 */
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { readdirSync } from "node:fs";
import { join, relative } from "node:path";

const ROOT = join(import.meta.dir, "..");
const DOCS = join(ROOT, "docs", "docs");
/**
 * Extraction lives at the repo **root**, not under `docs/`.
 *
 * `docs/` is its own workspace package (`dziri-docs`), and a package self-reference
 * resolves against the nearest ancestor `package.json`. Extract into `docs/` and the
 * nearest one is `dziri-docs`, which has no `dziri` export — so every example failed
 * with "Cannot find module 'dziri'" and, because that is not a per-file diagnostic,
 * the run reported them all as compiling. Two bugs stacked into a check that passed
 * while doing nothing.
 */
const WORK = join(ROOT, ".docs-examples");

const argv = process.argv.slice(2);
const QUIET = argv.includes("--quiet");
const KEEP = argv.includes("--keep");
const ONLY_EXAMPLES = argv.includes("--examples");

let failures = 0;
const fail = (msg: string): void => {
  failures++;
  console.log(msg);
};

// ---------------------------------------------------------------------------
// Pages
// ---------------------------------------------------------------------------

type Page = { path: string; rel: string; text: string };

function pages(dir: string, out: Page[] = []): Page[] {
  if (!existsSync(dir)) return out;
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    if (e.name.startsWith(".")) continue;
    const p = join(dir, e.name);
    if (e.isDirectory()) pages(p, out);
    else if (e.name.endsWith(".md") || e.name.endsWith(".mdx"))
      out.push({ path: p, rel: relative(ROOT, p).replace(/\\/g, "/"), text: readFileSync(p, "utf8") });
  }
  return out;
}

const all = pages(DOCS);
if (all.length === 0) {
  console.log(`docs-check  no pages under ${relative(ROOT, DOCS)} — nothing to check`);
  process.exit(0);
}

// ---------------------------------------------------------------------------
// 1. Code examples typecheck
// ---------------------------------------------------------------------------

/** ```lang meta\n …body… \n``` */
const FENCE = /^([ \t]*)```([A-Za-z0-9]+)([^\n]*)\n([\s\S]*?)^[ \t]*```[ \t]*$/gm;

/** The authoring surface, injected so a fragment need not repeat the import. */
const PREAMBLE = [
  'import { $, batch, bind, cn, computed, Fragment, isSignal, Outlet, signal, useRoute, useRouter, Window } from "dziri";',
  'import type { Args, Child, ClassArg, ClassSpec, Component, MapOptions, Props, ReadonlySignal, Route, Router, Signal, StyleObject, WindowConfig, WindowProps } from "dziri";',
].join("\n");

type Example = { page: Page; startLine: number; lang: string; body: string; file: string };

const examples: Example[] = [];
/**
 * Every fenced ts/tsx body, including the `no-check` ones.
 *
 * The phantom-import check reads these rather than the whole page. Prose *about* a
 * bad import — "a page teaching `import { foo } from \"dziri\"`" — is illustrative,
 * and flagging it made this checker fail on the page documenting itself. Fenced
 * blocks are the ones presented as usable code, so they are the ones held to it.
 *
 * `no-check` blocks are deliberately included: they are not typechecked, which makes
 * them the most likely place for a phantom import to survive unnoticed.
 */
const fencedCode = new Map<string, string[]>();
let skipped = 0;

for (const page of all) {
  FENCE.lastIndex = 0;
  for (const m of page.text.matchAll(FENCE)) {
    const [whole, , lang = "", meta = "", body = ""] = m as unknown as [string, string, string, string, string];
    if (lang !== "ts" && lang !== "tsx") continue;

    const bodies = fencedCode.get(page.rel) ?? [];
    bodies.push(body);
    fencedCode.set(page.rel, bodies);

    // `no-check` is the escape hatch for a fragment that cannot stand alone —
    // usually one importing from a project's own `./state.ts`. Counted and
    // reported rather than silently ignored: an unchecked example is a risk, and
    // the number of them is the thing worth watching.
    if (/\bno-check\b/.test(meta)) {
      skipped++;
      continue;
    }

    const startLine = page.text.slice(0, m.index!).split("\n").length + 1;
    // A snippet with its own dziri import must not get a second one.
    const hasOwn = /^\s*import\b[^\n]*["']dziri["']/m.test(body);
    const source = hasOwn ? body : `${PREAMBLE}\n${body}`;
    const file = `ex${examples.length}.${lang === "tsx" ? "tsx" : "ts"}`;
    examples.push({ page, startLine, lang, body: source, file });
  }
}

function checkExamples(): void {
  if (examples.length === 0) return;

  rmSync(WORK, { recursive: true, force: true });
  mkdirSync(WORK, { recursive: true });

  for (const ex of examples) writeFileSync(join(WORK, ex.file), ex.body, "utf8");

  // Extends the repo's tsconfig so the examples are checked under exactly the
  // settings an author's code is checked under — same strictness, same
  // `jsxImportSource`. A laxer config here would let the docs pass on code the
  // reader's own project would reject.
  writeFileSync(
    join(WORK, "tsconfig.json"),
    JSON.stringify(
      {
        extends: "../tsconfig.json",
        compilerOptions: { noEmit: true, types: ["bun"], skipLibCheck: true },
        // Explicit globs rather than ".", which produced TS18003 "no inputs found".
        include: ["*.ts", "*.tsx"],
      },
      null,
      2,
    ),
    "utf8",
  );

  let out = "";
  try {
    execFileSync("bunx", ["tsc", "--noEmit", "-p", WORK], {
      cwd: ROOT,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "pipe"],
    });
  } catch (e) {
    const err = e as { stdout?: string; stderr?: string };
    out = `${err.stdout ?? ""}${err.stderr ?? ""}`;
  }

  if (out.trim()) {
    // `ex12.tsx(4,10): error TS2304: Cannot find name 'foo'.`
    // Paths may be absolute or repo-relative depending on how tsc was invoked.
    const DIAGNOSTIC = /(?:^|[\\/])(ex\d+\.tsx?)\((\d+),(\d+)\):\s*(.*)$/;
    const byFile = new Map<string, Example>(examples.map((e) => [e.file, e]));
    const seen = new Set<string>();
    let parsed = 0;

    for (const line of out.split("\n")) {
      const m = DIAGNOSTIC.exec(line.trim());
      if (!m) continue;
      const ex = byFile.get(m[1]!);
      if (!ex) continue;
      parsed++;

      // Map the line back through the injected preamble to the real doc line.
      const preambleLines = ex.body.startsWith(PREAMBLE) ? PREAMBLE.split("\n").length : 0;
      const inBody = Number(m[2]) - preambleLines;
      const docLine = ex.startLine + Math.max(0, inBody - 1);
      const key = `${ex.page.rel}:${docLine}:${m[4]}`;
      if (seen.has(key)) continue;
      seen.add(key);

      fail(`  ${ex.page.rel}:${docLine}  ${m[4]}`);
    }

    // tsc said something we could not attribute to any example.
    //
    // This is the failure that matters most, because its natural shape is a *silent
    // pass*: a config error (TS18003 "no inputs found", TS5058 "path does not
    // exist", an unresolved `dziri`) produces output with no per-file diagnostic, so
    // the loop above records nothing and the run cheerfully reports that every
    // example compiles. Both of those bugs happened here on 2026-08-02, stacked, and
    // the check reported "all 25 compile" while typechecking nothing at all.
    if (parsed === 0) {
      fail(
        `  tsc failed without a per-example diagnostic — the examples were NOT checked.\n` +
          out
            .trim()
            .split("\n")
            .slice(0, 8)
            .map((l) => `      ${l}`)
            .join("\n"),
      );
    }
  }

  if (!KEEP) rmSync(WORK, { recursive: true, force: true });
}

if (!QUIET) console.log(`docs-check  ${all.length} pages · ${examples.length} examples typechecked${skipped ? ` · ${skipped} marked no-check` : ""}`);

const before = failures;
if (examples.length) {
  if (!QUIET) console.log(`\nEXAMPLES`);
  checkExamples();
  if (failures === before && !QUIET) console.log(`  all ${examples.length} compile`);
}

if (ONLY_EXAMPLES) {
  console.log(failures ? `\n${failures} problem(s)` : `\nclean`);
  process.exit(failures ? 1 : 0);
}

// ---------------------------------------------------------------------------
// 2. Public API coverage
// ---------------------------------------------------------------------------

/**
 * The authoring surface, read from the barrel rather than listed here.
 *
 * `src/index.ts` is where the public-versus-internal line is drawn, so it is also
 * the right definition of "what the docs owe the reader a page about". Anything only
 * reachable through a wildcard export is deliberately not a promise, and is not
 * counted.
 */
function publicExports(): { values: string[]; types: string[] } {
  const src = readFileSync(join(ROOT, "src", "index.ts"), "utf8");
  const values: string[] = [];
  const types: string[] = [];

  for (const m of src.matchAll(/export\s+(type\s+)?\{([^}]*)\}\s*from/g)) {
    const isType = Boolean(m[1]);
    for (const raw of m[2]!.split(",")) {
      const name = raw.trim().split(/\s+as\s+/).pop()?.trim();
      if (!name) continue;
      // `export { type Foo, bar }` — a type marked inline inside a value export.
      const inlineType = /^type\s+/.test(raw.trim());
      const clean = name.replace(/^type\s+/, "");
      if (!clean || !/^[A-Za-z_$][\w$]*$/.test(clean)) continue;
      (isType || inlineType ? types : values).push(clean);
    }
  }
  return { values, types };
}

const { values, types } = publicExports();
const corpus = all.map((p) => p.text).join("\n");

/**
 * Mentioned as a standalone token — in prose, a heading, a code fence, anywhere.
 *
 * `\b` is wrong at either end for a name like `$`, because `$` is not a word
 * character and so has no word boundary beside it: `\b\$\b` matches nothing, ever,
 * and `$` was reported undocumented while sitting under its own heading. Pick the
 * anchor from the character actually at each end.
 */
function mentions(name: string): boolean {
  const esc = name.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const left = /^\w/.test(name) ? "\\b" : "(?<![\\w$])";
  const right = /\w$/.test(name) ? "\\b" : "(?![\\w$])";
  return new RegExp(`${left}${esc}${right}`).test(corpus);
}

const undocumented = values.filter((v) => !mentions(v));
const undocumentedTypes = types.filter((t) => !mentions(t));

if (!QUIET) console.log(`\nPUBLIC API  ${values.length} values · ${types.length} types exported from src/index.ts`);

if (undocumented.length) {
  fail(`\nUNDOCUMENTED — exported from src/index.ts, mentioned by no page (${undocumented.length})`);
  for (const n of undocumented) console.log(`  ${n}`);
} else if (!QUIET) {
  console.log(`  every exported value is mentioned somewhere`);
}

// Types are advisory: a type can be genuinely internal to an example's shape.
if (undocumentedTypes.length && !QUIET) {
  console.log(`\n  types with no mention (advisory, does not fail): ${undocumentedTypes.join(", ")}`);
}

/**
 * The reverse direction, and the one that actually misleads: a page teaching an
 * import that no longer exists. Only `from "dziri"` is checked — a deep path is the
 * emitter's business, not an author's.
 */
const IMPORT_FROM_DZIRI = /import\s+(?:type\s+)?\{([^}]*)\}\s*from\s*["']dziri["']/g;
const known = new Set([...values, ...types]);
const phantom = new Map<string, string[]>();

for (const [rel, bodies] of fencedCode) {
  for (const body of bodies) {
    for (const m of body.matchAll(IMPORT_FROM_DZIRI)) {
      for (const raw of m[1]!.split(",")) {
        const name = raw.trim().replace(/^type\s+/, "").split(/\s+as\s+/)[0]?.trim();
        if (!name || !/^[A-Za-z_$][\w$]*$/.test(name)) continue;
        if (known.has(name)) continue;
        const list = phantom.get(rel) ?? [];
        if (!list.includes(name)) list.push(name);
        phantom.set(rel, list);
      }
    }
  }
}

if (phantom.size) {
  fail(`\nPHANTOM IMPORT — documented as importable from "dziri", not exported (${phantom.size} page(s))`);
  for (const [page, names] of phantom) console.log(`  ${page}  ${names.join(", ")}`);
}

// ---------------------------------------------------------------------------
// 3. Frontmatter
// ---------------------------------------------------------------------------

const missing: string[] = [];
for (const page of all) {
  const fm = /^---\n([\s\S]*?)\n---/.exec(page.text);
  if (!fm) {
    missing.push(`${page.rel}  no frontmatter`);
    continue;
  }
  const block = fm[1]!;
  const lacks: string[] = [];
  if (!/^title:/m.test(block)) lacks.push("title");
  // The site's index sets `slug: /` and is the one page whose position is implied.
  if (!/^sidebar_position:/m.test(block) && !/^slug:\s*\/\s*$/m.test(block)) lacks.push("sidebar_position");
  if (lacks.length) missing.push(`${page.rel}  missing ${lacks.join(", ")}`);
}

if (missing.length) {
  fail(`\nFRONTMATTER — the sidebars are autogenerated, so these sort arbitrarily (${missing.length})`);
  for (const m of missing) console.log(`  ${m}`);
} else if (!QUIET) {
  console.log(`\nFRONTMATTER  all ${all.length} pages carry title + sidebar_position`);
}

console.log(failures ? `\n${failures} problem(s)` : `\nclean — ${examples.length} examples compile, ${values.length} public values documented`);
process.exit(failures ? 1 : 0);
