/**
 * Four sidebars, each autogenerated from its directory.
 *
 * Autogenerated rather than hand-listed so that adding a page is one file, not two
 * — the failure mode of a hand-maintained sidebar is a page that exists and cannot
 * be reached. Ordering comes from `sidebar_position` in each page's frontmatter,
 * and `bun run docs-check` fails on a page that omits it.
 */
import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  learn: [{ type: "autogenerated", dirName: "learn" }],
  reference: [{ type: "autogenerated", dirName: "reference" }],
  architecture: [{ type: "autogenerated", dirName: "architecture" }],
  contributing: [{ type: "autogenerated", dirName: "contributing" }],
};

export default sidebars;
