// GENERATED by src/compile.ts from demo-tailwind/index.html + demo-tailwind/app.css
// Do not edit. No CSS, no selectors, no property names — just indices.
//
// 47 nodes, 4 style slots, 17 strings,
// 0 conditional nodes (0 variant slots), 0 interactive,
// 0 text bindings, 0 handlers.

// Types, so this artifact is checked rather than asserted at the far end.
import type { HandlerBinding, ListTable, NodeTable, StyleTable, TextBinding, VariantTable } from "../src/ir.ts";
import type { EditableRef } from "../src/runtime/bindings.ts";
import type { ListBindingRef } from "../src/runtime/list-runtime.ts";
import type { StylePatchRef } from "../src/runtime/patches.ts";

/** Mutable past the static entries: text bindings overwrite their own slots. */
export const strings: string[] = ["Tailwind, compiled","No browser engine. These classes went through dziri's compiler.","var() and calc()","31.5%","of Tailwind classes compile","was","2.1%","before this session","classes working","7170","up from 469","red-500","green-500","amber-400","violet-500","pink-500","Spacing comes from calc(var(--spacing) * n)"];

/** Mutable: style patches write field values in place. Node pointers never change. */
export const styles = {
  count: 4,
  bg: new Uint32Array(4),
  fg: new Uint32Array(4).fill(4278190080),
  borderColor: new Uint32Array(4),
  borderWidth: new Float32Array([0,0,0,1]),
  radius: new Float32Array([0,0,4,0]),
  padT: new Float32Array(4),
  padR: new Float32Array(4),
  padB: new Float32Array(4),
  padL: new Float32Array(4),
  marT: new Float32Array(4),
  marR: new Float32Array(4),
  marB: new Float32Array(4),
  marL: new Float32Array(4),
  display: new Uint8Array(4),
  direction: new Uint8Array([1,0,1,1]),
  wrap: new Uint8Array(4),
  justify: new Uint8Array(4),
  align: new Uint8Array(4).fill(255),
  alignSelf: new Uint8Array(4).fill(255),
  grow: new Float32Array(4),
  shrink: new Float32Array(4).fill(1),
  basis: new Float32Array(4).fill(NaN),
  gapRow: new Float32Array(4),
  gapCol: new Float32Array(4),
  gridCols: new Uint16Array(4),
  gridRows: new Uint16Array(4),
  gridColStart: new Int16Array(4),
  gridColSpan: new Int16Array(4),
  gridRowStart: new Int16Array(4),
  gridRowSpan: new Int16Array(4),
  justifyItems: new Uint8Array(4).fill(255),
  justifySelf: new Uint8Array(4).fill(255),
  width: new Float32Array(4).fill(NaN),
  height: new Float32Array(4).fill(NaN),
  minW: new Float32Array(4).fill(NaN),
  maxW: new Float32Array(4).fill(Infinity),
  minH: new Float32Array(4).fill(NaN),
  maxH: new Float32Array(4).fill(Infinity),
  aspectRatio: new Float32Array(4).fill(NaN),
  position: new Uint8Array(4),
  insetT: new Float32Array(4).fill(NaN),
  insetR: new Float32Array(4).fill(NaN),
  insetB: new Float32Array(4).fill(NaN),
  insetL: new Float32Array(4).fill(NaN),
  fontSize: new Float32Array(4).fill(16),
  fontWeight: new Uint16Array(4).fill(400),
  overflowX: new Uint8Array(4),
  overflowY: new Uint8Array(4),
  scrollbarWidth: new Uint8Array(4),
  scrollbarThumb: new Uint32Array(4),
  scrollbarTrack: new Uint32Array(4),
} satisfies StyleTable;

export const nodes = {
  count: 47,
  kind: new Uint8Array([0,0,0,1,0,1,0,0,0,1,0,1,0,1,0,0,1,0,1,0,1,0,0,1,0,1,0,1,0,0,1,0,1,0,1,0,1,0,1,0,0,1,0,0,0,0,0]),
  style: new Uint16Array([0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,2,0,2,0,2,0,2,0,2,0,3,0,0,1,2,2,2,2]),
  text: new Int32Array([-1,-1,-1,0,-1,1,-1,-1,-1,2,-1,3,-1,4,-1,-1,5,-1,6,-1,7,-1,-1,8,-1,9,-1,10,-1,-1,11,-1,12,-1,13,-1,14,-1,15,-1,-1,16,-1,-1,-1,-1,-1]),
  parent: new Int32Array([-1,0,1,2,1,4,0,6,7,8,7,10,7,12,6,14,15,14,17,14,19,6,21,22,21,24,21,26,0,28,29,28,31,28,33,28,35,28,37,0,39,40,39,42,42,42,42]),
  firstChild: new Int32Array([1,2,3,-1,5,-1,7,8,9,-1,11,-1,13,-1,15,16,-1,18,-1,20,-1,22,23,-1,25,-1,27,-1,29,30,-1,32,-1,34,-1,36,-1,38,-1,40,41,-1,43,-1,-1,-1,-1]),
  nextSibling: new Int32Array([-1,6,4,-1,-1,-1,28,14,10,-1,12,-1,-1,-1,21,17,-1,19,-1,-1,-1,-1,24,-1,26,-1,-1,-1,39,31,-1,33,-1,35,-1,37,-1,-1,-1,-1,42,-1,-1,44,45,46,-1]),
  list: new Int16Array(47).fill(-1),
  hidden: new Uint8Array(47),
} satisfies NodeTable;

/**
 * Conditional styling, sparse and sorted by node.
 *
 * mask is the predicate bits a node reads; slots[runStart + i] is its style for
 * the combination whose compacted bits equal i. Runs are shared between nodes
 * that resolve identically.
 */
export const variants = {
  count: 0,
  node: new Int32Array([]),
  mask: new Uint32Array([]),
  runStart: new Int32Array([]),
  slots: new Uint16Array([]),
} satisfies VariantTable;

/** Nodes that can receive input, sorted. Emitted, never inferred. */
export const interactive = new Int32Array([]);

/** Dynamic text runs. Literal chunks interleaved with the signals they read. */
export const textBindings = [

] satisfies TextBinding[];

/** Click handlers, as direct references to the app's exported functions. */
export const handlers = [

] satisfies HandlerBinding[];

/** Nodes that route keystrokes into a string signal while focused. */
export const editables = [

] satisfies EditableRef[];

/**
 * Conditional classes, compiled to style-table writes.
 *
 * Each entry writes field values for the slots the class actually changes — no
 * class names, no cascade, and node style pointers untouched. affectsLayout says
 * whether applying it requires a relayout or only a repaint.
 */
export const stylePatches = [

] satisfies StylePatchRef[];

/**
 * Dynamic lists. Each owns a contiguous arena of identical item subtrees; the
 * runtime rewrites the child chain and the bound slots, never the nodes.
 */
export const lists = {
  count: 0,
  container: new Int32Array([]),
  anchorPrev: new Int32Array([]),
  anchorNext: new Int32Array([]),
  arenaStart: new Int32Array([]),
  stride: new Int32Array([]),
  capacity: new Int32Array([]),
  active: new Int32Array(0),
  dataOffset: new Int32Array(0),
} satisfies ListTable;

/** Per-list: the array signal, key path, and where each item's bound slots live. */
export const listBindings = [

] satisfies ListBindingRef[];

export const root: number = 0;
